<meta charset="UTF-8">
<script type="text/javascript" src="<?php echo($this->basePath('js/module/dispo/tipocajamatriz/mantenimiento.js')); ?>"></script>
<script type="text/javascript" src="<?php echo($this->basePath('js/module/dispo/tipocajamarcacion/mantenimiento.js')); ?>"></script>
<script>
	$(document).ready(function () {
		InputData_TrimAll();
		InputData_initNumberNoDecimal();
	});//$(document).ready
</script>

   	<div class="title-admin-section">
        <h1>PANEL DE CAJAS</h1>
    </div>  
    
	<div class="table-container">
	
		  <!-- Nav tabs -->
		  <ul class="nav nav-tabs" role="tablist">
			    <li role="presentation" class="active"><a href="#grupo_dispo" aria-controls="grupo_dispo" role="tab" data-toggle="tab">MATRIZ</a></li>
			    <li role="presentation"><a href="#grupo_precio" aria-controls="grupo_precio" role="tab" data-toggle="tab">MARCACION</a></li>
		  </ul>
		
		  <!-- Tab panes -->
		  <div class="tab-content">
          
          		<!-- TAB MANTENIMIENTO DE TIPO CAJA MATRIZ --->
			    <div role="tabpanel" class="tab-pane active" id="grupo_dispo">
                    <form id="frm_tipo_caja_busqueda" name="frm_tipo_caja_busqueda" action="#" method="post" class="form-inline">
                        <div class="form-group">
                             <section class="body-admin-section">
                                <div class="accion-admin-section">
                                 	<div class="botonera-admin-section pull-left separator">
                                        <button type="button" class="btn btn-primary btn-xs" data-toggle="modal_nueva_variedad" data-target="modal_nueva_variedad" id="btn_nueva_caja_matriz"><i class="glyphicon glyphicon-plus"></i> CREAR CAJA MATRIZ </button>
                                    </div>   
                                    <!-- div class="botonera-admin-section pull-left separator">
                                        <button id="btn_actualizacion_masiva" type="button" class="btn btn-primary btn-xs"><i class="glyphicon glyphicon-plus"></i> ACTUALIZACION MASIVA</button>
                                    </div -->                    
                                    <div class="busqueda-admin-section pull-left">
                                         <!-- select  id="tipo_caja_id" class="form-control input-sm"></select -->                        
                                         <select  id="inventario_id" class="form-control input-sm"></select>
                                         <button id="btn_consultar" type="button" class="btn btn-primary btn-xs"><i class="glyphicon glyphicon-search"></i> BUSCAR</button>
                                    </div>
                                </div>
                             </section>
                             
                             
                        </div>
                        <div class="row-fluid">                                	
                            <table id="grid_tipo_caja_matriz" class="grid grid-autoheight"></table>
                            <div id="pager_tipo_caja_matriz"></div>
                        </div>
                    </form>            
                    
                    
                    <!-- Modal ACTUALIZACION MASIVA TIPO CAJA MATRIZ ------------------------------->
                    <div class="modal fade" id="dialog_tipo_caja_actualizacion" tabindex="-1" role="dialog" aria-labelledby="Dialogo para el la actualizacion masiva de Unidades de Bunchs para las cajas">
                        <div class="modal-dialog modal-md" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                    <h4 class="modal-title" id="myModalLabel">ACTUALIZACION MASIVA</h4>
                                </div>
                                <div class="modal-body">
                                    <form id="frm_tipo_caja_matenimiento" name="frm_tipo_caja_matenimiento" action="#" method="post" class="form-horizontal" />
                                        <input type="hidden" id="inventario_id" value="" />
                                        <input type="hidden" id="tipo_caja_id" value="" />
                                        <div class="form-group">                                                
                                            <label for="id" class="col-md-4 control-label">Tipo Caja:</label>
                                            <div class="col-md-8">
                                                 <p class="form-control-static" id="tipo_caja_nombre">X</p>
                                            </div>
                                        </div>
            
                                        <div class="form-group">
                                            <label for="nombre" class="col-md-4 control-label">Inventario:</label>
                                            <div class="col-md-8">
                                                <p class="form-control-static" id="inventario_nombre">X</p>
                                            </div>
                                        </div>
            
                                        <div class="form-group">
                                            <label for="inventario_id" class="col-md-4 control-label">Variedad:</label>
                                            <div class="col-md-8">
                                                <select  id="variedad_id" class="form-control"></select>
                                            </div>
                                        </div>
            
                                        <div class="form-group">                                                
                                            <label for="calidad_id" class="col-md-4 control-label">Grado:</label>
                                            <div class="col-md-8">
                                                <select  id="grado_id" class="form-control"></select>                                                    
                                            </div>
                                        </div>
            
                                        <div class="form-group">
                                            <label for="nombre" class="col-md-4 control-label">Bunches Por Caja:</label>
                                            <div class="col-md-8">
                                                <input type="text" class="form-control" id="unds_bunch" placeholder="Cantidad de Bunchs" validate="required" validateMessage="Ingrese cantidad de Bunches">
                                            </div>
                                        </div>
            
                                        <div class="form-group">                                                                                                   
                                            <div class="col-md-offset-2 col-md-10 text-right">
                                                <button id="btn_grabar" type="button" class="btn btn-primary btn-sm"><i class="glyphicon glyphicon-ok"></i> GRABAR</button>
                                            </div>
                                        </div>
                                    </form>
            
                                </div>
                            </div>
                        </div>
                    </div>                              
                    
                     <!-- END Modal ACTUALIZACION MASIVA TIPO CAJA MATRIZ -------------------------------------------------->  	 

			    </div>


				<!-- TAB MANTENIMIENTO DE TIPO CAJA MARCACION --->
			    <div role="tabpanel" class="tab-pane" id="grupo_precio">
                    <form id="frm_tipo_caja_marcacion" name="frm_tipo_caja_marcacion" action="#" method="post" class="form-inline">
                        <div class="form-group">
                             <section class="body-admin-section">
                                <div class="accion-admin-section">
                                    <div class="botonera-admin-section pull-left separator">
                                        <button id="btn_grabar" type="button" class="btn btn-primary btn-xs"><i class="glyphicon glyphicon-ok"></i> GRABAR</button>
                                    </div>                    
                                    <div class="busqueda-admin-section pull-left">
                                         <input type="text"  id="cliente_nombre" class="form-control input-sm" placeholder="Cliente" />                        
                                         <input type="text"  id="marcacion_nombre" class="form-control input-sm" placeholder="Marcacion" />
                                         <button id="btn_consultar" type="button" class="btn btn-primary btn-xs"><i class="glyphicon glyphicon-search"></i> BUSCAR</button>
                                    </div>
                                </div>
                             </section>
                        </div>
                        <div class="form-inline">
                            <div class="form-group">
                                 <button id="btn_row_new" type="button" class="btn btn-primary btn-xs btn-success"><i class="glyphicon glyphicon-plus"></i></button>
                                 <button id="btn_row_eliminar" type="button" class="btn btn-primary btn-xs btn-success"><i class="glyphicon glyphicon-minus"></i></button>
                            </div>
                        </div>            
                        <div class="row-fluid">                                	
                            <table id="grid_tipo_caja_marcacion" class="grid grid-autoheight"></table>
                            <div id="pager_tipo_caja_marcacion"></div>
                        </div>
                    </form>            
			    
			    </div>
		  </div>
		
	</div>
	
	
	<!-- MODAL PARA NUEVA VARIEDAD -->
	
		<div class="modal fade" tabindex="modal_matenimiento_caja_matriz" role="dialog" aria-labelledby="modal_matenimiento_caja_matriz" id="modal_matenimiento_caja_matriz">
			  <div class="modal-dialog">
				    <div class="modal-content">
				    	<form id="form_mantenimiento_caja_matriz" name="form_mantenimiento_caja_matriz" class="form-horizontal">
					    	<div class="modal-header">
						    		<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						    		<span aria-hidden="true">&times;</span></button>
		        					<h4 class="modal-title" id="modal_matenimiento_caja_matriz_titulo"></h4>
					    	</div>
					    	<div class="modal-body">
										 <div class="form-group">
										 		<label for="tipo_caja_id" class="col-sm-3 control-label">Tipo Caja:</label>
											    <div class="col-sm-8">
											      <select  id="tipo_caja_id" class="form-control" validate="required" validateMessage="Seleccione Tipo de Caja"></select>
											    </div>
										 </div>
										 		 <div class="col-sm-10">
											     <select  id="inventario_id" class="form-control" style="display:none;"></select>
											    </div>
										 <div class="form-group">
											    <label for="tamano_bunch_id" class="col-sm-3 control-label">Tamaño Bunch:</label>
											    <div class="col-sm-8">
											      <select  id="tamano_bunch_id" class="form-control" validate="required" validateMessage="Seleccione Tanaño Bunch"></select>
											    </div>
										  </div>
										  <div class="form-group">
											    <label for="tallos_x_bunch" class="col-sm-3 control-label">Tallos:</label>
											    <div class="col-sm-8">
											      <input type="text" class="form-control inputdata-number-no-decimal" id="tallos_x_bunch" maxlength="6" validate="required" validateMessage="Ingrese la Cantidad de Tallos">
											    </div><br>
										  </div>
										<div class="row" align="center">
											
											  <div class="col-md-12">
					                            <table id="grid_mantenimiento_caja_matriz" class="grid"></table>
					                            <div id="pager_mantenimiento_caja_matriz"></div>					                            
					                        </div><br>
					                         <!-- 
					                        <div class="col-md-12" id="id_grid__caja_matriz_data">
					                            <table id="grid_caja_matriz_data" class="grid"></table>
					                            <div id="pager_caja_matriz_data"></div>
					                        </div>
					                         -->
					                    </div><br>
							</div>
							<div class="modal-footer">
									<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
	        						<button type="button" class="btn btn-primary" id="btn_grabar_caja_matriz" name="btn_grabar_caja_matriz">Guardar</button>	
							</div>
						</form>
				    </div><!-- end div modal-dialog -->
			  </div><!-- end div modal-dialog -->
		</div> <!-- end div modal fade -->
	