


<?php
 		if ($this->identidad_usuario["perfil_id"] == \Application\Constants\Perfil::ID_VENTAS){ ?>
 				<script>
	 				$(document).ready(function ()
	 				{
<?php 
	 					if ((empty($this->identidad_usuario["cliente_id"]))||(empty($this->identidad_usuario["cliente_usuario_id"])))
	 					{
?>	 					
							$('#dialog_seleccion_cliente').modal('show');

<?php
 						}//end if
?>
						consultar_cliente();


						$("#dialog_seleccion_cli_cliente").on('change', function(event){
							var cliente_id = $("#dialog_seleccion_cli_cliente").val();

							if (cliente_id=='') return false;
								
							consulta_usuario_cliente(cliente_id);
						});
						
		 				
	 			        $("#dialog_btn_seleccion_cli").on('click', function(event){
	 						var cliente_id 	= $("#dialog_seleccion_cli_cliente").val();
	 						var usuario_id 	= $("#dialog_seleccion_cli_usuario").val();

	 						//Se valida que tenga un cliente seleccionado
	 						if (cliente_id==''){
	 							swal({  title: "ALERTA",   
									text: 'Debe de seleccionar un cliente',		    											
									type: "info",
									html: false,
									showCancelButton: false,
									confirmButtonColor: "#DD6B55",
									showConfirmButton: true,
	 							},
								function(isConfirm){
	 								$("#dialog_seleccion_cli_cliente").focus();	 							
 								});								
	 							return false;
	 						}//end if


	 						if (usuario_id==''){
	 							swal({  title: "ALERTA",   
									text: 'Debe de seleccionar un usuario para el cliente',		    											
									type: "warning",
									html: false,
									showCancelButton: false,
									confirmButtonColor: "#DD6B55",
									showConfirmButton: true,
	 							},
								function(isConfirm){									
	 								$("#dialog_seleccion_cli_usuario").focus();
 								});
								return false;
	 						}//end if

							/*-----------------------------------------------------*/
	 						var data = 	{
	 		 							texto_primer_elemento: "&lt;Clientes&gt;",
	 		 							cliente_id: cliente_id,
	 		 							usuario_id: usuario_id
	 		 							};
							data = JSON.stringify(data);

							//var data = '';
							var parameters = {	'type': 'POST',
												'contentType': 'application/json',
												'url':'<?php echo($this->basePath()); ?>/seguridad/usuario/asignarClienteUsuario',
												'cancel_process_previous':false,
												'show_cargando':true,
												'finish':function(response){
														if (response.respuesta_code=='OK'){
															swal({  title: "Asignando Cliente y Usuario al Vendedor ...",   
				    											text: "",  
				    											type: "success",
				    											showCancelButton: false,
				    											timer: 2000,
				    										});

				    										//Cierra el dialogo		
				    										$("#dialog_seleccion_cliente").modal('hide');
<?php				    									if ($this->opcion_consulta == 'view_seleccionar_marcacion')
															{	
?>
					    										consultar_marcacion();   //OJO AQUI HAY QUE PREGUNTAR LA CARGA
					    										$("#identidad_cliente").html(response.cliente_nombre + ' - ' + response.cliente_usuario_nombre);
<?php
 															}//end if
?>
														}else{
															message_error('ERROR', response);
														}//end if								
												}							
							                 }
							response = ajax_call(parameters, data);		
							/*------------------------------------------------------*/
	 						
	 						return false;
	 			        });//end function $("#dialog_btn_seleccion_cli").on('click',
	 				});//$(document).ready




					function consultar_cliente(){
						var data = {texto_primer_elemento: "&lt;Clientes&gt;"}
						data = JSON.stringify(data);

						$("#dialog_seleccion_cli_cliente").html('cargando...');
						//var data = '';
						var parameters = {	'type': 'POST',
											'contentType': 'application/json',
											'url':'<?php echo($this->basePath()); ?>/dispo/cliente/getcombo',
											'cancel_process_previous':false,
											'async': true,											
											'show_cargando':true,
											'finish':function(response){
													if (response.respuesta_code=='OK'){
														$("#dialog_seleccion_cli_cliente").html(response.opciones);									
													}else{
														message_error('ERROR', response);
													}//end if								
											}							
						                 }
						response = ajax_call(parameters, data);		
						return false;
					}//end function consultar_cliente	


					

					function consulta_usuario_cliente()
					{
						var data = {
									texto_primer_elemento: "&lt;Usuario Cliente&gt;",
									cliente_id: $("#dialog_seleccion_cli_cliente").val()
									}
						data = JSON.stringify(data);

						$("#dialog_seleccion_cli_usuario").html('cargando...');
						//var data = '';
						var parameters = {	'type': 'POST',
											'contentType': 'application/json',
											'url':'<?php echo($this->basePath()); ?>/seguridad/usuario/getcomboPorCliente',
											'cancel_process_previous':false,
											'async': true,
											'show_cargando':false,
											'finish':function(response){
													if (response.respuesta_code=='OK'){
														$("#dialog_seleccion_cli_usuario").html(response.opciones);									
													}else{
														message_error('ERROR', response);
													}//end if								
											}							
						                 }
						response = ajax_call(parameters, data);		
						return false;
					}//end function consulta_usuario_cliente	 				
 				</script>


			    <div id="dialog_seleccion_cliente" class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="Modal Asignar Clientes" aria-hidden="true">
			      <div class="modal-dialog modal-sm">
			        <div class="modal-content">
			          <div class="modal-header">
			            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
			            <h4 class="modal-title" id="myModalLabel">Escoger Cliente</h4>
			          </div>
			          <div class="modal-body clearfix">
			            <form method="post" name="cliente_assign" action=<?php echo htmlspecialchars($_SERVER["PHP_SELF"]); ?>>
			                <div class="clearfix">
			                    <select id="dialog_seleccion_cli_cliente"  class="form-control select-class" style="width:100%; margin-bottom: 10px;">
			                    </select>
			                    <select class="form-control flo-left" style="width:100%; margin-bottom: 10px;" id="dialog_seleccion_cli_usuario" >
			                    	<option value="">&lt;Usuario Cliente&gt;</option>
			                    </select>
			                    <input type="button" id="dialog_btn_seleccion_cli" class="add-label flo-right pointer"  value="Save This" style="margin-top: 5px;">
			                </div>
			            </form>                    
			          </div>
			        </div>
			      </div>
			    </div>
<?php 
		}//end if 