<meta charset="UTF-8">
<script type="text/javascript" src="<?php echo($this->basePath('js/module/dispo/tipocajamarcacion/mantenimiento.js')); ?>"></script>
<script>
	$(document).ready(function () {
		InputData_TrimAll();
	});//$(document).ready
</script>


<div class="title-admin-section">
	<h1>CAJA MARCACION</h1>
</div>            

<div class="row">   
	<section class="body-admin-section">                
					
		<form id="frm_tipo_caja" name="frm_tipo_caja" action="#" method="post" class="form-inline">
			<div class="form-group">
				 <section class="body-admin-section">
					<div class="accion-admin-section">
                        <div class="botonera-admin-section pull-left separator">
                            <button id="btn_grabar" type="button" class="btn btn-primary btn-xs"><i class="glyphicon glyphicon-ok"></i> GRABAR</button>
                        </div>                    
						<div class="busqueda-admin-section pull-left">
							 <input type="text"  id="cliente_nombre" class="form-control input-sm" placeholder="Cliente" />                        
							 <input type="text"  id="marcacion_nombre" class="form-control input-sm" placeholder="Marcacion" />
							 <button id="btn_consultar" type="button" class="btn btn-primary btn-xs"><i class="glyphicon glyphicon-search"></i> BUSCAR</button>
						</div>
					</div>
				 </section>
			</div>
            <div class="form-inline">
                <div class="form-group">
    				 <button id="btn_row_new" type="button" class="btn btn-primary btn-xs btn-success"><i class="glyphicon glyphicon-plus"></i></button>
                     <button id="btn_row_eliminar" type="button" class="btn btn-primary btn-xs btn-success"><i class="glyphicon glyphicon-minus"></i></button>
                </div>
			</div>            
			<div class="row-fluid">                                	
				<table id="grid_tipo_caja" class="grid grid-autoheight"></table>
				<div id="pager_tipo_caja"></div>
			</div>
		</form>            
        
        
	</section>
</div>	            
