
<meta charset="UTF-8">
	<script type="text/javascript" src="<?php echo($this->basePath('js/module/dispo/grupocliente/init.js')); ?>"></script>
   	<script type="text/javascript" src="<?php echo($this->basePath('js/module/dispo/grupocliente/dispo_x_grupo.js')); ?>"></script>

   	
   	<div class="title-admin-section">
        <h1>GRUPO CLIENTE</h1>
    </div>  
    
	<div class="table-container">
	
		  <!-- Nav tabs -->
		  <ul class="nav nav-tabs" role="tablist">
			    <li role="presentation" class="active"><a href="#grupo_dispo" aria-controls="grupo_dispo" role="tab" data-toggle="tab">GRUPO DISPO</a></li>
			    <li role="presentation"><a href="#grupo_precio" aria-controls="grupo_precio" role="tab" data-toggle="tab">GRUPO PRECIO</a></li>
		  </ul>
		
		  <!-- Tab panes -->
		  <div class="tab-content">
			    <div role="tabpanel" class="tab-pane active" id="grupo_dispo">
			   		
					MORONITOR (GRUPO DISPO)
			    </div>
			    
			    <div role="tabpanel" class="tab-pane" id="grupo_precio">
					MORONITOR (GRUPO PRECIO)
			    
			    </div>
		  </div>
		
	</div>
	
	
	
	        
	        