



    <div class="title-admin-section">
        <h1>GRUPO CLIENTES</h1>
    </div>  
    
    <div class="row">   
        <section class="body-admin-section">                
            
            <div id="grupos_cliente_usuario" class="table-container col-md-16 col-sm-16">	      
                  <!-- Nav tabs -->
                  <ul class="nav nav-tabs" role="tablist">
                    <li role="presentation" class="active"><a href="tab_grupo_dispo" aria-controls="tab_grupo_dispo" role="tab" data-toggle="tab">GRUPO DISPO</a></li>
                    <li role="presentation"><a href="tab_grupo_precio" aria-controls="tab_dis" role="tab" data-toggle="tab">GRUPO PRECIO</a></li>
                  </ul>
                  
                  
                   <!-- Tab panes -->
                  <div class="tab-content" style="margin-top:10px">
                    <div role="tabpanel" class="tab-pane active" id="tab_grupo_dispo">
                        <div class="panel panel-default">
                        <br>
                        CONTENIDO TAP1
                        
                        </div>
                    </div>
                  </div> 
                  
                   <div class="tab-content" style="margin-top:10px">
                    <div role="tabpanel" class="tab-pane active" id="tab_grupo_precio">
                        <div class="panel panel-default">
                        <br>
                        CONTENIDO TAP1
                        
                        </div>
                    </div>
                  </div> 
            </div>
      	</section>
	</div>  
                  
        
    

    
