<script type="text/javascript" src="C:\Users\Profeta\Desktop\PRUEBA WEB\js\jqgrid/grid.locale-es.js" ></script>
<script type="text/javascript" src="C:\Users\Profeta\Desktop\PRUEBA WEB\js\jqgridExcelExportClientSide.js" ></script>
<script type="text/javascript" src="C:\Users\Profeta\Desktop\PRUEBA WEB\js\jqgridExcelExportClientSide-libs.js" ></script>
<script>
		$(document).ready(function () {

			 $.jgrid.no_legacy_api = true; 
			   $.jgrid.useJSON = true; 
			/*---------------------------------------------------------------*/
			/*-----------------Se configura los JQGRID's---------------------*/
			/*---------------------------------------------------------------*/		
			jQuery("#grid_color_ventas").jqGrid({
				url:'../../dispo/prueba/listadodata',
				postData: {
				},
				datatype: "json",
				loadonce: true,		
				gridview:false,	
				/*height:'400',*/
				colNames:['Código','Nombre'],
				colModel:[
					//{name:'seleccion',index:'', width:50,  formatter: 'checkbox', align: 'center',editable: true, formatoptions: {disabled : false}, editoptions: {value:"1:0" },editrules:{required:false}},
					{name:'id',index:'id', width:50, align:"center", sorttype:"int"},
					{name:'nombre',index:'nombre', width:230, sorttype:"string"}
				],
				rowNum:999999999,
				pager: '#pager_colorventas',
				toppager:false,
				pgbuttons:false,
				pginput:false,
				rowList:false,
				gridview: false,
				shrinkToFit: false,
				loadComplete:  grid_setAutoHeight, 
				resizeStop: grid_setAutoHeight, 
				rownumbers: true,
				jsonReader: {
					repeatitems : false,
				},		
				
				loadBeforeSend: function (xhr, settings) {
					this.p.loadBeforeSend = null; //remove event handler
					return true; // dont send load data request
				},				
				loadError: function (jqXHR, textStatus, errorThrown) {
					message_error('ERROR','HTTP message body (jqXHR.responseText): ' + '<br>' + jqXHR.responseText);
				}
			});
			jQuery("#grid_color_ventas").jqGrid('navGrid','#pager_colorventas',{edit:false,add:false,del:false});
			
			
			//Se configura el grid para que pueda navegar procesar la fila con el ENTER
			jQuery("#grid_color_ventas").jqGrid('bindKeys', {
				   "onEnter" : function( rowid ) { 
						//marcacion_consultar_listado(rowid);
						var data = $('#grid_color_ventas').getRowData(rowid);
						marcacion_consultar_listado("+data.marcacion_sec+");
				   }
			});

			// add custom button to export the data to excel
			jQuery("#grid_color_ventas").jqGrid('navButtonAdd','#pager_colorventas',{
			       caption:"", 
			       onClickButton : function () { 
			           //jQuery("#grid_color_ventas").jqGrid('excelExport',{"url":"../../dispo/prueba/listadodata"});
			            $("#grid_color_ventas").jqGrid('exportarExcelCliente',{nombre:"HOJATEST",formato:"excel"});
			       } 
			});

			/*---------------------------------------------------------------*/	
			/*---------------------------------------------------------------*/
		
		});//$(document).ready


    </script>



	<div class="title-admin-section">
		<h1>PRUEBA EXCEL</h1>
	</div>


<div class="row">
<br>
	<div class="clearfix" id="grid_color">
    	<table id="grid_color_ventas" class="grid grid-autoheight" ></table>
    	<div id="pager_colorventas"></div>
    </div>
</div>   
	
	