<script type="text/javascript" src="<?php echo($this->basePath('js/module/dispo/tipo_caja/popup_tipo_caja.js')); ?>"></script>
 
 <style type="text/css">
	 		.zoom{
				transition: 1.5s ease;
		 		-moz-transition: 1.5s ease; /* Firefox */
		 		-webkit-transition: 1.5s ease; /* Chrome - Safari */
		 		-o-transition: 1.5s ease; /* Opera */
			}
			.zoom:hover{
				transform : scale(2);
				-moz-transform : scale(1.5); /* Firefox */
				-webkit-transform : scale(1.5); /* Chrome - Safari */
				-o-transform : scale(1.5); /* Opera */
				-ms-transform : scale(1.5); /* IE9 */
	 		}
	 </style>

	<style>
		.margen_imagen { 
		  padding: 0px  0px; 
		  border: PowderBlue 4px solid; 
		  border-radius: 10px; 
		}
		
		.margen { 
		  padding: 0px  0px; 
		  border: PowderBlue 4px solid; 
		  border-radius: 10px; 
		}
		
		.shadow{
		-webkit-box-shadow: 0px 0px 29px -2px rgba(99,184,230,0.81);
		-moz-box-shadow: 0px 0px 29px -2px rgba(99,184,230,0.81);
		box-shadow: 0px 0px 29px -2px rgba(99,184,230,0.81);
		}
 		
	</style>
	<div class="title-admin-section">
		<h1>BOX TYPE</h1>
	</div>


	<BR>
	<button type="button" class="btn btn-primary btn-sm " data-toggle="modal" data-target="#popup_tipo_cajas" >Box</button>

	<div class="modal fade bs-example-modal-lg" role="dialog" aria-labelledby="popup_tipo_cajas" id="popup_tipo_cajas" name="popup_tipo_cajas" > 
		<div class="modal-dialog modal-dialog-fullscreen" role="document">
			<div class="modal-content">
			      <div class="modal-header">
			        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			        <h4 class="modal-title" id="tipo_cajas">BOX TYPE</h4>
			      </div>
			      <div class="modal-body">
			      	<div class="row" id="row_box">
			      	<form class="form-horizontal" role="form" name="frm_popup_tipo_cajas" id="frm_popup_tipo_cajas">
			      		<?php  
				            $i=0;
				            foreach($this->result as $reg)
				            {
				                $i++; 
						?>
					        	<div class="col sm-12" >
						        		<div class="col-sm-1">
						        			<img src="<?php echo ($this->basePath().$reg['url_foto']); ?>" class="img-responsive margen_imagen zoom" style="width: 100px; height: 160px; display: block; " >
						        		</div>
						        		<div class="col-sm-2">
						        			<table class="table table-striped table-bordered margen">
						        				<caption><?php echo($reg['nombre']); ?></caption>
						        				<tbody>
											        <tr>
											          <th>Length:</th>
											          <th><?php echo($reg['largo'].' '.'cm'); ?></th>
											        </tr>
											        <tr>
											          <th>Width:</th>
											          <th><?php echo($reg['ancho'].' '.'cm'); ?></th>
											        </tr>
											        <tr>
											          <th>Height:</th>
											          <th><?php echo($reg['alto'].' '.'cm'); ?></th>
											        </tr>
										        </tbody>
						        			</table>
					        		</div>
					        	</div>
					        	<?php }//end foreach ?>
					    </form>
					</div>
				</div>
			</div><!-- /.modal-content -->
		</div>
	</div> <!-- /.modal -->
	
			