
<script>
$(document).ready(function () {
	InputData_UpperCaseAll();		
	InputData_TrimAll();
/*		InputData_KeyEnterDisabled();*/
//	InputData_initNumberAndDecimal();
	
	

	$('table').tablesorter(); //Columna de Sueldo
	$("table").stickyTableHeaders();


    $("#btn_consultar").on('click', function(event){ 
        $("#frm").submit();
		return false;
    });

    $("#btn_nuevo").on('click', function(event){
		nuevo(); 
		return false;
    });       

    $(".btn_edit").on('click', function(event){ 
		var tr 						= $(this).closest('tr');
		var cliente_id 			= tr.attr('cliente_id');

		consultar_cliente(cliente_id);
		//$("#dialog_mantenimiento").modal('show') 
    });

	
    $("#tbl_registros tbody tr").on('dblclick', function(event){ 
		var tr 						= $(this).closest('tr');
		var cliente_id 		= tr.attr('cliente_id');

		consultar_cliente(cliente_id);
		//$("#dialog_mantenimiento").modal('show') 
    });	

	
    $("#tbl_registros tbody tr").on('dblclick', function(event){ 
		var tr 						= $(this).closest('tr');
		var cliente_id 			= tr.attr('cliente_id');

		consultar_cliente_id(cliente_id);
		//$("#dialog_mantenimiento").modal('show') 
    });		

    $("#btn_grabar").on('click', function(event){ 
    	grabar();
		return false;
    });       

	        
	function nuevo()
	{
		//Se llama mediante AJAX para adicionar al carrito de compras
		var data = 	{}
		data = JSON.stringify(data);
		
		var parameters = {	'type': 'POST',//'POST',
							'contentType': 'application/json',
							'url':'<?php echo($this->basePath()); ?>/dispo/cliente/nuevodata',
							'control_process':true,
							'show_cargando':true,
							'finish':function(response){
									ValidateControlsInit();
									$("#accion").val("I");
									$("#dialog_mantenimiento_cliente_nombre").html("NUEVO REGISTRO");

									$("#cliente_id").val('');
									$("#cliente_id").prop('readonly',false);
									$("#nombre").val('');
									//$("#base").val('');
									$("#colorbase").html(response.cbo_color_base);
									//$("#estad).val('');
									$("#estado").html(response.cbo_estado);
									$("#lbl_fec_sincronizado").html('');
									$("#lbl_usuario_ing").html('');
									$("#lbl_fec_ingreso").html('');
									$("#lbl_usuario_mod").html('');
									$("#lbl_fec_modifica").html('');
									$("#sincronizado_pendiente").show();
									$("#sincronizado_ok").hide();
									
									$("#dialog_mantenimiento").modal('show')
							}							
		                 }
		response = ajax_call(parameters, data);		
		return false;				
	}//end function nuevo
        



    function grabar(){
		if (!ValidateControls('frm')) {
			return false;
		}
		
		//Se llama mediante AJAX para adicionar al carrito de compras
		var data = 	{	accion: $("#accion").val(),
					 	id: $("#cliente_id").val(),
					 	nombre: $("#nombre").val(),
					 	colorbase: $("#colorbase").val(),
					 	estado: $("#estado").val(),
					}
		data = JSON.stringify(data);
		
		var parameters = {	'type': 'POST',//'POST',
							'contentType': 'application/json',
							'url':'<?php echo($this->basePath()); ?>/dispo/cliente/grabardata',
							'control_process':true,
							'show_cargando':true,
							'finish':function(response){
									if (response.validacion_code == 'OK')
									{
										mostrar_registro(response)
										cargador_visibility('hide');
										swal({  title: "Informacion grabada con exito!!",   
											//text: "Desea continuar utilizando la misma marcacion? Para seguir realizando mas pedidos",  
											//html:true,
											type: "success",
											showCancelButton: false,
											confirmButtonColor: "#DD6B55",
											confirmButtonText: "OK",
											cancelButtonText: "",
											closeOnConfirm: false,
											closeOnCancel: false,
											/*timer: 2000*/
										});
									}else{
										swal({title: response.respuesta_mensaje,   
											//text: "Desea continuar utilizando la misma marcacion? Para seguir realizando mas pedidos",  
											//html:true,
											type: "error",
											showCancelButton: false,
											confirmButtonColor: "#DD6B55",
											confirmButtonText: "OK",
											cancelButtonText: "",
											closeOnConfirm: false,
											closeOnCancel: false,
											/*timer: 2000*/
										});
									
									}									
							}							
		                 }
		response = ajax_call(parameters, data);		
		return false;		
	}//end function grabar



	function consultar_cliente(id)
	{
		//Se llama mediante AJAX para adicionar al carrito de compras
		var data = 	{cliente_id: id}
		data = JSON.stringify(data);
		
		var parameters = {	'type': 'POST',//'POST',
							'contentType': 'application/json',
							'url':'<?php echo($this->basePath()); ?>/dispo/cliente/consultardata',
							'control_process':true,
							'show_cargando':true,
							'finish':function(response){
									mostrar_registro(response)
									cargador_visibility('hide');

									$("#dialog_mantenimiento").modal('show')
							}							
		                 }
		response = ajax_call(parameters, data);		
		return false;		
	}//end function consultar_cliente

	function mostrar_registro(response)
	{
		var row = response.row;
		if (row!==null)
		{
			ValidateControlsInit();
			$("#accion").val("M");			
			$("#dialog_mantenimiento_cliente_nombre").html(row.nombre);
			$("#cliente_id").val(row.id);
			$("#cliente_id").prop('readonly',true);
			$("#nombre").val(row.nombre);
			$("#direccion").html(response.cbo_color_base);
			$("#pais_id").html(response.cbo_estado);
			$("#lbl_fec_ingreso").html(row.fec_ingreso);
			$("#lbl_fec_modifica").html(row.fec_modifica);
			$("#lbl_usuario_ing").html(row.usuario_ing_user_name);
			$("#lbl_usuario_mod").html(row.usuario_mod_user_name);
			$("#lbl_fec_sincronizado").html(row.fec_sincronizado);
			
			
			
			
			if (row.sincronizado==1)
			{
				$("#sincronizado_pendiente").hide();
				$("#sincronizado_ok").show();
			}else{
				$("#sincronizado_pendiente").show();
				$("#sincronizado_ok").hide();
			}//end if
		}//end if
	}//end function mostrar_registro



	
	});//$(document).ready
    </script>



<div class="title-admin-section">
	<h1>cliente</h1>
</div>



<div class="table-container col-md-16 col-sm-16">
  <div class="clearfix">
        	<div class="pull-left">
            	<a id="btn_nuevo" class="btn btn-small btn-success" href="#"><i class="glyphicon glyphicon-plus icon-white"></i> Nuevo</a>
            </div>
        	<div class="pull-right">
            	<div class="form-inline">
                	<form id="frm" action="<?php echo($this->basePath()); ?>/dispo/cliente/mantenimiento" method="post" >
                    <input name="criterio_busqueda" type="text" class="select-class2" placeholder="Search" size="20" value="<?php echo($this->criterio_busqueda); ?>" />
                    <select  name="busqueda_estado" class="select-class2">
                        <?php echo($this->busqueda_estado); ?>
                    </select>
                    <select name="busqueda_sincronizado" class="select-class2">
                    	<?php echo($this->busqueda_sincronizado); ?>
                    </select>
                    <a id="btn_consultar" class="btn btn-small btn-success"  href="#" ><i class="glyphicon glyphicon-search icon-white"></i></a>
                    </form>
				</div>
            </div>
        </div>
				<table id="tbl_registros" class="clear table-head table-dispo tablesorter tableinit tablesorter_numberrow">
		<thead>
				<tr>
				  <th  width="50" rowspan="2" class="th-inner">&nbsp;</th>
					<th  width="100" rowspan="2" class="th-inner">ID</th>				
					<th  width="0" rowspan="2" class="th-inner">NOMBRE</th>
					<th  width="0" rowspan="2" class="th-inner">DIRECCION</th>
					<th  width="150" rowspan="2" class="th-inner">PAIS</th>
					<th  width="150" rowspan="2" class="th-inner">TELEFONO</th>
					<th  width="70" colspan="2" class="th-inner">SINCRONIZACION</th>					
					<th  width="70" rowspan="2" class="th-inner">ESTADO</th>
					<th  width="70" rowspan="2" class="th-inner">&nbsp;</th>
				</tr>
				<tr>
				  <th  width="70" class="th-inner">&nbsp;</th>
				  <th class="th-inner">FEC. ULTIMA VEZ</th>
		      </tr>
			</thead>
			<tbody class="searchable" style="border: 1px solid #cdcdcd;">
<?php  
		$i=0;
		foreach($this->result as $reg)
		{
			$i++;
			$class_row = '';
			if ($reg['estado']=='I'){
				$class_row = 'row_estado_inactivo';
			}
?>            
				<tr agencia_carga_id="<?php echo($reg['id']); ?>" class="<?php echo($class_row); ?>" >
				  <td><?php echo($i); ?></td>
					<td><?php echo($reg['id']); ?></td>
					<td align="left"><?php echo($reg['nombre']); ?></td>
					<td><?php echo($reg['direccion']); ?></td>
					<td><?php echo($reg['pais_nombre']); ?></td>
					<td><?php echo($reg['telefono1']); ?></td>
					<td>
					<?php if ($reg['sincronizado']==0){ ?>
						<span class="glyphicon glyphicon-time icon-white" style="color:red"></span>
					<?php }else{ ?>
						<i class="glyphicon glyphicon-ok icon-white" style="color:green"></i>
					<?php }//end if ?>	
					</td>
					<td><?php echo($reg['fec_sincronizado']); ?></td>
					<td><?php echo($reg['estado']); ?></td>
					<td><a href="#" class="btn_edit"><i class="glyphicon glyphicon-pencil icon-white" style="color:orange"></i></a></td>
				</tr>
<?php	}//end foreach ?>		
			</tbody>
		</table>   
				
    </div>
    

            <!--  DIALOG DE MANTENIMIENTO -->
            <form id="frm">
			<div class="modal fade" id="dialog_mantenimiento" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			  <div class="modal-dialog">
			    <div class="modal-content">
			      <div class="modal-header">
			        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
			        <h4 class="modal-title" id="myModalLabel">cliente (<span id="dialog_mantenimiento_cliente_nombre"></span>)</h4>
			      </div>
			      <div class="modal-body clearfix">
			        <div class="clearfix">
                        
			        	  <table border="0" align="center" cellpadding="0" cellspacing="0" class="tbl_formulario_mantenimiento">
			        	      <tr>
			        	        <td><label class="control-label">ID:</label></td>
			        	        <td>
                                <input id="cliente_id" name="cliente_id" type="text" class="form-control input-sm" style="width:50px" value="" maxlength="3" max-lenght="3" validate="required" validateMessage="Ingrese un codigo">
                                <input type="hidden" name="accion" id="accion" value="" /></td>
		        	          </tr>
			        	      <tr>
			        	        <td><label class="control-label">NOMBRE:</label></td>
			        	        <td><input name="nombre" type="text" class="form-control input-sm" id="nombre" style="width:350px" value="" maxlength="30" max-lenght="3" validate="required" validateMessage="Ingrese un nombre"></td>
		        	          </tr>
			        	      <tr>
			        	        <td><label class="control-label">COLOR BASE:</label></td>
			        		    <td><select  name="colorbase" class="select-class2" id="colorbase" validate="required"></select></td>
		        	          </tr>	
		        	           <tr>
			        	        <td><label class="control-label">ESTADO:</label></td>
			        	        <td><select  name="estado" class="select-class2" id="estado"></select></td>
		        	          </tr>		
		        	            <tr>
			        	        <td><label class="control-label">SINCRONIZADO:</label></td>
			        	        <td>
 
									<span id="sincronizado_pendiente" class="glyphicon glyphicon-time icon-white" style="color:red; display:none" ></span>
									<span id="sincronizado_ok" class="glyphicon glyphicon-ok icon-white" style="color:green; display:none"></span>
                                    <span id="lbl_fec_sincronizado"></span>
 
                                </td>
		        	          </tr>        	   
			        	      <tr>
			        	        <td>&nbsp;</td>
			        	        <td>&nbsp;</td>
		        	        </tr>

			        	      <tr>
			        	        <td><label class="control-label">Ingreso:</label></td>
			        	        <td><b><span id="lbl_usuario_ing"></span></b> - <span id="lbl_fec_ingreso"></span></td>
		        	          </tr>
			        	      <tr>
			        	        <td><label class="control-label">Modificación:</label></td>
			        	        <td><b><span id="lbl_usuario_mod"></span></b> - <span id="lbl_fec_modifica"></span></td>
		        	          </tr>
	        	      </table>
                      <br>
						<center><a id="btn_grabar" class="btn btn-small btn-success" href="#"><i class="glyphicon glyphicon-plus icon-save"></i> Grabar</a></center>
     
                      
		        	  <!--   div id="dialog_oferta_formulario"></div -->			
			        </div>
			      </div>
			    </div>
			  </div>
			</div>
			</form>
	