 <?php /*echo $this->headScript()
            ->appendFile($this->basePath('js/module/dispo/cliente/init-cliente.js'))
            ->appendFile($this->basePath('js/module/dispo/cliente/cliente.js'))
            ->appendFile($this->basePath('js/module/dispo/cliente/agencia-carga.js'))
            ->appendFile($this->basePath('js/module/dispo/cliente/marcacion.js'))
 			->appendFile($this->basePath('js/module/dispo/cliente/usuario.js'));*/
?>

<script type="text/javascript" src="<?php echo($this->basePath('js/module/dispo/cliente/init-cliente.js')); ?>"></script>
<script type="text/javascript" src="<?php echo($this->basePath('js/module/dispo/cliente/cliente.js')); ?>"></script>
<script type="text/javascript" src="<?php echo($this->basePath('js/module/dispo/cliente/marcacion.js')); ?>"></script>
<script type="text/javascript" src="<?php echo($this->basePath('js/module/dispo/cliente/agencia-carga.js')); ?>"></script>
<script type="text/javascript" src="<?php echo($this->basePath('js/module/dispo/cliente/usuario.js')); ?>"></script>


<div class="title-admin-section">
	<h1><strong>Cliente</strong></h1>
</div>

<div class="row">
	<section class="body-admin-section">    	
    	<div class="accion-admin-section"> 
    		<form id="frm_nuevo_cliente" class="form-horizontal" role="form" name="frm_nuevo_cliente">
        	<div class="botonera-admin-section pull-left separator">
            	<a id="btn_nuevo_cliente" name="btn_nuevo_cliente" class="btn btn-primary btn-xs" href="#" role="button"><i class="glyphicon glyphicon-plus icon-white"></i> NUEVO</a>
            </div>
       	  </form>	
        	<div class="busqueda-admin-section pull-left">	
            	<!--- div class="form-inline" -->
                	
                <form id="frm_busqueda_cliente" action="<?php echo($this->basePath()); ?>/dispo/cliente/mantenimiento" method="post" >
                <div class="input-group" style="display:inline-flex">    
                	<input name="criterio_busqueda" id="criterio_busqueda" type="text" class="form-control input-sm" placeholder="Search" size="20" value="<?php echo($this->criterio_busqueda); ?>" />
                     <div class="input-group">
						<select  name="busqueda_estado" id="busqueda_estado" class="form-control input-sm" style="width:130px">
	    	                <?php echo($this->busqueda_estado); ?>
    	                </select>                                       
                    </div>
 					<span class="input-group-btn">
                    	<button id="btn_consultar" class="btn btn-sm btn-primary" type="button"><i class="glyphicon glyphicon-search icon-white"></i></button>
                    </span>                        
                </div>                
               
                </form>    
			
            </div>
      </div>
        <div class="clearfix"></div>
        <div>
			<table id="grid_cliente" class="grid grid-autoheight"></table>
            <div id="pager_cliente"></div>        	
        </div>
  </section>
</div>


<!-- DIALOGO MANTENIMIENTO CLIENTE -->
<!-- Modal -->
<div class="modal fade" id="dialog_mantenimiento" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-dialog-fullscreen" role="document">
    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	        <h4 class="modal-title" id="myModalLabel">CLIENTE (<span id="dialog_mantenimiento_cliente_nombre"></span>)</h4>
	      </div>
      <div class="modal-body">
         <div id="tabs_mantenimiento_cliente">
              <!-- Nav tabs -->
              <ul class="nav nav-tabs" role="tablist">
                <li role="presentation" class="active"><a href="#tab_informacion_general" aria-controls="tab_informacion_general" role="tab" data-toggle="tab">INFORMACION GENERAL</a></li>
                <li role="presentation"><a href="#tab_marcacion" aria-controls="tab_marcacion" role="tab" data-toggle="tab">MARCACION</a></li>
                <li role="presentation"><a href="#tab_agencia_carga" aria-controls="tab_agencia_carga" role="tab" data-toggle="tab">AGENCIA DE CARGA</a></li>
                <li role="presentation"><a href="#tab_usuarios" aria-controls="tab_usuarios" role="tab" data-toggle="tab">USUARIOS</a></li>
              </ul>
            
              <!-- Tab paneL -->
              <div class="tab-content">
                <div role="tabpanel" class="tab-pane fade in active" id="tab_informacion_general">
                	<div class="row clear" >
               			<form class="form-horizontal" role="form" name="frm_informacion_general" id="frm_informacion_general">
                        <!--PRIMERA COLUMNA-->
                            <div class="col-md-4 table-striped">
                                    <div class="col-md-12" >
                                        <div class="col-md-2" >
                                            <label for="cliente_id" class="control-label"> Cliente: </label>
                                        </div>
                                        <div class="col-md-3">
                                            <input type="text" class="form-control " id="cliente_id" name="cliente_id" validate="required" validateMessage="Ingrese un Codigo" ><br/>
                                        </div>

                                        <div class="col-md-4">
                                            <label for="lbl_fec_ingreso" class="control-label">Created On:</label>
                                        </div>
                                        <div class="col-md-3">
                                            <input type="text" class="form-control" id="lbl_fec_ingreso" name="lbl_fec_ingreso" disabled><br/>
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                       <div class="col-md-2">
                                            <label for="co1" class="control-label"> Nombre: </label>
                                        </div>
                                        <div class="col-md-10">
                                            <input type="text" class="form-control" id="nombre" name="nombre" validate="required" validateMessage="Ingrese un nombre" onkeyup="this.value=this.value.toUpperCase()"><br/>
                                         </div>
                                    </div>
                                    <div class="col-md-12">
                                      <div class="col-md-2">
                                        	<label for="abreviatura" class="control-label"> Abrevia: </label>
                                      </div>
                                      <div class="col-md-4">
                                        	<input type="text" class="form-control" id="abreviatura" name="abreviatura"  onkeyup="this.value=this.value.toUpperCase()"><br/>
                                      </div>
									</div>
                                 
                                    <div class="col-md-12">
                                        <div class="col-md-2">
                                            <label for="d1" class="control-label"> Dir. : </label>
                                        </div>
                                        <div class="col-md-10">
                                            <textarea class="form-control" rows="3" style="resize:none;" id="direccion" name="direccion" validate="required" validateMessage="Ingrese una Direccion"></textarea><br/>
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="col-md-2">
                                            <label for="ciudad" class="control-label"> Ciudad: </label>
                                        </div>
                                        <div class="col-md-10">
                                            <input type="text" id="ciudad" class="form-control" name="ciudad" onkeyup="this.value=this.value.toUpperCase()" ><br/>
                                        </div>
                                    </div>
                                     <div class="col-md-12">
                                        <div class="col-md-2">
                                            <label for="co1" class="control-label"> Estado: </label>
                                        </div>
                                        <div class="col-md-10">
                                     		<select  name="estados_id" class="form-control" id="estados_id" validate="required" validateMessage="Seleccione un Estado"></select><br/>
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="col-md-2">
                                            <label for="estado_nombre" class="control-label">Est./Prov.: </label>
                                        </div>
                                        <div class="col-md-10">
                                            <input type="text" id="estado_nombre" name="estado_nombre" class="form-control" onkeyup="this.value=this.value.toUpperCase()"><br/>
                                        </div>
                              	 	</div>
                                    <div class="col-md-12">
                                        <div class="col-md-2">
                                            <label for="pais_id" class="control-label"> Pais: </label>
                                        </div>
                                        <div class="col-md-10">
                                            <select  name="pais_id" class="form-control" id="pais_id" validate="required" validateMessage="Seleccione un Pais"></select></br>
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="col-md-2">
                                        	<label for="codigo_postal" class="control-label"> ZIP: </label>
                                        </div>
                                        <div class="col-md-4">
                                       		<input type="text" class="form-control" id="codigo_postal" name="codigo_postal"><br/>
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="col-md-3">
                                            <label for="comprador" class="control-label">Comprador:</label>
                                        </div>
                                        <div class="col-md-9">
                                            <input type="text" id="comprador" name="comprador" class="form-control" onkeyup="this.value=this.value.toUpperCase()"><br/>
                                        </div>
                              	    </div>
                                  <div class="col-md-12">
                                    <div class="col-md-2">
                                        <label for="telefono1" class="control-label"> Fono1: </label>
                                    </div>
                                    <div class="col-md-7">
                                        <input type="text" class="form-control" id="telefono1" name="telefono1">
                                    </div>
                                    <div class="col-md-3">
                                        <input type="text" class="form-control" id="telefono1_ext" name="telefono1_ext"placeholder="Ext"><br/>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="col-md-2">
                                        <label for="telefono2" class="control-label"> Fono2: </label>
                                    </div>
                                    <div class="col-md-7">
                                        <input type="text" class="form-control" id="telefono2" name="telefono2">
                                    </div>
                                    <div class="col-md-3">
                                        <input type="text" class="form-control" id="telefono2_ext" name="telefono2_ext" placeholder="Ext"><br/>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="col-md-2">
                                        <label for="fax1" class="control-label"> Fax1: </label>
                                    </div>
                                    <div class="col-md-7">
                                        <input type="text" class="form-control" id="fax1" name="fax1">
                                    </div>
                                    <div class="col-md-3">
                                        <input type="text" class="form-control" id="fax1_ext" placeholder="Ext" name="fax1_ext"><br/>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="col-md-2">
                                        <label for="fax2" class="control-label"> Fax2: </label>
                                    </div>
                                    <div class="col-md-7">
                                        <input type="text" class="form-control" id="fax2" name="fax2">
                                    </div>
                                    <div class="col-md-3">
                                        <input type="text" class="form-control" id="fax2_ext" placeholder="Ext" name="fax2_ext"><br/>
                                    </div>
                               </div>
                                    
                            </div><!--END PRIMERA COLUMNA-->
                            <!--SEGUNDA COLUMNA-->
                            <div class="col-md-4">
                                    <div class="col-md-12">
                                        <div class="col-md-2">
                                            <label for="usuario_vendedor_id" class="control-label"> Vendedor: </label>
                                        </div>
                                        <div class="col-md-10">
                                            <select  name="usuario_vendedor_id" class="form-control" id="usuario_vendedor_id" validate="required" validateMessage="Seleccione un Vendedor"></select><br/>
                                        </div>
                                    </div>
                                 <div class="col-md-12">
                                        <div class="col-md-3">
                                            <label for="co1" class="control-label">Lte Cdto:</label>
                                        </div>
                                        <div class="col-md-4">
                                            <input type="text" class="form-control" id="tc_limite_credito" name="tc_limite_credito">
                                        </div>
                                        <div class="col-md-2">
                                            <label for="co1" class="control-label">Interes: </label>
                                        </div>
                                        <div class="col-md-3">
                                            <input type="text" class="form-control" id="tc_interes" name="tc_interes"><br/>
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="col-md-5">
                                            <label for="est_credito_suspendido" class="control-label">Cdto. Suspend:
                                               <input type="checkbox" id="est_credito_suspendido" name="est_credito_suspendido">
                                            </label>
                                        </div>
                                        <div class="col-md-2">
                                            <label for="credito_suspendido_razon" class="control-label">Razon:</label>
                                        </div>
                                        <div class="col-md-5">
                                            <input type="text" class="form-control" id="credito_suspendido_razon" name="credito_suspendido_razon" onkeyup="this.value=this.value.toUpperCase()"><br/>
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="col-md-2">
                                            <label for="contacto" class="control-label">Contacto: </label>
                                        </div>
                                        <div class="col-md-10">
                                            <input type="text" id="contacto" name="contacto" class="form-control" onkeyup="this.value=this.value.toUpperCase()"><br/>
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="col-md-2">
                                            <label for="cliente_factura_id" class="control-label">Fact. A:</label>
                                        </div>
                                        <div class="col-md-3">
                                            <input type="text" class="form-control" id="cliente_factura_id" name="cliente_factura_id" validate="required" validateMessage="Valor Requerido" placeholder="Codigo" autocomplete="off"><br/>
                                        </div>
                                        <div class="col-lg-7">
                                            <input type="text" class="form-control" id="cliente_factura_nombre" name="cliente_factura_nombre" placeholder="Nombre" data-provide="typeahead" autocomplete="off"><br/>
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="col-md-2">
                                            <label for="co1" class="control-label"> Fono1: </label>
                                        </div>
                                        <div class="col-md-7">
                                            <input type="text" class="form-control" id="telefono_fact1"  name="telefono_fact1_ext">
                                        </div>
                                        <div class="col-md-3">
                                            <input type="text" class="form-control" id="telefono_fact1_ext" name="telefono_fact1_ext" placeholder="Ext"><br/>
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="col-md-2">
                                            <label for="telefono_fact2" class="control-label"> Fono2: </label>
                                        </div>
                                        <div class="col-md-7">
                                            <input type="text" class="form-control" id="telefono_fact2" name="telefono_fact2">
                                        </div>
                                        <div class="col-md-3">
                                            <input type="text" class="form-control" id="telefono_fact2_ext" name="telefono_fact2_ext" placeholder="Ext"><br/>
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="col-md-2">
                                            <label for="fax_fact1" class="control-label"> Fax1: </label>
                                        </div>
                                        <div class="col-md-7">
                                            <input type="text" class="form-control" id="fax_fact1" name="fax_fact1">
                                        </div>
                                        <div class="col-md-3">
                                            <input type="text" class="form-control" id="fax_fact1_ext"  name="fax_fact1_ext" placeholder="Ext"><br/>
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="col-md-2">
                                            <label for="fax_fact2" class="control-label"> Fax2: </label>
                                        </div>
                                        <div class="col-md-7">
                                            <input type="text" class="form-control" id="fax_fact2" name="fax_fact2">
                                        </div>
                                        <div class="col-md-3">
                                            <input type="text" class="form-control" id="fax_fact2_ext" name="fax_fact2_ext" placeholder="Ext"><br/>
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="col-md-2">
                                            <label for="email_factura" class="control-label">Email: </label>
                                        </div>
                                        <div class="col-md-10">
                                            <input type="text" id="email_factura" name="email_factura" class="form-control"><br/>
                                        </div>
                                    </div>
                                  
                                    <div class="col-md-12">
                                        <div class="col-md-2">
                                        	<label for="pais_fue" class="control-label"> Pais FUE: </label>
                                        </div>
                                        <div class="col-md-5">
                                        	<input type="text" class="form-control" id="pais_fue" name="pais_fue"><br/>
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="col-md-2">
                                        	<label for="facturacion_sri" class="control-label">Fact. SRI: </label>
                                        </div>
                                        <div class="col-md-5">
                                        	<input type="text" class="form-control" id="facturacion_sri" name="facturacion_sri" value="NOR" placeholder="NOR" disabled><br/>
                                        </div>
                                    </div>
                                	<div class="col-md-12">
                                        <div class="col-md-2">
                                        <label for="porc_iva" class="control-label">% IVA: </label>
                                        </div>
                                        <div class="col-md-5">
                                        <input type="text" class="form-control" id="porc_iva" name="porc_iva" value='0'><br/>
                                        </div>
                                    </div>  
                            
                            </div><!--END SEGUNDA COLUMNA-->
                            <!--TERCERA COLUMNA-->
                            <div class="col-md-4">
                                  	<div class="col-md-12">
											<div class="col-md-6">
												<label for="estado" class="control-label"> Inactivo:</label>
											</div>
											<div class="col-md-6">
											<label for="co1" class="control-label">	<input type="checkbox" name="estado" id="estado"></label>
											</div>
									</div>
                                    <div class="col-md-12">
                                        <div class="col-md-6">
                                            <label for="incobrable" class="control-label"> Incobrable:</label>
                                        </div>
                                        <div class="col-md-6">
                                        <label for="co1" class="control-label">	<input type="checkbox" name="incobrable" id="incobrable" autocomplete="off"></label>
                                        </div>
                               		</div>
                                    <div class="col-md-12">
											<div class="col-md-6">
												<label for="cliente_especial" class="control-label">Tipo Cliente Especial:</label>
											</div>
											<div class="col-md-6">
											<label for="" class="control-label">	<input type="checkbox" id="cliente_especial" name="cliente_especial"></label>
											</div>
									</div>
                                    <div class="col-md-12">
											<div class="col-md-6">
												<label for="envia_estadocta" class="control-label">Enviar Estado de Cuenta:</label>
											</div>
											<div class="col-md-6">
											<label for="co1" class="control-label">	<input type="checkbox" id="envia_estadocta" name="envia_estadocta"></label></br><br/>
											</div>
									</div>
                                    <div class="col-md-12">
                                        <div class="col-md-5">
                                            <label for="formato_estado_cta" class="control-label">Formato Est. de Cta:</label>
                                        </div>
                                        <div class="col-md-4">
                                           <select  name="formato_estado_cta" class="form-control" id="formato_estado_cta" ></select><br/>
                                        </div>
                                </div> 
                                <div class="col-md-12">
                                    <div class="col-md-6">
                                    <span class="additional-info-wrap"> 
                                        <label class="radio-inline" >   
                                        <input type="radio" name="tipo_envio_estcta" class="S" id="programacion_semana" onclick="tipoProgramacion('S');" value="S" >Dia Semana</label>
                                    </span> 
                                    </div>     
                           	 	</div>
                                <div class="col-md-12">
                                    <div class="col-md-6">
                                    <span class="additional-info-wrap"> 
                                        <label class="radio-inline">   
                                        <input type="radio" name="tipo_envio_estcta" class="C" id="programacion_calendario" onclick="tipoProgramacion('C');" value="C">Dia Calendario</label>
                                        </span> 
                                     </div>     
                            	</div>
                                <div class="col-md-12">
                                    <div class="col-md-6">
                                        <span class="additional-info-wrap"> 
                                            <label class="radio-inline">   
                                            <input type="radio" name="tipo_envio_estcta" class="I" id="programacion_inmediato" onclick="tipoProgramacion('I');" value="I">Inmediato</label></br></br>
                                         </span>
                                     </div> 
                       			 </div>
                                 <div class="col-md-12">
                                    <div class="col-md-12" id="semanal" style="display:none;">
                                        <div class="col-md-12">
                                            <br/><p><label> Programación semanal </label></p>
                                            <div class="col-md-1">
                                                <label> L </label>
                                            </div>
                                            <div class="col-md-1">
                                                <label> M </label>
                                            </div>
                                            <div class="col-md-1">
                                                <label> M </label>
                                            </div>
                                            <div class="col-md-1">
                                                <label> J </label>
                                            </div>
                                            <div class="col-md-1">
                                                <label> V </label>
                                            </div>
                                            <div class="col-md-1">
                                                <label> S </label>
                                            </div>
                                            <div class="col-md-1">
                                                <label> D </label>
                                            </div>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="col-md-1 ">
                                            	<label class="radio-inline" >
                                                <input type="radio" aria-label="..." name="dia_semana" id="L" value="L">
                                                </label>
                                            </div>
                                            <div class="col-md-1">
                                            	<label class="radio-inline" >
                                                <input type="radio" aria-label="..." name="dia_semana" id="M" value="M">
                                                </label>
                                            </div>
                                            <div class="col-md-1">
                                            	<label class="radio-inline">
                                                <input type="radio" aria-label="..." name="dia_semana" id="I" value="I">
                                                </label>
                                            </div>
                                            <div class="col-md-1">
                                            	<label class="radio-inline">
                                                <input type="radio" aria-label="..." name="dia_semana" id="J" value="J">
                                                </label>
                                            </div>
                                            <div class="col-md-1">
                                            	<label class="radio-inline">
                                                <input type="radio" aria-label="..." name="dia_semana" id="V" value="V">
                                                </label>
                                            </div>
                                            <div class="col-md-1">
                                            	<label class="radio-inline">
                                                <input type="radio" aria-label="..." name="dia_semana" id="S" value="S">
                                                </label>
                                            </div>
                                            <div class="col-md-1">
                                            	<label class="radio-inline">
                                                <input type="radio" aria-label="..." name="dia_semana" id="D" value="D">
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12" id="calendario" style="display:none;">
                                		<div class="col-md-12">
                                            <br/><p><label> Programación calendario </label><p>
                                            <div class="col-md-3">
                                                <input type="text" class="form-control" maxlength="2" pattern="[0-9]" name="diacal_fecha1" id="diacal_fecha1"/>
                                            </div>
                                            <div class="col-md-3">
                                                <input type="text" class="form-control" maxlength="2" pattern="[0-9]"  name="diacal_fecha2" id="diacal_fecha2"/>
                                            </div>
                               		 	</div>
                                </div>
                                <div class="col-md-12" id="p_inmediato" style="display:none;">
                                    <div class="col-md-12">
                                        <br/><p><label> Programación inmediato </label><p>
                                        <div class="col-md-12">
                                            <label><input type="checkbox" aria-label="..." name="inmediato" id="inmediato"> Inmediato </label>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                	<div class="col-md-6 ">
                                	</br>
                                	</br>
                                	</div>
                                </div>
                                <div class="col-md-12">
                                    <div class="col-md-6 ">
                                 <a id="btn_grabar_informacion_general" class="btn btn-small btn-success" href="#"><i class="glyphicon glyphicon-plus icon-save"></i> Grabar</a> 
                               		</div>
                                </div> 
                            </div><!--END TERCERA COLUMNA-->
                    	</form>
                    </div>
                </div><!--END TAB INF. GENERAL-->
	                <div role="tabpanel" class="tab-pane fade" id="tab_marcacion"> <!--INICIO TAB MARCACION-->
	                	<div class="row clear" >
		                  	<form  class="form-horizontal" role="form" id="frm_marcacion_listado" name="frm_marcacion_listado">
			                  	 <div class="col-lg-4 table-striped">
		                              <div class="clearfix">
		                                     	<div class=" busqueda-admin-section pull-left separator"><a name="btn_nueva_marcacion" id="btn_nueva_marcacion" class="btn btn-primary btn-xs" ><i class="glyphicon glyphicon-plus"></i> NUEVO</a>
		                                     	</div>
		                                  <div class="busqueda-admin-section pull-left">
												<input name="busqueda_nombre" id="busqueda_nombre" type="text" class="select-class2" placeholder="Nombre" size="20" value="<?php echo($this->criterio_busqueda); ?>" />
		                                        <select  name="busqueda_estado" id="busqueda_estado" class="select-class2">
		                                         <?php echo($this->busqueda_estado); ?>
		                                        </select>
		                                        <a id="btn_consultar_marcacion"  class="btn btn-success btn-xs"><i class="glyphicon glyphicon-search"></i></a>
		                                  </div></br>
		                              </div>
		                              <div class="clearfix">
		                                  <table id="grid_marcacion_listado" class="grid grid-autoheight"></table>
		                                   <div id="pager_marcacion_listado"></div>
		                              </div>
								</div></br>
		                   </form>	
		               </div>
	                </div> <!--END TAB MARCACION-->
	                <div role="tabpanel" class="tab-pane fade" id="tab_agencia_carga"> <!--INICIO TAB AG CARGA-->
	                    
		                  	<form  class="form-horizontal" role="form" id="frm_agenciacarga_listado" name="frm_agenciacarga_listado">
		                  	<table id="tbl_registros" class="">
			                  	 <tr>
			                  	 	<td>
		                              <div class="clearfix">
		                                     	<div class="busqueda-admin-section pull-left separator"><a id="btn_nueva_agencia_carga"  class="btn btn-primary btn-xs" style="display:none;" >
		                                     	<i class="glyphicon glyphicon-plus" style="display:none;"></i> NUEVO</a>
		                                     	</div>
		                                  <div class="pull-lef">
		                                        <select  name="busqueda_estado" id="busqueda_estado" class="select-class2" style="display:none;">
		                                         <?php echo($this->busqueda_estado); ?>
		                                        </select>
		                                        <a id="btn_consultar_agencia_carga"  class="btn btn-success btn-xs" style="display:none;"><i class="glyphicon glyphicon-search" style="display:none;"></i></a>
		                                  </div>
		                              </div>
		                              <div class="clearfix">
		                                  <table id="grid_agenciacarga_listado" class="grid grid-autoheight" ></table>
		                                   <div id="pager_agenciacarga_listado"></div>
		                              </div>
								</td>
								<td >
								 	<center>
										<p><a id="btn_asignar_cliente_agencia_carga"   role="button"   class="btn btn-primary btn-sm">
											ASIGNAR <i class="glyphicon glyphicon-forward"> </i></a>
										</p><br>
										<p><a id="btn_eliminar_cliente_agencia_carga"   role="button"   class="btn btn-primary btn-sm">
											 <i class="glyphicon glyphicon-backward"></i> ELIMINAR</a>
										</p>
									</center>
								</td>
								<td >
								 <div class="clearfix">
		                                  <table id="grid_cliente_agenciacarga_listado" class="grid grid-autoheight" ></table>
		                                   <div id="pager_cliente_agenciacarga_listado"></div>
		                         </div>
		                         </td>
								</tr></br>
							</table>
		                   </form>	
		               
                    </div><!--END TAB AGENCIA CARGA-->
                <div role="tabpanel" class="tab-pane fade" id="tab_usuarios"><!--INICIO TAB USUARIOS-->
                      <div class="row clear" >
		                  	<form  class="form-horizontal" role="form" id="frm_usuario_listado" name="frm_usuario_listado">
			                  	 <div class="col-lg-4 table-striped">
		                              <div class="clearfix">
		                                     	<div class="busqueda-admin-section pull-left separator"><a id="btn_nuevo_usuario"  class="btn btn-primary btn-xs"><i class="glyphicon glyphicon-plus"></i> NUEVO</a>
		                                     	</div>
		                                  <div class="pull-left">
												<input name="busqueda_nombre" id="busqueda_nombre" type="text" class="select-class2" placeholder="Nombre" size="20" value="<?php echo($this->criterio_busqueda); ?>" />
		                                        <select  name="busqueda_estado" id="busqueda_estado" class="select-class2">
		                                         <?php echo($this->busqueda_estado); ?>
		                                        </select>
		                                        <a id="btn_consultar_usuario"  class="btn btn-success btn-xs"><i class="glyphicon glyphicon-search"></i></a>
		                                  </div></br>
		                              </div>
		                              <div class="clearfix">
		                                  <table id="grid_usuario_listado" class="grid"></table>
		                                   <div id="pager_usuario_listado"></div>
		                              </div>
								</div></br>
		                   </form>	
		              </div>
                </div><!--END TAB USUARIOS-->
              </div>
        </div>
      </div>
    </div>
  </div>
</div>
						
		
		 <!--  DIALOG DE NUEVA MARCACION-->

			<div class="modal" id="dialog_nueva_marcacion" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			  <div class="modal-dialog">
			    <div class="modal-content">
			      <div class="modal-header">
			        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
			        <h4 class="modal-title" id="myModalLabel">MARCACION (<span id="dialog_nueva_marcacion_nombre"></span>)</h4>
			      </div>
			      <div class="modal-body clearfix">
			        <div class="clearfix">
               				<br>
		  				<form id="frm_marcacion" name="frm_marcacion">
					    	<table border="0" align="center" cellpadding="0" cellspacing="0" class="clear tablesorter">
				        	      <tr>
				        	        <td><label class="control-label">ID:</label></td>
				        	        <td>
	                                <input id="marcacion_sec" name="marcacion_sec" type="text" class="form-control input-sm" style="width:50px" value="" maxlength="11" max-lenght="11" disabled >
	                               <input type="hidden" name="accion" id="accion" value="" /></td>
			        	          </tr>
				        	      <tr>
				        	        <td>
	                                <input id="cliente_id" name="cliente_id" type="hidden" class="form-control input-sm" style="width:50px" value="" maxlength="5" max-lenght="5" disabled >
	                                <input type="hidden" name="accion" id="accion" value="" /></td>
			        	          </tr>
				        	        <td><label class="control-label">NOMBRE:</label></td>
				        	        <td><input name="nombre" type="text" class="form-control input-sm" id="nombre" style="width:350px" value="" maxlength="60" max-lenght="60" validate="required" validateMessage="Ingrese un nombre" onkeyup="this.value=this.value.toUpperCase()"></td>
			        	          </tr>
			        	          <tr>
				        	        <td><label class="control-label">DIRECCION:</label></td>
				        	        <td><input name="direccion" type="text" class="form-control input-sm" id="direccion" style="width:350px" value="" maxlength="40" max-lenght="40" ></td>
			        	         </tr>
			        	         <tr>
				        	        <td><label class="control-label">PAIS:</label></td>
				        	        <td><select  name="pais_id" class="select-class2" id="pais_id" validate="required" validateMessage="Seleccione Pais"></select></td>
			        	         </tr>
			        	          <tr>
				        	        <td><label class="control-label">CIUDAD:</label></td>
				        	        <td><input name="ciudad" type="text" class="form-control input-sm" id="ciudad" style="width:350px" value="" maxlength="30" max-lenght="30" validate="required" validateMessage="Ingrese una Ciudad" onkeyup="this.value=this.value.toUpperCase()"></td>
			        	         </tr>
			        	         <tr>
				        	        <td><label class="control-label">CONTACTO:</label></td>
				        	        <td><input name="contacto" type="text" class="form-control input-sm" id="contacto" style="width:350px" value="" maxlength="30" max-lenght="30" validate="required" validateMessage="Ingrese un Contacto"></td>
			        	         </tr>
			        	         <tr>
				        	        <td><label class="control-label">TELEFONO:</label></td>
				        	        <td><input name="telefono" type="text" class="form-control input-sm " id="telefono" style="width:350px" value="" maxlength="13" max-lenght="13" ></td>
			        	         </tr>
			        	         <tr>
			        	         <td><label class="control-label">TIPO CAJA:</label></td>
			        	         <td><select id="tipo_caja_default_id" name="tipo_caja_default_id"  class="select-class2" validate="required" validateMessage="Seleccione Tipo Caja"></select></td>
			        	         </tr>
			        	          <tr>
				        	        <td><label class="control-label">ZIP:</label></td>
				        	        <td><input name="zip" type="text" id="zip" class="form-control input-sm" style="width:350px" value="" maxlength="9" max-lenght="9" ></td>
			        	         </tr>
				        	     <tr>
				        	     	<td><label class="control-label">ESTADO:</label></td>
				        	        <td><select  name="estado" class="select-class2" id="estado" ></select></td>
			        	         </tr>	
		        	            <tr>
			        	       		<td><label class="control-label">SINCRONIZADO:</label></td>
			        	        <td>
									<span id="sincronizado_pendiente" class="glyphicon glyphicon-time icon-white" style="color:red; display:none" ></span>
									<span id="sincronizado_ok" class="glyphicon glyphicon-ok icon-white" style="color:green; display:none"></span>
	                                <span id="lbl_fec_sincronizado"></span>
                                </td>
		        	          </tr>        	   
			        	      <tr>
			        	       		<td>&nbsp;</td>
			        	        	<td>&nbsp;</td>
		        	          </tr>
			        	      <tr>
			        	        	<td><label class="control-label">Ingreso:</label></td>
			        	       		<td><b><span id="lbl_usuario_ing"></span></b> - <span id="lbl_fec_ingreso"></span></td>
		        	          </tr>
			        	      <tr>
			        	        	<td><label class="control-label">Modificación:</label></td>
			        	        	<td><b><span id="lbl_usuario_mod"></span></b> - <span id="lbl_fec_modifica"></span></td>
		        	          </tr>
			        	  	</table>
			        	  	<br>
							<center>
							<p><a id="btn_grabar_marcacion"   role="button"   class="btn btn-primary btn-sm"><i class="glyphicon glyphicon-plus"></i> GRABAR</a></p>
							</center>
     						</form>
					     
		        	  <!--   div id="dialog_oferta_formulario"></div -->			
			        </div>
			      </div>
			    </div>
			  </div>
			</div>


			
<!--  DIALOG DE AGENCIA CARGA -->
           
			<div class="modal fade" id="dialog_nueva_agenciacarga" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			  <div class="modal-dialog">
			    <div class="modal-content">
			      <div class="modal-header">
			        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
			        <h4 class="modal-title" id="myModalLabel">AGENCIA DE CARGA (<span id="dialog_nueva_agenciacarga_nombre"></span>)</h4>
			      </div>
			      <div class="modal-body clearfix">
			        <div class="clearfix">
                         <form id="frm_agencia_carga">
			        	 <table border="0" align="center" cellpadding="0" cellspacing="0" class="clear tablesorter">
			        	      <tr>
			        	        <td><label class="control-label">ID:</label></td>
			        	        <td>
                                <input id="agencia_carga_id" name="agencia_carga_id" type="text" class="form-control input-sm" style="width:50px" value="" maxlength="3" max-lenght="3" validate="required" validateMessage="Ingrese un codigo" onkeyup="this.value=this.value.toUpperCase()">
                                <input type="hidden" name="accion" id="accion" value="" /></td>
		        	          </tr>
			        	      <tr>
			        	        <td><label class="control-label">NOMBRE:</label></td>
			        	        <td><input name="nombre" type="text" class="form-control input-sm" id="nombre" style="width:350px" value="" maxlength="30" max-lenght="30" validate="required" validateMessage="Ingrese un nombre" onkeyup="this.value=this.value.toUpperCase()"></td>
		        	          </tr>
			        	      <tr>
			        	        <td><label class="control-label">DIRECCION:</label></td>
			        	        <td><input name="direccion" type="text" class="form-control input-sm" id="direccion" style="width:350px" value="" maxlength="30" max-lenght="30"></td>
		        	          </tr>
			        	      <tr>
			        	        <td><label class="control-label">TELEFONO:</label></td>
			        	        <td><input type="text" name="telefono"  class="form-control input-sm inputdata-number-and-decimal" id="telefono" style="width:350px" value="" maxlength="15" max-lenght="15" ></td>
		        	          </tr>
			        	      <tr>
			        	        <td><label class="control-label">TIPO:</label></td>
			        	        <td><select  name="tipo" class="select-class2" id="tipo" validate="required" validateMessage="Seleccione un Tipo"></select></td>
		        	          </tr>
			        	      <tr>
			        	        <td><label class="control-label">ESTADO:</label></td>
			        	        <td><select  name="estado" class="select-class2" id="estado"></select></td>
		        	          </tr>
			        	      <tr>
			        	        <td>&nbsp;</td>
			        	        <td>&nbsp;</td>
		        	        </tr>
			        	      <tr>
			        	        <td><label class="control-label">SINCRONIZADO:</label></td>
			        	        <td>
 
									<span id="sincronizado_pendiente" class="glyphicon glyphicon-time icon-white" style="color:red; display:none" ></span>
									<span id="sincronizado_ok" class="glyphicon glyphicon-ok icon-white" style="color:green; display:none"></span>
                                    <span id="lbl_fec_sincronizado"></span>
 
                                </td>
		        	          </tr>
			        	      <tr>
			        	        <td><label class="control-label">Ingreso:</label></td>
			        	        <td><b><span id="lbl_usuario_ing"></span></b> - <span id="lbl_fec_ingreso"></span></td>
		        	          </tr>
			        	      <tr>
			        	        <td><label class="control-label">Modificación:</label></td>
			        	        <td><b><span id="lbl_usuario_mod"></span></b> - <span id="lbl_fec_modifica"></span></td>
		        	          </tr>
	        	      </table>
                      <br><center>
						<a id="btn_grabar_agencia_carga" class="btn btn-small btn-success " href="#"><i class="glyphicon glyphicon-plus icon-save"></i> Grabar</a>
     					</center>
                      		</form>
		        	  <!--   div id="dialog_oferta_formulario"></div -->			
			        </div>
			      </div>
			    </div>
			  </div>
			</div>
	

			
   <!--  DIALOG DE USUARIO NUEVO -->
            
			<div class="modal fade" id="dialog_nuevo_usuario" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			  <div class="modal-dialog">
			    <div class="modal-content">
			      <div class="modal-header">
			      <form action="">
			        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
			        <h4 class="modal-title" id="myModalLabel">USUARIO(<span id="dialog_nuevo_usuario_nombre"></span>)</h4>
			      </form>
			      </div>
			      <div class="modal-body clearfix">
			        <div class="clearfix">
                        <form id="frm_nuevo_usuario">
			        	  <table border="0" align="center" cellpadding="0" cellspacing="0" class="tbl_formulario_mantenimiento">
			        	      <tr>
			        	        <td><label class="control-label">ID:</label></td>
			        	        <td>
                                <input id="usuario_id" name="usuario_id" type="text" class="form-control input-sm" style="width:50px" value="" maxlength="3" max-lenght="3" disabled="disabled">
                                <input type="hidden" name="accion" id="accion" value="" /></td>
		        	          </tr>
			        	      <tr>
			        	        <td><label class="control-label">NOMBRE:</label></td>
			        	        <td><input name="nombre" type="text" class="form-control input-sm" id="nombre" style="width:350px" value="" maxlength="50" max-lenght="3" validate="required" validateMessage="Ingrese un Nombre" onkeyup="this.value=this.value.toUpperCase()" ></td>
		        	          </tr>
			        	      <tr>
			        	        <td><label class="control-label">USUARIO:</label></td>
			        	        <td><input name="username" type="text" class="form-control input-sm" id="username" style="width:350px" value="" maxlength="20" validate="required" validateMessage="Ingrese un Usuario" max-lenght="3"></td>
		        	          </tr>
			        	      <tr>
			        	        <td><label class="control-label">CLAVE:</label></td>
			        	        <td><input type="password" name="password"  class="form-control input-sm" id="password" style="width:350px" value="" maxlength="15" ></td>
		        	          </tr>
		        	           <tr>
			        	        <td><label class="control-label">CONFIRMAR CLAVE:</label></td>
			        	        <td><input type="password" name="password2"  class="form-control input-sm" id="password2" style="width:350px" value="" maxlength="15" ></td>
		        	          </tr>
		        	           <tr>
			        	        <td><label class="control-label">CORREO:</label></td>
			        	        <td><input type="email" name="email"  class="form-control input-sm" id="email" style="width:350px" value="" maxlength="50" ></td>
		        	          </tr>
		        	          <tr>
			        	        <td><label class="control-label">INVENTARIO:</label></td>
			        	        <td><select  name="inventario_id" class="form-control" id="inventario_id" validate="required" validateMessage="Inventario Requerido" style="width:250px"></select></td>
		        	         </tr>
		        	         <tr>
			        	        <td><label class="control-label">CALIDAD:</label></td>
			        	        <td><select  name="calidad_id" class="form-control" id="calidad_id" validate="required" validateMessage="Seleccione Calidad" style="width:250px"></select></td>
		        	         </tr>
		        	          <tr>
			        	        <td><label class="control-label">GRUPO DISPO:</label></td>
			        	        <td><select  name="grupo_dispo_cab_id" class="form-control" id="grupo_dispo_cab_id" validate="required" validateMessage="Grupo Requerido" style="width:250px"></select></td>
		        	          </tr>
		        	          <tr>
			        	        <td><label class="control-label">GRUPO PRECIO:</label></td>
			        	        <td><select  name="grupo_precio_cab_id" class="form-control" id="grupo_precio_cab_id" validate="required" validateMessage="Grupo Requerido" style="width:250px"></select></td>
		        	          </tr>
			        	      <tr>
			        	        <td><label class="control-label">ESTADO:</label></td>
			        	        <td><select  name="estado" class="form-control" id="estado" style="width:150px"></select></td>
		        	          </tr>
			        	      <tr>
			        	        <td>&nbsp;</td>
			        	        <td>&nbsp;</td>
		        	        </tr>
			        	      <tr>
			        	        <td><label class="control-label">Ingreso:</label></td>
			        	        <td><b><span id="lbl_usuario_ing"></span></b> - <span id="lbl_fec_ingreso"></span></td>
		        	          </tr>
			        	      <tr>
			        	        <td><label class="control-label">Modificación:</label></td>
			        	        <td><b><span id="lbl_usuario_mod"></span></b> - <span id="lbl_fec_modifica"></span></td>
		        	          </tr>
	        	      </table>
                      <br>
						<center><a id="btn_grabar_usuario" class="btn btn-small btn-success" href="#"><i class="glyphicon glyphicon-plus icon-save"></i> Grabar</a></center>
                      	</form>
		        	  <!--   div id="dialog_oferta_formulario"></div -->			
			        </div>
			      </div>
			    </div>
			  </div>
			</div>
		