

<script type="text/javascript" src="<?php echo($this->basePath('js/module/dispo/parametrizar/parametrizar.js')); ?>"></script>


	<div class="title-admin-section">
		<h1>PARAMETROS</h1>
	</div>
	
	<div class="row">   
		<section class="body-admin-section">    	
	    	<div class="accion-admin-section"> 	
	        	<div class="botonera-admin-section pull-left separator">
	            </div>
	        	<div class="busqueda-admin-section pull-left">	
	            	<div class="form-inline">
	          			<!-- AREA DE BUSQUEDA -->                 
					</div>
	            </div>
			</div>
			<div class="clearfix"></div>
			<div>
				<table id="grid_parametro_listado" class="grid grid-autoheight"></table>
            	<div id="pager_parametro_listado"></div>        	
       		 </div>
		</section>
	</div>

	<!--  DIALOG DE MANTENIMIENTO -->
            
			<div class="modal fade" id="dialog_mantenimiento" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			  <div class="modal-dialog">
			    <div class="modal-content">
			      <div class="modal-header">
			        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
			        <h4 class="modal-title" id="myModalLabel">Parametros (<span id="dialog_mantenimiento_parametros_nombre"></span>)</h4>
			      </div>
			      <div class="modal-body clearfix">
			        <div class="clearfix">
                        <form id="frm_matenimiento" name="frm" method="post" action="#">
			        	  <table border="0" align="center" cellpadding="0" cellspacing="0" class="tbl_formulario_mantenimiento">
			        	      <tr>
			        	        <td><label class="control-label">ID:</label></td>
			        	        <td>
                                <input id="id" name="id" type="text" class="form-control input-sm" style="width:350px" value="" maxlength="20" max-lenght="20">
                                <input type="hidden" name="accion" id="accion" value="" /></td>
		        	          </tr>
			        	      <tr>
			        	        <td><label class="control-label">DESCRIPCION:</label></td>
			        	        <td><span id="descripcion"></span></td>
		        	          </tr>
		        	          <tr>
			        	        <td><label class="control-label">TIPO:</label></td>
			        	        <td><span id="tipo"></span></td>
		        	          </tr>
		        	          <tr>
			        	        <td><label class="control-label" for="valor_texto">VALOR TEXTO:</label></td>
			        		    <td><input name="valor_texto" type="text" class="form-control input-sm" id="valor_texto" style="width:350px" value="" maxlength="30" max-lenght="30" validate="validateLinkConditional" validateLinkConditional="($('#tipo').html()=='Texto')"  validateMessage="Ingrese un valor"></td>
		        	          </tr>	
		        	          <tr>
			        	        <td><label class="control-label" for="valor_numerico">VALOR NUMERICO:</label></td>
			        		    <td><input name="valor_numerico" type="text" class="form-control input-sm" id="valor_numerico" style="width:350px" value="" maxlength="30" max-lenght="30"  validate="validateLinkConditional" validateLinkConditional="($('#tipo').html()=='Numerico')"  validateMessage="Ingrese un valor"></td>
		        	          </tr>	
		        	          <tr>
			        	        <td valign="top"><label class="control-label">OBSERVACION :</label></td>
			        		    <td> <textarea  rows="4" class="form-control" id="observacion" name="observacion"></textarea></td>
		        	          </tr>	
			        	      <tr>
			        	        <td>&nbsp;</td>
			        	        <td>&nbsp;</td>
		        	        </tr>
			        	    <tr>
			        	        <td><label class="control-label">Ingreso:</label></td>
			        	        <td><b><span id="lbl_usuario_ing"></span></b> - <span id="lbl_fec_ingreso"></span></td>
		        	        </tr>
			        	    <tr>
			        	        <td><label class="control-label">Modificación:</label></td>
			        	        <td><b><span id="lbl_usuario_mod"></span></b> - <span id="lbl_fec_modifica"></span></td>
		        	        </tr>
	        	      </table>
                      <br>
						<center>
                        	<button id="btn_grabar" type="button" class="btn btn-small btn-success"><i class="glyphicon glyphicon-plus icon-save" ></i> Grabar</button>
						</center>
				 	</form>
		        	  <!--   div id="dialog_oferta_formulario"></div -->			
			        </div>
			      </div>
			    </div>
			  </div>
			</div>
			
	

	