

<script type="text/javascript" src="<?php echo($this->basePath('js/module/dispo/agenciacarga/agencia-carga.js')); ?>"></script>


<div class="title-admin-section">
	<h1>AGENCIAS DE CARGA</h1>
</div>

<div class="row">
	<section class="body-admin-section">    	
    	<div class="accion-admin-section"> 
    		<form id="frm_nueva_agencia" class="form-horizontal" role="form" name="frm_nueva_agencia">
        	<div class="botonera-admin-section pull-left separator">
            	<a id="btn_nuevo" name="btn_nuevo" class="btn btn-primary btn-xs" href="#" role="button"><i class="glyphicon glyphicon-plus icon-white"></i> Nuevo</a>
            </div>
       	  </form>	
        	<div class="busqueda-admin-section pull-left">	
            	<!--- div class="form-inline" -->
                	
                <form id="frm_busqueda_agencia" action="<?php echo($this->basePath()); ?>/dispo/agenciacarga/mantenimiento" method="post" >
                <div class="input-group" style="display:inline-flex">    
                	<input name="criterio_busqueda" id="criterio_busqueda" type="text" class="form-control input-sm" placeholder="Search" size="20" value="<?php echo($this->criterio_busqueda); ?>" />
                     <div class="input-group">
						<select  name="busqueda_estado" id="busqueda_estado" class="form-control input-sm" style="width:130px">
	    	                <?php echo($this->busqueda_estado); ?>
    	                </select>                                       
                    </div>
 					<span class="input-group-btn">
                    	<button id="btn_consultar"  name="btn_consultar" class="btn btn-sm btn-primary" type="button"><i class="glyphicon glyphicon-search icon-white"></i> Buscar</button>
                    </span> 
                    <span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
                    <span class="input-group">
                    <button id="btn_excel" type="button" class="btn btn-sm btn-primary"> <i class="glyphicon glyphicon-download-alt"></i> Generar Reporte</button>
                    </span>                           
                </div>                
               
                </form>    
			
            </div>
      </div>
        <div class="clearfix"></div>
        <div>
			<table id="grid_agenciacarga_listado" class="grid grid-autoheight"></table>
            <div id="pager_agenciacarga_listado"></div>        	
        </div>
  </section>
</div>

            <!--  DIALOG DE MANTENIMIENTO -->
            <form id="frm">
			<div class="modal fade" id="dialog_mantenimiento"  name="dialog_mantenimiento" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			  <div class="modal-dialog">
			    <div class="modal-content">
			      <div class="modal-header">
			        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
			        <h4 class="modal-title" id="myModalLabel">AGENCIA DE CARGA (<span id="dialog_mantenimiento_agenciacarga_nombre"></span>)</h4>
			      </div>
			      <div class="modal-body clearfix">
			        <div class="clearfix">
                        
			        	  <table border="0" align="center" cellpadding="0" cellspacing="0" class="tbl_formulario_mantenimiento">
			        	      <tr>
			        	        <td><label class="control-label">ID:</label></td>
			        	        <td>
                                <input id="id" name="id" type="text" class="form-control input-sm" style="width:50px" value="" maxlength="3" max-lenght="3" validate="required" validateMessage="Ingrese un codigo">
                                <input type="hidden" name="accion" id="accion" value="" /></td>
		        	          </tr>
			        	      <tr>
			        	        <td><label class="control-label">NOMBRE:</label></td>
			        	        <td><input name="nombre" type="text" class="form-control input-sm" id="nombre" style="width:350px" value="" maxlength="30" max-lenght="3" validate="required" validateMessage="Ingrese un nombre"></td>
		        	          </tr>
			        	      <tr>
			        	        <td><label class="control-label">DIRECCION:</label></td>
			        	        <td><input name="direccion" type="text" class="form-control input-sm" id="direccion" style="width:350px" value="" maxlength="30" max-lenght="3"></td>
		        	          </tr>
			        	      <tr>
			        	        <td><label class="control-label">TELEFONO:</label></td>
			        	        <td><input type="text" name="telefono"  class="form-control input-sm inputdata-number-and-decimal" id="telefono" style="width:350px" value="" maxlength="15" max-lenght="3" ></td>
		        	          </tr>
			        	      <tr>
			        	        <td><label class="control-label">TIPO:</label></td>
			        	        <td><select  name="tipo" class="select-class2" id="tipo" validate="required" validateMessage="Seleccione Tipo"></select></td>
		        	          </tr>
			        	      <tr>
			        	        <td><label class="control-label">ESTADO:</label></td>
			        	        <td><select  name="estado" class="select-class2" id="estado"></select></td>
		        	          </tr>
			        	      <tr>
			        	        <td>&nbsp;</td>
			        	        <td>&nbsp;</td>
		        	        </tr>
			        	      <tr>
			        	        <td><label class="control-label">SINCRONIZADO:</label></td>
			        	        <td>
 
									<span id="sincronizado_pendiente" class="glyphicon glyphicon-time icon-white" style="color:red; display:none" ></span>
									<span id="sincronizado_ok" class="glyphicon glyphicon-ok icon-white" style="color:green; display:none"></span>
                                    <span id="lbl_fec_sincronizado"></span>
 
                                </td>
		        	          </tr>
			        	      <tr>
			        	        <td><label class="control-label">Ingreso:</label></td>
			        	        <td><b><span id="lbl_usuario_ing"></span></b> - <span id="lbl_fec_ingreso"></span></td>
		        	          </tr>
			        	      <tr>
			        	        <td><label class="control-label">Modificación:</label></td>
			        	        <td><b><span id="lbl_usuario_mod"></span></b> - <span id="lbl_fec_modifica"></span></td>
		        	          </tr>
	        	      </table>
                      <br>
						<center><a id="btn_grabar" class="btn btn-small btn-success" href="#"><i class="glyphicon glyphicon-plus icon-save"></i> Grabar</a></center>
     
                      
		        	  <!--   div id="dialog_oferta_formulario"></div -->			
			        </div>
			      </div>
			    </div>
			  </div>
			</div>
			</form>
	