<meta charset="UTF-8">
<script type="text/javascript" src="<?php echo($this->basePath('js/module/dispo/pedido/listado_vendedor.js')); ?>"></script>
<script>
	$(document).ready(function () {
		InputData_TrimAll();			
	});//$(document).ready
</script>

   	<div class="title-admin-section">
        <h1>LISTADO DE PEDIDOS</h1>
    </div>  
    
    <div class="table-container" style="margin-top:5px">
        <div class="row-fluid">
            <form id="frm_buscar" name="frm_buscar" action="#" method="post" class="form-inline">
                
                <div class="form-inline">                                    
                    <div class="form-group">
                        <label for="cliente_nombre">Cliente:</label>
                        <input type="text" class="form-control" id="cliente_nombre" placeholder="Moroni Salazar">
                    </div>
                    <div class="form-group">
                        <label for="fecha_ini">Fecha Ini:</label>
                        <input type="text" class="form-control" id="fecha_ini" placeholder="yyyy-mm-dd">
                    </div>	                    
                    <div class="form-group">
                        <label for="fecha_ini">Fecha Fin:</label>
                        <input type="text" class="form-control" id="fecha_fin" placeholder="yyyy-mm-dd">
                    </div>
                    
					<button id="btn_consultar" type="button" class="btn btn-default">Consultar</button>                    	                    
                </div>
                
                <div class="form-inline">
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" id="desglosar_fincas"> Desglosar Fincas
                        </label>
                    </div>
                </div>                
            </form>
            
            <table id="grid_listado">            
            </table>
        </div>
    </div>
