<style>
	#tbl_sin_stock td{
		text-align:center;	
	}
</style>

<script>
	$(document).ready(function () {
	    $(".bnt_sin_stock_actualizar_nro_cajas").on('click', function(event){ 
	        sin_stock_actualizar_nro_cajas($(this));
			return false;
	    });

	    $(".btn_eliminar_sin_stock_detalle").on('click', function(event){ 
	    	eliminar_sin_stock_detalle($(this));
			return false;
	    });	    
	});//$(document).ready

	

	function sin_stock_actualizar_nro_cajas(obj)
	{
		cargador_visibility('show');		
		var tr 						= obj.closest('tr');
		var id_tr					= tr.attr('id');
		var pedido_cab_id 			= tr.attr('pedido_cab_id');
		var pedido_det_sec			= tr.attr('pedido_det_sec');
		var nro_cajas_en_stock		= $('#'+id_tr+'_cbo_nro_cajas_en_stock').val(); 

		//Se llama mediante AJAX para adicionar al carrito de compras
		var data = 	{	pedido_cab_id: pedido_cab_id,
						pedido_det_sec: pedido_det_sec,
						nro_cajas_en_stock: nro_cajas_en_stock
					}
		data = JSON.stringify(data);
		
		var parameters = {	'type': 'POST',//'POST',
							'contentType': 'application/json',
							'url':'<?php echo($this->basePath()); ?>/dispo/pedido/actualizarnrocajas',
							'control_process':true,
							'show_cargando':false,
							'finish':function(response){
									if (response.respuesta_codex=='OK'){
										//Se debe de actualizar el pedido actual
										cargar_detalle_pedido(0);
										consultarNroItemsPedidoComprando();
										
										//Se elimina la linea de la tabla porque ya se proceso, se evita la recarga por el parpadeo
										$('table#tbl_sin_stock tr#'+id_tr).remove();
										ocultarTablaSinStock();
									}else{
										swal({title: '('+ response.respuesta_codex + ') '+response.respuesta_mensaje,		    											
											type: "error",
											html: false,
											showCancelButton: false,
											confirmButtonColor: "#DD6B55",
											showConfirmButton: true,
											});
									}//end if
									cargador_visibility('hide');
							}							
		                 }
		response = ajax_call(parameters, data);		
		return false;
	}//end function sin_stock_actualizar_nro_cajas


	function eliminar_sin_stock_detalle(obj)
	{
		cargador_visibility('show');		
		var tr 						= obj.closest('tr');
		var id_tr					= tr.attr('id');
		var pedido_cab_id 			= tr.attr('pedido_cab_id');
		var pedido_det_sec			= tr.attr('pedido_det_sec'); 

		//Se llama mediante AJAX para adicionar al carrito de compras
		var data = 	{	pedido_cab_id: pedido_cab_id,
						pedido_det_sec: pedido_det_sec
					}

		var parameters = {	'type': 'POST',//'POST',
							//'contentType': 'application/json',
							'url':'<?php echo($this->basePath()); ?>/dispo/pedido/eliminardetalle',
							'control_process':true,
							'show_cargando':false,
							'finish':function(response){
									if (response.respuesta_code=='OK'){
										//Consulta el detalle de la dispo
										consultarNroItemsPedidoComprando()
										cargar_detalle_pedido(0)
										//Se debe de actualizar el pedido actual

										//Se elimina la linea de la tabla porque ya se proceso, se evita la recarga por el parpadeo
										$('table#tbl_sin_stock tr#'+id_tr).remove();
										ocultarTablaSinStock();
									}else{
										swal({title: '('+ response.respuesta_codex + ') '+response.respuesta_mensaje,		    											
											type: "error",
											html: false,
											showCancelButton: false,
											confirmButtonColor: "#DD6B55",
											showConfirmButton: true,
											});
									}//end if
									cargador_visibility('hide');
							}							
		                 }
		response = ajax_call(parameters, data);		
		return false;
	}//end function btn_eliminar_sin_stock_detalle	


	function ocultarTablaSinStock()
	{
		var nro_tr = $('#tbl_sin_stock tr').length;
		console.log('nro_tr:', nro_tr);
		if (nro_tr == 1)
		{
			$("#detalle_pedido_sin_stock").html("");
		}//end if
	}//end function ocultarTablaSinStock
	
</script>
	<div class="clearfix">
    </div>
    <br><br>
    <div>
		<p class="text-center" style="color:#9C0A0C"><b>CHECK THE FOLLOWING ITEMS...OUT STOCK</b></p>
	</div>
    <div>
        <table class="table-dispo border" id="tbl_sin_stock" align="center">
             <tr>
                 <td class="th-inner"  width="60">ID Item</td>
                 <td class="th-inner"  width="110">Variety</td>
                 <td class="th-inner"  width="50">Length(cm)</td>
                 <td class="th-inner"  width="50">Box Type</td>                                
                 <td class="th-inner"  width="50">Boxes</td>
                 <td class="th-inner"  width="50">Price/Item</td>
                 <td class="th-inner"  width="130">Boxes in Stock</td>
                 <td class="th-inner"  width="60">Ok</td>
                 <td class="th-inner"  width="60">Remove</td>
             </tr>
    <?php 	
            $ind = 0;
            foreach($this->result as $reg) 
            {				
                $cbo_caja = "";
                $selected = "";
                for($i=1; $i<=$reg['nro_cajas_en_stock']; $i++)
                {				
                    if ($i==$reg['nro_cajas_en_stock']){
                        $selected = "selected";
                    }//end if
                    $cbo_caja = $cbo_caja.'<option value="'.$i.'"'.$selected.'>'.$i.'</option>';
                }//end for
                $ind++;
    ?>
                 <tr id="<?php echo($ind); ?>" pedido_cab_id="<?php echo($reg['pedido_cab_id']); ?>" pedido_det_sec="<?php echo($reg['pedido_det_sec']); ?>">
                     <td>                
                        <?php echo($reg['pedido_det_sec']); ?>
                     </td>                         
                     <td align="left">
                        <?php echo($reg['variedad_nombre']); ?>
                     </td>
                     <td>
                        <?php echo($reg['grado_id']); ?>
                     </td>
                     <td>
                        <?php echo($reg['tipo_caja_id']); ?>
                     </td>
                     <td>
                        <?php echo($reg['nro_cajas']); ?>
                     </td>
                     <td>
                        <?php echo($reg['precio']); ?>
                     </td>
                     <td>
                            <?php if (empty($cbo_caja)){ ?>
                                DON'T EXIST BOXES
                            <?php }else{ ?>
                                <select class="form-control select-class" id="<?php echo($ind); ?>_cbo_nro_cajas_en_stock"><?php echo($cbo_caja); ?></select>	             			
                            <?php }//end if ?>
                     </td>
                     <td>
                            <?php if (!empty($cbo_caja)){ ?>
                                 <div class="btn btn-xs btn-success bnt_sin_stock_actualizar_nro_cajas" indice="<?php echo($ind); ?>" style="cursor:pointer">
                                     <span class="glyphicon glyphicon-ok"></span> Ok
                                 </div>
                            <?php }//end if ?>
                     </td>
                     <td>
                         <img class="pointer btn_eliminar_sin_stock_detalle" src="<?php echo($this->basePath()); ?>/images/delete-icon.png" alt="" style="cursor:pointer">
                     </td>
                 </tr>
    <?php 	}//end for each ?>
        </table>
    </div>