<script type="text/javascript" src="<?php echo($this->basePath('js/module/dispo/tipo_caja/popup_tipo_caja.js')); ?>"></script>
	<style>
		#tbl_pedido_actual{
			text-align: center;	
		}
		
		.td_sin_border{
		  border-bottom: 0px solid #ffffff;
		  border-right: 0px solid #ffffff;
		}
		
		<!-- ESTILOS CSS PARA MODAL TYPEBOX-->
		
	</style>

	<script>
		$(document).ready(function () {
			$("#pedido_comentario").val('<?php echo($this->pedido_comentario); ?>');
		});
	
	</script>

    <form class="clear frm_pedido" name="frm_pedido">	

 	  
        <div> 

                <p class="subtitle-section pull-left">
                    <b>Order ID :</b> 
                     <?php echo($this->nro_pedido_formateado); ?>&nbsp;&nbsp;-&nbsp;&nbsp;
                </p>
               <p class="subtitle-section pull-left">
                    <b>Date: </b>
                     <?php echo($this->pedido_fecha); ?>&nbsp;&nbsp;-&nbsp;&nbsp;
                </p>               
                <p class="subtitle-section pull-left">
                    <b>Label / Mark: </b>
                     <?php echo($this->marcacion_nombre); ?>&nbsp;&nbsp;-&nbsp;&nbsp;
                </p>
                <p class="subtitle-section pull-left">
                    <b>Cargo Agency: </b>
                    <span class="agencia_carga_nombre"><?php echo($this->agencia_carga_nombre); ?></span>&nbsp;&nbsp;                      
                    <span data-toggle="modal" data-target="#CambiarAgenciaCarga">                                            
                        <img class="tool pull-right pointer btn_mostrar_dialog_agencia_carga" style="margin-right: 8px; cursor:pointer" title="edit" src="<?php echo($this->basePath()); ?>/images/edit-icon.png" pedido_det_sec="<?php echo(""/*$reg['pedido_det_sec']*/); ?>">                                           
                    </span>                   
                </p>                        
        </div>
       
        <div class="clearfix"></div>

		<div>
						<table class="table-dispo border" id="tbl_pedido_actual" width="90%" align="left">
                            <tr>
                                <td class="th-inner" width="100%">Variety</td>
                                <td class="th-inner"  width="90">Length (cm)</td>
                                <td class="th-inner"  width="90">Unts /Bunch</td>
                                <td class="th-inner"  width="100"><a href="#"  style="color:white; text-decoration:underline" id="popup_tipo_caja" name="popup_tipo_caja">Box Type <i class="glyphicon glyphicon-question-sign" style="color:white; font-size:16px"></i></a></td>
                                <td class="th-inner"  width="100">Bunch /Box</td> 
                                <td class="th-inner"  width="50">Boxes</td>
                                <td class="th-inner"  width="100">Units</td>
                                <td class="th-inner"  width="100">Price</td>
                                <td class="th-inner"  width="100">Total Box</td>
                                <td class="th-inner"  width="100">Total</td>                                                
                                <!-- <td class="th-inner"  width="120">Marcacion</td> -->
                                <td class="th-inner"  width="70">
                                    Mark/PO
                                </td>
                                <td class="th-inner"  width="70">Delete</td>
                            </tr>
        <?php
			$total_pedido = 0; 	
            if ($this->rs_pedido_det)
            {
				$i = 0;
                foreach ($this->rs_pedido_det as $reg)
                {	
					$i++;
					if ($i%2 == 0)
					{
						$color_fondo = '#E0EBF5';  //E0EBF5 //E0F5E6

					}else{
						$color_fondo = '';
					}
					
					$total_pedido = $total_pedido + $reg['total'];
					$total_x_caja = $reg['tallos_x_bunch'] * $reg['cantidad_bunch']/$reg['nro_cajas'] * $reg['precio'];
				
					$html_tallos_x_bunch = '';
					if ($reg['tallos_x_bunch']!=25)
					{
						$html_tallos_x_bunch = '&nbsp;<span class="tallos_buches_no_standar">('.$reg['tallos_x_bunch'].')</span>';
					}//end if		

					$html_marca = '<i class="glyphicon glyphicon-pencil icono" style="color:orange; font-size:16px;"></i>';
					if (!empty($reg['marca']))
					{
						$html_marca = $reg['marca'];
					}//end if	
        ?>
                            <tr class="tr_det_<?php echo($reg['pedido_det_sec']); ?>" oferta="<?php echo($reg['estado_reg_oferta']); ?>" pedido_cab_oferta_id="<?php echo($reg['pedido_cab_oferta_id']); ?>" pedido_det_oferta_sec="<?php echo($reg['pedido_det_oferta_sec']); ?>" variedad_nombre_oferta_vinculada="<?php echo($reg['variedad_nombre_oferta_vinculada']); ?>" pedido_det_sec="<?php echo($reg['pedido_det_sec']); ?>" style="background-color:<?php echo($color_fondo); ?>">    
                                <td align="left">
                                    <span class="variedad_nombre"><?php echo($reg['variedad_nombre']); ?></span><?php echo($html_tallos_x_bunch); ?>
                                    <?php if ($reg['estado_reg_oferta']==1){ ?>
                                        <div class="pull-right btn_oferta" style="margin-right: 10%; color: orange;">
                                                    <span class="glyphicon glyphicon-star pointer"
                                                    aria-hidden="true" data-toggle="modal" data-target="#oferta"></span>
                                        </div>
                                    <?php }//end if ?>
                                    <?php if (!empty($reg['pedido_cab_oferta_id'])){ ?>                                    
										<div class="pull-right btn_oferta" style="margin-right: 10%; color: gray;">
                                                    <span class="glyphicon glyphicon-star pointer"
                                                    aria-hidden="true" data-toggle="modal" data-target="#oferta"></span>
                                        </div>
                                    <?php }//end if ?>
                                </td>
                                <td>
                                    <?php echo($reg['grado_id']); ?>
                                </td>
                                <td>
                                    <?php echo($reg['tallos_x_bunch']); ?>                        
                                </td>
                                <td>
                                    <?php echo($reg['tipo_caja_nombre']); ?>
                                </td>
                                <td>
                                    <?php echo($reg['cantidad_bunch']/$reg['nro_cajas']); ?>
                                </td>
                                <td>
                                    <?php echo($reg['nro_cajas']); ?>
                                </td>
                                <td>
                                    <?php echo($reg['tallos_total']); ?>
                                </td>                                
                                <td>
                                    $ <?php echo($reg['precio']); ?>                        
                                </td>
                                <td align="right" nowrap>$ <?php echo(number_format($total_x_caja, 2)); ?></td>
                                <td nowrap align="right">
                                    $ <?php echo($reg['total']); ?>                        
                                </td>
                                <td>
                                    <a href="#" id="btn_cambiar_marca_<?php echo($reg['pedido_det_sec']); ?>" class="link_mark btn_cambiar_marca"><?php echo($html_marca); ?></a>
                                </td>
                                <td>
                                    <img pedido_det_sec="<?php echo($reg['pedido_det_sec']); ?>" class="btn_eliminar_detalle"  src="<?php echo($this->basePath()); ?>/images/delete-icon.png" alt="" style="cursor:pointer">
                                </td>
                            </tr>
        <?php 	} //end foreach 
            }//end if
        ?>
                            <tr style="border-top: #06A604 solid 2px">
                              <td align="left" style="border:#FFFFFF none 0px">&nbsp;</td>
                              <td style="border:#FFFFFF none 0px">&nbsp;</td>
                              <td style="border:#FFFFFF none 0px">&nbsp;</td>
                              <td style="border:#FFFFFF none 0px">&nbsp;</td>
                              <td style="border:#FFFFFF none 0px">&nbsp;</td>
                              <td style="border:#FFFFFF none 0px">&nbsp;</td>
                              <td style="border:#FFFFFF none 0px">&nbsp;</td>
                              <td style="border:#FFFFFF none 0px">&nbsp;</td>
                              <td style="border:#FFFFFF none 0px">&nbsp;</td>
                              <td style="border:#FFFFFF none 0px" align="right" nowrap><b>$ <?php echo(number_format($total_pedido, 2)); ?></b></td>
                              <td style="border:#FFFFFF none 0px">&nbsp;</td>
                              <td style="border:#FFFFFF none 0px">&nbsp;</td>
                            </tr>
        
                  	</table>        
        </div>
    
    	 <div class="clearfix"></div>

         <div style="margin-top:5px; width:90%">
            <div class="pull-left">
                    <span class="btn btn-default" data-toggle="modal" data-target="#dialog_comentario">Add Comment</span>
            </div>
            
            <div class="pull-right">
        <?php 		if ($this->rs_pedido_det){ ?>        
                        <input id="btn_confirmar" type="button" class="btn btn-success pull-right" value="Confirm your order" />
        <?php 		}//end if ?>   
             </div>
         </div>
       </form>
        


        
	<!-- Modal -->
    <div class="modal fade" id="dialog_marca" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">WRITE YOUR  BOX MARK</h4>
          </div>
          <div class="modal-body">
                <form id="frm_marca" method="post" action="#" class="form-inline" onSubmit="return false;">
                	<input type="hidden" id="control_id" value="" />
                    <input type="hidden" id="pedido_det_sec" value="" />
                    <input type="text" id="pedido_det_marca" class="form-control" placeholder="Mark/PO" style="width:85%" />                        
                    <button id="btn_grabar_marca" type="submit" class="btn btn-primary" data-dismiss="modal">Save</button>
                </form>             
          </div>
        </div>
      </div>
    </div>
     
