<?php echo $this->doctype(); ?>
<html>
<head lang="en">
    <meta>
    <title>AGRINAG - Dispo</title>


    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
    					//->appendStylesheet($this->basePath('js/jquery-ui-1.10.2/css/ui-lightness/jquery-ui.css'))
					    //->appendStylesheet($this->basePath('js/jquery-ui-1.11.4/css/ui-lightness/jquery-ui.css'))
	                    ->appendStylesheet('http://fonts.googleapis.com/css?family=Muli')
                        ->appendStylesheet($this->basePath('css/bootstrap.css'))
						//->appendStylesheet('http://getbootstrap.com/2.3.2/assets/css/bootstrap.css')
                        ->appendStylesheet($this->basePath('css/sweet-alert.css'))
                        ->appendStylesheet($this->basePath('css/main.css'))
                        ->appendStylesheet($this->basePath('css/mycustom.css'))                         
                        ->appendStylesheet($this->basePath('js/custom-alert/custom-alert.css'))   
                        ->appendStylesheet($this->basePath('js/custom-validate/custom-validate.css'))
                        ->appendStylesheet($this->basePath('js/custom-tips/custom-tips.css'))
                        
    ?>                        
    
    <!-- Scripts -->
    <?php echo $this->headScript()
            ->appendFile($this->basePath('js/scripts/jquery-1.11.1.min.js'))
            //->appendFile($this->basePath('js/jquery-ui-1.10.2/jquery-ui-1.10.2.custom.min.js')
            //->appendFile($this->basePath('js/jquery-ui-1.10.2/i18n/jquery.ui.datepicker-es.js')))
    		->appendFile($this->basePath('js/jquery-ui-1.11.4/jquery-ui-1.11.4.custom.min.js'))    
            ->appendFile($this->basePath('js/jquery-ui-1.11.4/i18n/jquery.ui.datepicker-es.js'))         
 //           ->appendFile($this->basePath('js/scripts/angular.min.js'))
 //           ->appendFile($this->basePath('js/scripts/angular-route.min.js'))
 //           ->appendFile($this->basePath('js/scripts/angular-animate.min.js'))
            ->appendFile($this->basePath('js/scripts/bootstrap.min.js'))            
 //           ->appendFile($this->basePath('js/scripts/ui-bootstrap-tpls-0.11.0.min.js'))
 //           ->appendFile($this->basePath('js/scripts/angular-animate.min.js'))
            ->appendFile($this->basePath('js/scripts/sweet-alert.js'))     
            ->appendFile($this->basePath('js/scripts/behaviors.js'))
            
            ->appendFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->appendFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
            ->appendFile($this->basePath('js/custom-system/serializeFormJSON.js'))            
            ->appendFile($this->basePath('js/custom-system/ajax/ajax.js'))
            ->appendFile($this->basePath('js/custom-cargador/custom-cargador.js'))            
            ->appendFile($this->basePath('js/custom-alert/custom-alert.js'))
    		->appendFile($this->basePath('js/jquery.tablesorter/jquery.tablesorter.min.js'))
    		->appendFile($this->basePath('js/jquery.stickytableheaders/jquery.stickytableheaders.min.js'))
    		->appendFile($this->basePath('js/custom-tablesorter/custom-tablesorter.js'))
    		->appendFile($this->basePath('js/custom-alert/custom-alert.js'))
    		->appendFile($this->basePath('js/custom-validate/custom-validate.js'))
    		->appendFile($this->basePath('js/custom-validate/i18n/custom-validate-fecha-es.js'))
    		->appendFile($this->basePath('js/custom-validate/custom-validate-cedula.js'))	
    		->appendFile($this->basePath('js/custom-tips/custom-tips.js'))
			->appendFile($this->basePath('js/custom-system/input_data.js'));
     ?>
    
    
<!--  
  //  <script type="text/javascript" src="javascripts/behaviors.jsxx"></script>
  //  <script type="text/javascript" src="javascripts/services/cart.jsxx"></script>
  // <script type="text/javascript" src="javascripts/main.jsxxx"></script>
  //  <script type="text/javascript" src="javascripts/controllers/homectrl.jsxxx"></script>
  //  <script type="text/javascript" src="javascripts/controllers/orderctrl.jsxxx"></script>
   // <script type="text/javascript" src="javascripts/controllers/ordenesctrl.jsxxx"></script>
-->

<script>
	var btn = $.fn.button.noConflict() // reverts $.fn.button to jqueryui btn
	$.fn.btn = btn // assigns bootstrap button functionality to $.fn.btn
	$(document).ready(function ()
	{
        $("#inicio").on('click', function(event){ 
        	window.location.href = '<?php echo($this->basePath()); ?>/dispo/disponibilidad/seleccionarMarcacionAgencia'
			return false;
        });

		
        $("#opt_order, #msg_nro_items_comprando").on('click', function(event){ 
        	window.location.href = '<?php echo($this->basePath()); ?>/dispo/pedido/consultarpedidoactual'
			return false;
        });
		
		
        $("#opt_list_orders_client").on('click', function(event){ 
        	window.location.href = '<?php echo($this->basePath()); ?>/dispo/pedido/listadocliente'
			return false;
        });
		
	    $(".link_opcion").on('click', function(event){ 
			var url = $(this).attr('url');
        	window.location.href = url;
			return false;
        });	
		
		//Se pone los estilos para que no se sobrepongan al tooltips
		$(".title-section, .dform-control").css("z-index","-1");
		$(".title-section, .dform-control").css("position","relative");
				
		//Se esconde los mensajes
		//$("#tasks_message").show();
		$("#msg_order").hide();			//msg_orden - esto aparecera cuando se haga el ADD para anadir la orden
		consultarNroItemsPedidoComprando();
	});//$(document).ready


	function consultarNroItemsPedidoComprando()
	{
		var data = '';
		var parameters = {	'type': 'POST',//'POST',
							'contentType': 'application/json',
							'url':'<?php echo($this->basePath()); ?>/dispo/pedido/consultarnroitemspedidocomprando',
							'cancel_process_previous':false,
							'show_cargando':false,
							'async': true,
							'finish':function(response){
									if (response.respuesta_code=='OK'){
										//Se muestra el cuadro de informacion que se cargo una orden
										$("#msg_nro_items_comprando").html(response.nro_items_comprando);
									}else{
										message_error('ERROR', response);
									}//end if	
							}							
		                 }
		response = ajax_call(parameters, data);		
		return false;		
	}//end function consultarNroItemsPedidoComprando
		
</script>		
     
</head>
<body class="clearfix">                

                  
    <div class="menu-right" data-spy="affix" data-offset-bottom="0">
        <ul class="esconderx">
            <?php
            if (($this->identidad_usuario['perfil_id'] == \Application\Constants\Perfil::ID_VENTAS)
				||($this->identidad_usuario['perfil_id'] == \Application\Constants\Perfil::ID_ADMIN))
			{ ?>
                <li class="right-menu-item">
                    <span class="pointer" data-toggle="modal" data-target="#dialog_seleccion_cliente">
                        <img class="tool" title="Cliente" src="<?php echo($this->basePath()); ?>/images/side-menu-cliente.png">
                    </span>
                </li>
            <?php 
			}//end if ?>
            <li class="right-menu-item">
                <a href="#/">
                    <img id="inicio" class="tool" title="Home" src="<?php echo($this->basePath()); ?>/images/side-menu-home.png">
                </a>
            </li>
            <li class="right-menu-item"> 
                <div class="animate-show alert message_add arrow_right animate-show" role="alert" id="msg_order" style="display: none;" > <!-- NOTIFICACION -->
                </div>              
                <a href="#/order-resume" >
                    <span class="notification img-circle" id="msg_nro_items_comprando"> <!-- NOTIFICACION -->                       
                    </span>
                    <img class="tool" title="Order" src="<?php echo($this->basePath()); ?>/images/side-menu-item3.png" id="opt_order">
                </a>
            </li>
            <li class="right-menu-item">
                <a href="#/list-ordenes">
                    <img class="tool" title="Orders" src="<?php echo($this->basePath()); ?>/images/side-menu-item6.png" id="opt_list_orders_client">
                </a>
            </li>
            <?php
            if ($this->identidad_usuario['perfil_id'] == \Application\Constants\Perfil::ID_ADMIN)
			{ ?>
                <li class="right-menu-item">
                    <a class="pointer"  data-toggle="modal" data-target="#admin">
                           <img class="tool" title="Admin" src="<?php echo($this->basePath()); ?>/images/side-menu-admin.png">
                   </a>
                </li>
            <?php
			}//end if
			?>
            <li class="right-menu-item">
                <a href="<?php echo($this->basePath()); ?>/seguridad/login/logout">
                    <img class="tool" title="Quit" src="<?php echo($this->basePath()); ?>/images/side-menu-item5.png">
                </a>
            </li>            
        </ul>
    </div>
	<div id="page" class="clearfix">
        <div id="head_fix">
        	<header>
                <a href="#/"><img src="<?php echo($this->basePath()); ?>/images/logo-agrinag-header.png" alt="logo agrinag"></a>

                <div class="pull-right">
                    <div class="user-info flo-left">
                        <div class="icon-user img-circle flo-left">
                            <img src="<?php echo($this->basePath()); ?>/images/user-icon.png">
                        </div>
                        <div class="flo-left">
                            <h2>
<?php 
								if (($this->identidad_usuario['perfil_id']== Application\Constants\Perfil::ID_VENTAS)
									||($this->identidad_usuario['perfil_id']== Application\Constants\Perfil::ID_ADMIN))
								{
									echo($this->identidad_usuario['nombre_usuario'].' <span style="color:yellow">(Vendedor)</span><br>');
								}//end if								
								echo('<div id="identidad_cliente">'.$this->identidad_usuario['cliente_nombre']. ' - '.$this->identidad_usuario['cliente_usuario_nombre'].'</div>');
?>	
                            </h2>
                            <h3 class="flo-left">
<?php 
								echo($this->identidad_usuario['cliente_seleccion_marcacion_nombre']);
?>								
                            </h3>
                        </div>
                        
                    </div>
                    
                    <div class="user-menu flo-left">
                        <span class="glyphicon glyphicon-list"></span>
                    </div>
                </div>                
            </header>           
        </div>

        <div class="content clearfix">
            <section class="col-md-15 col-sm-15">
                <!--  div class="title-section clearfix" -->        
        			<?php echo $this->content; ?>
                <!--  /div  -->
            </section>                    
		</div>
    </div>
    
    
	<div id="dialog-message" title=""></div>  
    
    
    <!-- Modal Admin -->
<div class="modal fade" id="admin" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Menu de Administrador</h4>
      </div>
      <div class="modal-body clearfix">
        <ul class="admin-menu">
            <li>
                <span class="img-circle back1 link_opcion" url="<?php echo($this->basePath()); ?>/dispo/disponibilidad/xxxxxx">
                    <img src="<?php echo($this->basePath()); ?>/images/admin_icons/dispo.png">
                </span>
                <p class="back1">disponibilidad</p>
            </li>
            <li>
                <span class="img-circle back2 link_opcion" url="<?php echo($this->basePath()); ?>/dispo/variedad/mantenimiento">
                    <img src="<?php echo($this->basePath()); ?>/images/admin_icons/variedad.png">
                </span>
                <p class="back2">variedad</p>
            </li>
            <li>
                <span class="img-circle back3 link_opcion" url="<?php echo($this->basePath()); ?>/dispo/agenciacarga/mantenimiento">
                    <img src="<?php echo($this->basePath()); ?>/images/admin_icons/agencia.png">
                </span>
                <p class="back3">agencias de carga</p>
            </li>
        </ul>

        <ul class="admin-menu">
            <li>
                <span class="img-circle back4 link_opcion" url="<?php echo($this->basePath()); ?>/dispo/usuario/mantenimiento">
                    <img src="<?php echo($this->basePath()); ?>/images/admin_icons/usuarios.png">
                </span>
                <p class="back4">usuarios</p>
            </li>
            <li>
                <span class="img-circle back5 link_opcion" url="<?php echo($this->basePath()); ?>/dispo/cliente/mantenimiento">
                    <img src="<?php echo($this->basePath()); ?>/images/admin_icons/clientes.png">
                </span>
                <p class="back5">clientes</p>
            </li>
            <li>
                <span class="img-circle back6 link_opcion" url="<?php echo($this->basePath()); ?>/dispo/grupocliente/mantenimiento">
                    <img src="<?php echo($this->basePath()); ?>/images/admin_icons/grupo_clientes.png">
                </span>
                <p class="back6">grupo de clientes</p>
            </li> 
        </ul>

        <ul class="admin-menu">
            <li>
                <span class="img-circle back7 link_opcion" url="<?php echo($this->basePath()); ?>/dispo/cajamatriz/mantenimiento">
                    <img src="<?php echo($this->basePath()); ?>/images/admin_icons/caja_matriz.png">
                </span>
                <p class="back7">caja matriz</p>
            </li>
            <li>
                <span class="img-circle back8 link_opcion" url="<?php echo($this->basePath()); ?>/dispo/cajamarcacion/mantenimiento">
                    <img src="<?php echo($this->basePath()); ?>/images/admin_icons/caja_marcacion.png">
                </span>
                <p class="back8">caja marcacion</p>
            </li>
        </ul>

      </div>
    </div>
  </div>
</div>
 
</body>
</html>