<?php echo $this->doctype(); ?>
<html>
<head lang="en">
    <meta>
    <title>AGRINAG - Dispo</title>


    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
//NO ES NECESARIO	                    ->appendStylesheet('http://fonts.googleapis.com/css?family=Muli')
	                    ->appendStylesheet($this->basePath('js/jquery-ui-1.11.4/css/ui-lightness/jquery-ui.css'))
	                    ->appendStylesheet($this->basePath('js/jquery-jqGrid-5.0.0/css/ui.jqgrid.css'))	                    
                        // NO VALE ->appendStylesheet($this->basePath('css/bootstrap.css'))
						//->appendStylesheet('http://getbootstrap.com/2.3.2/assets/css/bootstrap.css')
	    				->appendStylesheet($this->basePath('js/bootstrap-3.3.5/css/bootstrap.min.css'))	  			//BOOTSTRAP
    					->appendStylesheet($this->basePath('js/bootstrap-3.3.5/css/bootstrap-theme.min.css'))	  	//BOOTSTRAP OPCIONAL																			
                        ->appendStylesheet($this->basePath('css/sweet-alert.css'))
//                        ->appendStylesheet($this->basePath('css/main.css'))
                        ->appendStylesheet($this->basePath('css/mycustom.css'))                         
                        ->appendStylesheet($this->basePath('js/custom-alert/custom-alert.css'))   
                        ->appendStylesheet($this->basePath('js/custom-validate/custom-validate.css'))
                        ->appendStylesheet($this->basePath('js/custom-tips/custom-tips.css'))
						->appendStylesheet($this->basePath('css/custom-bootstrap.css'))		
						->appendStylesheet($this->basePath('css/layout-pedido.css'))
    ?>                        
    
    <!-- Scripts -->
    <?php echo $this->headScript()
            ->appendFile($this->basePath('js/scripts/jquery-1.11.1.min.js'))
    		->appendFile($this->basePath('js/jquery-ui-1.11.4/jquery-ui-1.11.4.custom.min.js'))    
            ->appendFile($this->basePath('js/jquery-ui-1.11.4/i18n/jquery.ui.datepicker-es.js'))
            ->appendFile($this->basePath('js/jquery-jqGrid-5.0.0/js/i18n/grid.locale-es.js'))
            ->appendFile($this->basePath('js/jquery-jqGrid-5.0.0/js/jquery.jqGrid.min.js'))
 ///           ->appendFile($this->basePath('js/jquery-jqGrid-5.0.0/js/grid.loader.js'))
    		->appendFile($this->basePath('js/bootstrap-3.3.5/js/bootstrap.min.js'))
            ->appendFile($this->basePath('js/scripts/sweet-alert.js'))     
 //           ->appendFile($this->basePath('js/scripts/behaviors.js'))
            
            ->appendFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->appendFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
            ->appendFile($this->basePath('js/custom-system/serializeFormJSON.js'))            
            ->appendFile($this->basePath('js/custom-system/ajax/ajax.js'))
            ->appendFile($this->basePath('js/custom-cargador/custom-cargador.js'))            
            ->appendFile($this->basePath('js/custom-alert/custom-alert.js'))
    		->appendFile($this->basePath('js/jquery.tablesorter/jquery.tablesorter.min.js'))
    		->appendFile($this->basePath('js/jquery.stickytableheaders/jquery.stickytableheaders.min.js'))
    		->appendFile($this->basePath('js/custom-tablesorter/custom-tablesorter.js'))
    		->appendFile($this->basePath('js/custom-alert/custom-alert.js'))
    		->appendFile($this->basePath('js/custom-validate/custom-validate.js'))
    		->appendFile($this->basePath('js/custom-validate/i18n/custom-validate-fecha-es.js'))
    		->appendFile($this->basePath('js/custom-validate/custom-validate-cedula.js'))	
    		->appendFile($this->basePath('js/custom-tips/custom-tips.js'))
			->appendFile($this->basePath('js/custom-system/input_data.js'));
     ?>
    

<script>
	var btn = $.fn.button.noConflict() // reverts $.fn.button to jqueryui btn
	$.fn.btn = btn // assigns bootstrap button functionality to $.fn.btn
	$(document).ready(function ()
	{
        $("#inicio").on('click', function(event){ 
        	window.location.href = '<?php echo($this->basePath()); ?>/dispo/disponibilidad/seleccionarMarcacionAgencia'
			return false;
        });

		
        $("#opt_order, #msg_nro_items_comprando").on('click', function(event){ 
        	window.location.href = '<?php echo($this->basePath()); ?>/dispo/pedido/consultarpedidoactual'
			return false;
        });
		
		
        $("#opt_list_orders_client").on('click', function(event){ 
        	window.location.href = '<?php echo($this->basePath()); ?>/dispo/pedido/listadocliente'
			return false;
        });
		
	    $(".link_opcion").on('click', function(event){ 
			var url = $(this).attr('url');
        	window.location.href = url;
			return false;
        });	
		
		//Se pone los estilos para que no se sobrepongan al tooltips
		$(".title-section, .dform-control").css("z-index","-1");
		$(".title-section, .dform-control").css("position","relative");


		//Se setea configuracion por defecto para el JQGRID
		$.extend($.jgrid.defaults, {
			/*shrinkToFit: true,*/			
			height: 'auto',
			viewrecords: true, 
			rowNum:20,
			rowList:[20,50,100,200],
			altRows: true,
			toppager:true,
			cloneToTop:true,  				
			//loadtext: "Loading...",
			emptyrecords: "No existen registros",
		});

		
		//Se esconde los mensajes
		//$("#tasks_message").show();
		$("#msg_order").hide();			//msg_orden - esto aparecera cuando se haga el ADD para anadir la orden
		consultarNroItemsPedidoComprando();
	});//$(document).ready


	function consultarNroItemsPedidoComprando()
	{
		var data = '';
		var parameters = {	'type': 'POST',//'POST',
							'contentType': 'application/json',
							'url':'<?php echo($this->basePath()); ?>/dispo/pedido/consultarnroitemspedidocomprando',
							'cancel_process_previous':false,
							'show_cargando':false,
							'async': true,
							'finish':function(response){
									if (response.respuesta_code=='OK'){
										//Se muestra el cuadro de informacion que se cargo una orden
										$("#msg_nro_items_comprando").html(response.nro_items_comprando);
									}else{
										message_error('ERROR', response);
									}//end if	
							}							
		                 }
		response = ajax_call(parameters, data);		
		return false;		
	}//end function consultarNroItemsPedidoComprando
		
</script>		

     
</head>
<body>                
	<div class="container-fluid">
        <div id="layout-cabecera" class="row clearfix">
            <div class="pull-left">
	            <a href="#/"><img src="<?php echo($this->basePath()); ?>/images/logo-agrinag-header.png" alt="logo agrinag"></a>
            </div>
			<div class="pull-right col-md-offset-1 col-xs-offset-1">&nbsp;&nbsp;&nbsp;
            </div>              
            <div class="pull-right">  
                 <div class="pull-left">
                    <span class="glyphicon glyphicon-user bootstrap-circle" id="icon-user"></span>
                 </div>
                 <div class="pull-left">
                    <?php 
                    if (($this->identidad_usuario['perfil_id']== Application\Constants\Perfil::ID_VENTAS)
                         ||($this->identidad_usuario['perfil_id']== Application\Constants\Perfil::ID_ADMIN))
                    {
                        echo('<span id="identidad_usuario_administrativo">'.$this->identidad_usuario['nombre_usuario'].' </span><span style="color:yellow">(Vendedor)</span></<br></br>');
                    }//end if								
                    echo('<span id="identidad_cliente">'.$this->identidad_usuario['cliente_nombre']. ' - '.$this->identidad_usuario['cliente_usuario_nombre'].'</span>');
                    ?>	
                    <br>
                    <?php 
                         echo('<span id="seleccion_marcacion_cliente">'.$this->identidad_usuario['cliente_seleccion_marcacion_nombre'].'</span>');
                    ?>	
                 </div>             
            </div>                       
        </div>

        <div class="menu-app" data-spy="affix" data-offset-top="60" data-offset-bottom="0">
        	<div class="pull-right">
                <div class="menu-app-adorno">
                     <span class="glyphicon glyphicon-list"></span>
                </div>
               <div class="menu-app-body">     
					<?php
                    if (($this->identidad_usuario['perfil_id'] == \Application\Constants\Perfil::ID_VENTAS)
                        ||($this->identidad_usuario['perfil_id'] == \Application\Constants\Perfil::ID_ADMIN))
                    { ?>
                        <div class="menu-app-opcion">
                            <span class="pointer" data-toggle="modal" data-target="#dialog_seleccion_cliente">
                                <img class="tool" title="Cliente" src="<?php echo($this->basePath()); ?>/images/side-menu-cliente.png">
                            </span>
                        </div>
                    <?php 
                    }//end if ?>               
					<div class="menu-app-opcion">
                    	<a href="#">
                        	<img id="inicio" class="tool" title="Home" src="<?php echo($this->basePath()); ?>/images/side-menu-home.png">
                    	</a>
                    </div>
					<div class="menu-app-opcion">
                        <div class="animate-show alert message_add arrow_right animate-show" role="alert" id="msg_order" style="display: none;" > <!-- NOTIFICACION -->
                        </div>              
                        <a href="#" >                            
                            <img class="tool" title="Order" src="<?php echo($this->basePath()); ?>/images/side-menu-item3.png" id="opt_order">
							<span class="notification img-circle" id="msg_nro_items_comprando"> <!-- NOTIFICACION -->                       
                            </span>                            
                        </a>
                    </div>  
					<div class="menu-app-opcion">
                        <a href="#/list-ordenes">
                            <img class="tool" title="Orders" src="<?php echo($this->basePath()); ?>/images/side-menu-item6.png" id="opt_list_orders_client">
                        </a>
					</div>                    
					<?php
                    if ($this->identidad_usuario['perfil_id'] == \Application\Constants\Perfil::ID_ADMIN)
                    { ?>
                        <div class="menu-app-opcion">
                            <a class="pointer"  data-toggle="modal" data-target="#admin">
                                   <img class="tool" title="Admin" src="<?php echo($this->basePath()); ?>/images/side-menu-admin.png">
                           </a>
                        </div>
                    <?php
                    }//end if
                    ?>
					
					<div class="menu-app-opcion">
                        <a href="<?php echo($this->basePath()); ?>/seguridad/login/logout">
                            <img class="tool" title="Quit" src="<?php echo($this->basePath()); ?>/images/side-menu-item5.png">
                        </a>      
					</div>
                </div>
            </div>
        </div>
        
        <div class="row">
            <section class="container-fluid">
                    <?php echo $this->content; ?>
            </section>                    
        </div>
 	</div>  <!-- end container -->   
 
    
	<div id="dialog-message" title=""></div>  
    
    
    <!-- Modal Admin -->
<div class="modal fade" id="admin" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Menu de Administrador</h4>
      </div>
      <div class="modal-body clearfix">
      
        	<div class="row">
            	<div class="col-md-4">
                	<div class="link_opcion" url="<?php echo($this->basePath()); ?>/dispo/disponibilidad/panel">
                        <div class="link-icono img-circle back1">
                            <img src="<?php echo($this->basePath()); ?>/images/admin_icons/dispo.png">
                        </div>
                        <div class="clearfix"></div>
                        <div class="link-title back1">DISPONIBILIDAD</div>
                    </div>
                </div>
                
            	<div class="col-md-4">
                	<div class="link_opcion" url="<?php echo($this->basePath()); ?>/dispo/variedad/mantenimiento">
                        <div class="link-icono img-circle back2">
                             <img src="<?php echo($this->basePath()); ?>/images/admin_icons/variedad.png">
                        </div>
                        <div class="clearfix"></div>
                        <div class="link-title back2">VARIEDAD</div>
                    </div>                
                </div>
                
            	<div class="col-md-4">
                	<div class="link_opcion" url="<?php echo($this->basePath()); ?>/dispo/agenciacarga/mantenimiento">
                        <div class="link-icono img-circle back3">
                             <img src="<?php echo($this->basePath()); ?>/images/admin_icons/agencia.png">
                        </div>
                        <div class="clearfix"></div>
                        <div class="link-title back3">AGENCIA DE CARGA</div>
                    </div>                  
               	</div>                                
            </div>
     
        	<div class="row">
				<div class="col-md-4">
                	<div class="link_opcion" url="<?php echo($this->basePath()); ?>/seguridad/usuario/mantenimiento">
                        <div class="link-icono img-circle back4">
                             <img src="<?php echo($this->basePath()); ?>/images/admin_icons/usuarios.png">
                        </div>
                        <div class="clearfix"></div>
                        <div class="link-title back4">USUARIOS</div>
                    </div>                  
               	</div>
 				<div class="col-md-4">
                	<div class="link_opcion" url="<?php echo($this->basePath()); ?>/dispo/cliente/mantenimiento">
                        <div class="link-icono img-circle back5">
                             <img src="<?php echo($this->basePath()); ?>/images/admin_icons/clientes.png">
                        </div>
                        <div class="clearfix"></div>
                        <div class="link-title back5">CLIENTES</div>
                    </div>                  
               	</div>               
 				<div class="col-md-4">
                	<div class="link_opcion" url="<?php echo($this->basePath()); ?>/dispo/grupocliente/mantenimiento">
                        <div class="link-icono img-circle back6">
                             <img src="<?php echo($this->basePath()); ?>/images/admin_icons/clientes.png">
                        </div>
                        <div class="clearfix"></div>
                        <div class="link-title back6">GRUPO DE CLIENTES</div>
                    </div>                  
               	</div>
            </div>     
      
        	<div class="row">
 				<div class="col-md-4">
                	<div class="link_opcion" url="<?php echo($this->basePath()); ?>/dispo/cajamatriz/mantenimiento">
                        <div class="link-icono img-circle back7">
                             <img src="<?php echo($this->basePath()); ?>/images/admin_icons/caja_matriz.png">
                        </div>
                        <div class="clearfix"></div>
                        <div class="link-title back7">CAJA MATRIZ</div>
                    </div>                  
               	</div>
 				<div class="col-md-4">
                	<div class="link_opcion" url="<?php echo($this->basePath()); ?>/dispo/cajamarcacion/mantenimiento">
                        <div class="link-icono img-circle back8">
                             <img src="<?php echo($this->basePath()); ?>/images/admin_icons/caja_matriz.png">
                        </div>
                        <div class="clearfix"></div>
                        <div class="link-title back8">CAJA MARCACION</div>
                    </div>                  
               	</div>
			</div>

      </div>
    </div>
  </div>
</div>
 
</body>
</html>