<meta charset="UTF-8">
<script type="text/javascript" src="<?php echo($this->basePath('js/module/dispo/precio/init.js')); ?>"></script>
<script type="text/javascript" src="<?php echo($this->basePath('js/module/dispo/precio/precio_x_grupo.js')); ?>"></script>
<script type="text/javascript" src="<?php echo($this->basePath('js/module/dispo/precio/grupo_usuario.js')); ?>"></script>
<script>
	$(document).ready(function () {
		
	});//$(document).ready
</script>

   	<div class="title-admin-section">
        <h1>PANEL DE PRECIOS</h1>
    </div>  
    
	<div class="table-container">
	
		  <!-- Nav tabs -->
		  <ul class="nav nav-tabs" role="tablist">
				<li role="presentation" class="active"><a href="#precio_grupo" aria-controls="grupo_dispo" role="tab" data-toggle="tab">PRECIO X GRUPO</a></li>          
			    <li role="presentation"><a href="#grupo_usuario" aria-controls="grupo_precio" role="tab" data-toggle="tab">GRUPO DE USUARIOS</a></li>			    
		  </ul>
		
		  <!-- Tab panes -->
		  <div class="tab-content">
 
         		<!-- TAB MANTENIMIENTO DE PRECIO GRUPO --->
			    <div role="tabpanel" class="tab-pane active" id="precio_grupo">
                
                        	<!--- Grilla principal de la PRECIO X GRUPO --->
                        	<form id="frm_precio_grupo" name="frm_precio_grupo" action="#" method="post" class="form-inline">
                                <div class="form-group">
                                	 <section class="body-admin-section">
                                     	<div class="accion-admin-section">
                                            <div class="botonera-admin-section pull-left separator">
                                                <button id="btn_nuevo_grupo_precio" type="button" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#modal_grupo_precio"><i class="glyphicon glyphicon-plus"></i> NUEVO</button>
                                                <button id="btn_modificar_grupo_precio" type="button" class="btn btn-primary btn-xs"><i class="glyphicon glyphicon-pencil"></i>  MODIFICAR</button>
                                            </div>                                        
                                            <div class="busqueda-admin-section pull-left">
                                            	 <select  id="grupo_precio_cab_id" class="form-control input-sm"></select>
                                                 <select  id="tipo_precio" class="form-control input-sm"></select>
                                                 &nbsp;&nbsp;<span id="info_grupo_precio_cab" class="bg-info"> </span>
                                            </div>
                                        </div>
                                     </section>
                                	 
                                     
                                </div>
                                <table id="grid_precio_grupo" class="grid grid-autoheight"></table>
                                <div id="pager_precio_grupo"></div>
                            </form> 

			    </div>
 
 				<!-- TAB MANTENIMIENTO DE TIPO CAJA MARCACION --->
			    <div role="tabpanel" class="tab-pane" id="grupo_usuario">
			    	  	<form id="frm_grupo_usuario" name="frm_grupo_usuario" action="#" method="post" class="form-inline">
                                <div class="form-group">
                                	 <section class="body-admin-section">
                                     	<div class="accion-admin-section">                                        	
                                            <div class="busqueda-admin-section pull-left">
                                            	 <select  id="grupo_precio_cab_id" class="form-control input-sm"></select>
                                                 <button id="btn_consultar" type="button" class="btn btn-primary btn-xs" style="display: none;"><i class="glyphicon glyphicon-search"></i> BUSCAR</button>&nbsp;&nbsp;<span id="info_grupo_precio_cab" class="bg-info"></span>
                                            </div>
                                        </div>
                                     </section>
                                </div>
                                
                             <div class="clearfix">
                             	<table cellpadding="0" cellspacing="0" border="0">
                                    	<tr>
                                        	<td>
				                             	<table id="grid_grupoprecio_noasignados" class="grid grid-autoheight" ></table>
				                             	<div id="pager_grupoprecio_noasignados"></div>  
				                            </td>
				                            <td>
                                                <p><a id="btn_asignar_grupo"   role="button"   class="btn btn-primary btn-sm">ASIGNAR <i class="glyphicon glyphicon-forward"> </i></a>
                                                </p><br>
                                                <p><a id="btn_eliminar_grupo"   role="button"   class="btn btn-primary btn-sm"><i class="glyphicon glyphicon-backward"></i> QUITAR&nbsp;&nbsp;&nbsp;</a>
                                                </p>

                                            </td>
                                            <td>
                                                <table id="grid_grupoprecio_asignados" class="grid grid-autoheight" ></table>
				                             	<div id="pager_grupoprecio_asignados"></div>                                  
                                            </td>
                                        <tr>
                                </table>
		                     </div>
                             
                           	</form> 			    
			    </div>
                
                
		  </div>
		
	</div>




    <!-- Modal -->
	<div class="modal fade" id="dialog_precio_grupo_mantenimiento" tabindex="-1" role="dialog" aria-labelledby="dialog_precio_grupo_mantenimiento">
		  <div class="modal-dialog" role="document">
			    <div class="modal-content">
				      <div class="modal-header">
					        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					        <h4 class="modal-title" id="myModalLabel"><span id="dialog_precio_grupo_mantenimiento_titulo"></span></h4>
				      </div>
				      <div class="modal-body">
				      		<form class="form-horizontal" name="frm_precio_grupo_mantenimiento" id="frm_precio_grupo_mantenimiento">
					      		<input type="hidden" id="accion" name="accion" value="">
									 <div class="form-group">
									    <label for="id" class="col-sm-2 control-label">ID:</label>
									    <div class="col-sm-4">
	      									<input type="text" class="form-control" id="id" maxlength="5" disabled>
	    								</div>
									 </div>
									 <div class="form-group">
									    <label for="nombre" class="col-sm-2 control-label">NOMBRE:</label>
									    <div class="col-sm-9">
	      									<input type="text" class="form-control" id="nombre" maxlength="50"  validate="required" validateMessage="Ingrese un Nombre">
	    								</div>
									 </div>
									 <div class="form-group">
									    <label for="inventario_id" class="col-sm-2 control-label">INVENTARIO:</label>
									    <div class="col-sm-9">
	      									<select  id="inventario_id"  name="inventario_id" class="form-control" validate="required" validateMessage="Seleccione un inventario"></select>
	    								</div>
									 </div>
									 <div class="form-group">
									    <label for="calidad_id" class="col-sm-2 control-label">CALIDAD:</label>
									    <div class="col-sm-9">
	      									<select  id="calidad_id" name="calidad_id" class="form-control" validate="required" validateMessage="Seleccione la calidad"></select>
	    								</div>
									 </div>
							 </form> 
					      </div>
					      <div class="modal-footer">
					      	<form class="form-horizontal" name="frm_grabar_precio_grupo" id="frm_grabar_precio_grupo">
						        <button type="button" class="btn btn-primary btn-sm " id="btn_grabar_grupo_precio" name="btn_grabar_grupo_precio"><i class="glyphicon glyphicon-plus"></i> GRABAR</button>
						    </form>
					      </div>
				        
			    </div>
		  </div>
	</div>