<meta charset="UTF-8">
<script type="text/javascript" src="<?php echo($this->basePath('js/module/dispo/precio/init.js')); ?>"></script>
<script type="text/javascript" src="<?php echo($this->basePath('js/module/dispo/precio/precio_x_grupo.js')); ?>"></script>
<script type="text/javascript" src="<?php echo($this->basePath('js/module/dispo/precio/grupo_usuario.js')); ?>"></script>
<script>
	$(document).ready(function () {
		
	});//$(document).ready
</script>

   	<div class="title-admin-section">
        <h1>PANEL DE PRECIOS</h1>
    </div>  
    
	<div class="table-container">
	
		  <!-- Nav tabs -->
		  <ul class="nav nav-tabs" role="tablist">
			    <li role="presentation" class="active"><a href="#precio_grupo" aria-controls="grupo_dispo" role="tab" data-toggle="tab">PRECIO X GRUPO</a></li>
			    <li role="presentation"><a href="#grupo_usuario" aria-controls="grupo_precio" role="tab" data-toggle="tab">GRUPO DE USUARIOS</a></li>
		  </ul>
		
		  <!-- Tab panes -->
		  <div class="tab-content">
          
          		<!-- TAB MANTENIMIENTO DE TIPO CAJA MATRIZ --->
			    <div role="tabpanel" class="tab-pane active" id="precio_grupo">
                
                        	<!--- Grilla principal de la PRECIO X GRUPO --->
                        	<form id="frm_precio_grupo" name="frm_precio_grupo" action="#" method="post" class="form-inline">
                                <div class="form-group">
                                	 <section class="body-admin-section">
                                     	<div class="accion-admin-section">
                                        	<div class="botonera-admin-section pull-left separator">
                                        		<button id="btn_nuevo" type="button" class="btn btn-primary btn-xs"><i class="glyphicon glyphicon-plus"></i> NUEVO</button>
                                        	</div>
                                            <div class="busqueda-admin-section pull-left">
                                            	 <select  id="grupo_precio_cab_id" class="form-control input-sm"></select>
                                                 <select  id="tipo_precio" class="form-control input-sm"></select>
                                                 &nbsp;&nbsp;<span id="info_grupo_precio_cab" class="bg-info"> </span>
                                            </div>
                                        </div>
                                     </section>
                                	 
                                     
                                </div>
                                <table id="grid_precio_grupo" class="grid grid-autoheight"></table>
                                <div id="pager_precio_grupo"></div>
                            </form> 

			    </div>


				<!-- TAB MANTENIMIENTO DE TIPO CAJA MARCACION --->
			    <div role="tabpanel" class="tab-pane" id="grupo_usuario">
			    	  	<form id="frm_grupo_usuario" name="frm_grupo_usuario" action="#" method="post" class="form-inline">
                                <div class="form-group">
                                	 <section class="body-admin-section">
                                     	<div class="accion-admin-section">
                                        	<div class="botonera-admin-section pull-left separator">
                                        		<button id="btn_nuevo_grupo_precio" type="button" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#modal_grupo_precio"><i class="glyphicon glyphicon-plus"></i> NUEVO</button>
                                                <button id="btn_modificar_grupo_precio" type="button" class="btn btn-primary btn-xs"><i class="glyphicon glyphicon-pencil"></i>  MODIFICAR</button>
                                        	</div>
                                            <div class="busqueda-admin-section pull-left">
                                            	 <select  id="grupo_precio_cab_id" class="form-control input-sm"></select>
                                                 <button id="btn_consultar" type="button" class="btn btn-primary btn-xs" style="display: none;"><i class="glyphicon glyphicon-search"></i> BUSCAR</button>&nbsp;&nbsp;<span id="info_grupo_precio_cab" class="bg-info"></span>
                                            </div>
                                        </div>
                                     </section>
                                </div>
                                
                             <div class="clearfix">
                             	<table cellpadding="0" cellspacing="0" border="0">
                                    	<tr>
                                        	<td>
				                             	<table id="grid_grupoprecio_noasignados" class="grid grid-autoheight" ></table>
				                             	<div id="pager_grupoprecio_noasignados"></div>  
				                            </td>
				                            <td>
                                                <p><a id="btn_asignar_grupo"   role="button"   class="btn btn-primary btn-sm">ASIGNAR <i class="glyphicon glyphicon-forward"> </i></a>
                                                </p><br>
                                                <p><a id="btn_eliminar_grupo"   role="button"   class="btn btn-primary btn-sm"><i class="glyphicon glyphicon-backward"></i> ELIMINAR</a>
                                                </p>

                                            </td>
                                            <td>
                                                <table id="grid_grupoprecio_asignados" class="grid grid-autoheight" ></table>
				                             	<div id="pager_grupoprecio_asignados"></div>                                  
                                            </td>
                                        <tr>
                                </table>
		                     </div>
                             
                           	</form> 			    
			    </div>
		  </div>
		
	</div>
