<meta charset="UTF-8">


<script>

	$(document).ready(function () {

        $('#filter_text').keyup(function () 
        {
            $("#cbo_filter").val('');
			$('#cbo_color').val('');
            var rex = new RegExp($(this).val(), 'i');
			console.log(rex);
            $('.searchable tr').hide();
            $('.searchable tr').filter(function () {
                return rex.test($.trim($(this).text()));
            }).show();
        })	       
        

        $('#cbo_color').on('change', function(event)
		{       
			$('#filter_text').val('') 			
            $("#cbo_filter").val('');
			
			var texto = $("#cbo_color option:selected").text();
			if (texto=='ALL')
			{				
				var rex = new RegExp('[a-z][A-Z]');		
			}else{
	            var rex = new RegExp(texto, 'i');				
			}//end if
			
            $('.searchable tr').hide();
            $('.searchable tr').filter(function () {
                return rex.test($.trim($(this).text()));
            }).show();
        })	  		
		
		
        $('#cbo_filter').change(function () 
        {
        	$('#filter_text').val('');
			$('#cbo_color').val('');
			
			var texto = $("#cbo_filter option:selected").text();
			
			if (texto=='ALL')
			{				
				var regexp2 = new RegExp('[a-z][A-Z]');		
			}else{
	            var regexp2 = new RegExp('^'+texto, 'i');				
			}//end if			
			//var texto = eval("/^"+$("#cbo_filter option:selected").text()+"/g");
			
			//var regexp2 =  eval("/^"+texto+"/g");  /*new RegExp('^'+texto,'i');*/
			//var regexp2 = new RegExp(texto,'i');
			//console.log('regexp2:',regexp2);
			//console.log('regexp2:',regexp2);
            $('.searchable tr').hide();
            $('.searchable tr').filter(function () {  //.variedad
                return regexp2.test($.trim($(this).text()));
            }).show();
        })


 /*       $(".btn_add_order").on('click', function(event){ 
            add_order($(this));
			return false;
        });
        //btn_add_order
*/

        consultar_detalle_dispo();
	});//$(document).ready



	function consultar_detalle_dispo()
	{
		//	listado_detalle_dispo
		cargador_visibility('show');
		ajax_process_30 = $.ajax({
								url: '<?php echo($this->basePath()); ?>/dispo/disponibilidad/listadodetalledispo',
								type: "GET",
								async: true,
								contentType: "application/json",								
								/*beforeSend : function(){
									if (ajax_process_30) {
										ajax_process_30.abort();
									}
								},*/
							}).done(function(msg) {
								$("#detalle_dispo").html(msg);									
								cargador_visibility('hide');

							}).error(function(request, status, error) {
								console.log('paso99', status, error );
								message_error('ERROR', request.responseText);
								cargador_visibility('hide');
							});	
		return false;		
	}//end function consultar_detalle_dispo
</script>

    <div class="title-section">
        <h1>
             Availability</h1>
    </div>

    <div class="row clearfix"> 
		<div class="col-xd-offset-1 col-md-offset-1 col-lg-offset-1 col-xs-10 col-sm-10 col-md-10 col-lg-10">
            <div class="row container-fluid">
            	<div class="pull-right" style="margin-bottom:5px; line-height:35px">
                
                    <div class="search pull-left">
                        <div class="input-group" style="width:200px">                        
                            <input id="filter_text" type="text" class="form-control" placeholder="Search...">
							<a href="#" class="input-group-addon btn glyphicon glyphicon-search" role="button"></a>
                        </div>                        
                    </div>
        			
                    <div class="pull-left">
                    	&nbsp;&nbsp;&nbsp;Color:&nbsp;
                    </div>
                    <div class="pull-left">
                    	<select id="cbo_color" class="form-control pull-left">
                        	<?php echo($this->cbo_color); ?>
                        </select>
                    </div>
                    
                    <div class="pull-left">
                        &nbsp;&nbsp;&nbsp;Select a Letter:&nbsp;
                    </div>
                    <div class="pull-left">
                        <select id="cbo_filter" class="form-control pull-left">
                            <option value="">ALL</option>
                            <option value="A">A</option>
                            <option value="B">B</option>
                            <option value="C">C</option>
                            <option value="d">D</option>
                            <option value="e">E</option>
                            <option value="F">F</option>
                            <option value="G">G</option>
                            <option value="h">H</option>
                            <option value="i">I</option>
                            <option value="j">J</option>
                            <option value="k">K</option>
                            <option value="l">L</option>
                            <option value="m">M</option>
                            <option value="n">N</option>
                            <option value="o">O</option>
                            <option value="p">P</option>
                            <option value="q">Q</option>
                            <option value="r">R</option>
                            <option value="s">S</option>
                            <option value="t">T</option>
                            <option value="u">U</option>
                            <option value="v">V</option>
                            <option value="w">W</option>
                            <option value="x">X</option>
                            <option value="y">Y</option>
                            <option value="z">Z</option>                            
                         </select> 
                        
                    </div>
                </div>
            </div>
            
            <div class="clearfix"></div>
            
            <div id="detalle_dispo" style="text-align:center"></div>
            <div class="clearfix"></div>

            <div>
                <p>*PRICE PER STEM ($)</p> 
            </div>
            <div class="clearfix"></div>
            <div>
                <a href="<?php echo($this->basePath()); ?>/dispo/pedido/consultarpedidoactual" class="btn btn-primary pull-right"> Check Your Order </a>
            </div>            
        </div>
	</div>
	<br><br><br>



   	 	<!-- DIALOGS -->	
		<?php echo $this->partial('dispo/dialog/seleccioncliente', array(
				'identidad_usuario' 		=> $this->identidad_usuario,
				'opcion_consulta'			=> 'view_seleccionar_marcacion'
		));
		?>	