<meta charset="UTF-8">


<script>

	$(document).ready(function () {

        $('#filter_text').keyup(function () 
        {
            $("#cbo_filter").val('');
            var rex = new RegExp($(this).val(), 'i');
            $('.searchable tr').hide();
            $('.searchable tr').filter(function () {
                return rex.test($(this).text());
            }).show();
        })	       
        
        $('#cbo_filter').change(function () 
        {
        	$('#filter_text').val('');
			var regexp2 = new RegExp('^'+$("#cbo_filter").val(),'i');            
            $('.searchable tr').hide();
            $('.searchable tr .variedad').filter(function () {
                return regexp2.test($.trim($(this).text()));
            }).parent().show();
        })


 /*       $(".btn_add_order").on('click', function(event){ 
            add_order($(this));
			return false;
        });
        //btn_add_order
*/

        consultar_detalle_dispo();
	});//$(document).ready



	function consultar_detalle_dispo()
	{
		//	listado_detalle_dispo
		cargador_visibility('show');
		ajax_process_30 = $.ajax({
								url: '<?php echo($this->basePath()); ?>/dispo/disponibilidad/listadodetalledispo',
								type: "GET",
								async: true,
								contentType: "application/json",								
								/*beforeSend : function(){
									if (ajax_process_30) {
										ajax_process_30.abort();
									}
								},*/
							}).done(function(msg) {
								$("#detalle_dispo").html(msg);									
								cargador_visibility('hide');

							}).error(function(request, status, error) {
								console.log('paso99', status, error );
								message_error('ERROR', request.responseText);
								cargador_visibility('hide');
							});	
		return false;		
	}//end function consultar_detalle_dispo
</script>


        <div class="title-section">
            <h1>
                 Disponibilidad
            </h1>
        </div>

        <div class="pull-right clearfix">
             <div class="search pull-left separator">
                <input id="filter_text" type="text" class="flo-left input-search" placeholder="Search">
                <button class="button-search">
                    <span class="glyphicon glyphicon-search"></span>
                </button>
            </div>

            <p class="pull-left letter" style="padding-top:14px">
                Select a Letter:
            </p>

            <select id="cbo_filter" class="form-control select-class search pull-left select-letter">
                <option value="">ALL</option>
                <option value="A">A</option>
                <option value="B">B</option>
                <option value="C">C</option>
                <option value="d">D</option>
                <option value="e">E</option>
                <option value="F">F</option>
                <option value="G">G</option>
                <option value="h">H</option>
                <option value="i">I</option>
                <option value="j">J</option>
                <option value="k">K</option>
                <option value="l">L</option>
                <option value="m">M</option>
                <option value="n">N</option>
                <option value="o">O</option>
                <option value="p">P</option>
                <option value="q">Q</option>
                <option value="r">R</option>
                <option value="s">S</option>
                <option value="t">T</option>
                <option value="u">U</option>
                <option value="v">V</option>
                <option value="w">W</option>
                <option value="x">X</option>
                <option value="y">Y</option>
                <option value="z">Z</option>                            
             </select> 
        </div>
    </div>


    <div class="clearfix col-md-15 col-sm-15"> 

        <div class="table-container col-md-14 col-md-offset-1 col-sm-14 col-sm-offset-1">                        

			<div id="detalle_dispo"></div>
            

            <div class="clearfix">
                <p>*PRICE PER STEM ($)</p> 
            </div>
            
            <div class="clear">
                <a href="#/order-resume" class="button-class pull-right"> Ver Pedido </a>
            </div>                       

            <!-- </form> -->
        </div>


   	 	<!-- DIALOGS -->	
		<?php echo $this->partial('dispo/dialog/seleccioncliente', array(
				'identidad_usuario' 		=> $this->identidad_usuario,
				'opcion_consulta'			=> 'view_seleccionar_marcacion'
		));
		?>	