<script type="text/javascript" src="<?php echo($this->basePath('js/module/dispo/tipo_caja/popup_tipo_caja.js')); ?>"></script>
<meta charset="UTF-8">


<style>
	#tbl_dispo td{
		text-align:center;	
	}

	#tbl_dispo .btn_add_order{
		width:45px; 
		padding-left:3px; 
		padding-right:3px; 
		margin-left:2px; 
		margin-right:2px;
		font-weight:bold;
		font-size:12px;
		cursor: pointer;
	}	

	#tbl_dispo .cantidad_order{
		 width:60px;
	}

	#tbl_dispo .cbo_tipo_caja_detalle{
		width:inherit;
	}

</style>

<script>
	var ajax_process_dispo_det_cajas = null;

	$(document).ready(function () {
		$("#tbl_dispo").stickyTableHeaders();
		
        $(".btn_add_order").on('click', function(event){ 
            add_order($(this));
			return false;
        });


        $("body").on('click', '.btn_oferta', function(event){
        	mostrar_oferta_dispo($(this));
			return true;
        });

        $("body").on('change', '.cbo_tipo_caja_detalle', function(event){
        	consultar_nro_cajas($(this));
			return true;
        });        
	});//$(document).ready


	function consultar_nro_cajas(obj)
	{		
		var tr 				= obj.closest('tr');
		var id_tr			= tr.attr('id');
		var producto_id		= tr.attr('producto_id');
		var variedad_id 	= tr.attr('variedad_id');
		var grado_id		= tr.attr('grado_id');
		var tallos_x_bunch	= tr.attr('tallos_x_bunch');
		var tipo_caja_id	= $('#'+id_tr+'_tipo_caja_id').val(); 	

		//Se inicializa la cantidad de cajas y el combo de seleccion de cajas
		 $('#'+id_tr+'_cantidad_order').html('');
		 $('#'+id_tr+'_stock').html('loading..');
		 		
		var data = 	{	producto_id: producto_id,
						variedad_id: variedad_id,
						grado_id: grado_id,
						tallos_x_bunch: tallos_x_bunch,
						tipo_caja_id: tipo_caja_id,
					}

		data = JSON.stringify(data);
		var parameters = {	'type': 'POST',//'POST',
							'contentType': 'application/json',
							'url':'<?php echo($this->basePath()); ?>/dispo/disponibilidad/getcajas',
							'control_process':true,
							'show_cargando':false,
							'finish':function(response){
									if (response.respuesta_codex=='OK'){
										//Se muestra el cuadro de informacion que se cargo una orden
										//Se inicializa la cantidad de cajas y el combo de seleccion de cajas
										 $('#'+id_tr+'_cantidad_order').html(response.cbo_nro_caja);
										 $('#'+id_tr+'_stock').html(response.nro_cajas);				
										 if (response.nro_cajas==0)
										 {
											 $('#'+id_tr+'_cantidad_order').hide();
											 $('#'+id_tr+'_add').hide();
										 }else{
											 $('#'+id_tr+'_cantidad_order').show();
											 $('#'+id_tr+'_add').show();
										 }	
									}else{
										swal({title: '('+ response.respuesta_codex + ') '+response.respuesta_mensaje,		    											
											type: "error",
											html: false,
											showCancelButton: false,
											confirmButtonColor: "#DD6B55",
											showConfirmButton: true,
											});
									}//end if
									//console.log('termina add order');
									cargador_visibility('hide');
							}							
		                 }
		response = ajax_call(parameters, data);		
		return false;		
	}//end function consultarDispoPorCaja

	
	function add_order(obj)
	{
		cargador_visibility('show');		
		var tr 				= obj.closest('tr');
		var id_tr			= tr.attr('id');
		var producto_id 	= tr.attr('producto_id');		
		var variedad_id 	= tr.attr('variedad_id');
		var grado_id		= tr.attr('grado_id');
		var tallos_x_bunch	= tr.attr('tallos_x_bunch');
		var tipo_caja_id	= $('#'+id_tr+'_tipo_caja_id').val(); 
		var cantidad_order	= $('#'+id_tr+'_cantidad_order').val();

		//Se llama mediante AJAX para adicionar al carrito de compras
		var data = 	{	producto_id: producto_id,
						variedad_id: variedad_id,
						grado_id: grado_id,
						tallos_x_bunch: tallos_x_bunch,
						tipo_caja_id: tipo_caja_id,
						cantidad_order: cantidad_order
					}
		data = JSON.stringify(data);
		
		//var data = '';
		var parameters = {	'type': 'POST',//'POST',
							'contentType': 'application/json',
							'url':'<?php echo($this->basePath()); ?>/dispo/pedido/additem',
							'control_process':true,
							'show_cargando':false,
							'finish':function(response){
									if (response.respuesta_codex=='OK'){
										//Se muestra el cuadro de informacion que se cargo una orden
										$("#msg_order").show();
										$("#msg_order").html(response.respuesta_mensaje);
										setTimeout(function(){ $("#msg_order").hide(); }, 4000);

										//Consulta el detalle de la dispo
										consultarNroItemsPedidoComprando()
										consultar_detalle_dispo()									
									}else{
										swal({title: '('+ response.respuesta_codex + ') '+response.respuesta_mensaje,		    											
											type: "error",
											html: false,
											showCancelButton: false,
											confirmButtonColor: "#DD6B55",
											showConfirmButton: true,
											});
									}//end if
									//console.log('termina add order');
									cargador_visibility('hide');
							}							
		                 }
		response = ajax_call(parameters, data);		
		return false;		
	}//end function addOrder



	function mostrar_oferta_dispo(obj)
	{
		//cargador_visibility('show');		
		var tr 				= obj.closest('tr');
		var id_tr			= tr.attr('id');
		var producto_id		= tr.attr('producto_id');
		var variedad_id 	= tr.attr('variedad_id');
//		console.log('tr.html:',tr.html(),'*tr:',tr);
		var variedad_nombre = tr.find('.variedad_nombre').html();
		//console.log('variedad_nombre:',variedad_nombre);
		var grado_id		= tr.attr('grado_id');
		var tallos_x_bunch	= tr.attr('tallos_x_bunch');

		$("#dialog_oferta_variedad_nombre").html(variedad_nombre);

		//Se llama mediante AJAX para llamar la oferta que tiene la variedad
		var data = 	{	producto_id: producto_id,
						variedad_id: variedad_id,
						grado_id: grado_id,
						tallos_x_bunch: tallos_x_bunch
						//tipo_caja_id: tipo_caja_id,
						//cantidad_order: cantidad_order
					}
		data = JSON.stringify(data);
		
		//var data = '';
		var parameters = {	'type': 'POST',//'POST',
							'contentType': 'application/json',
							'url':'<?php echo($this->basePath()); ?>/dispo/disponibilidad/consultarofertahtml',
							'control_process':true,
							'show_cargando':false,
							'finish':function(response){
									if (response.respuesta_codex=='OK'){
										//Se muestra el cuadro de informacion que se cargo una orden
										$("#dialog_oferta_formulario").html(response.html);
									}else{
										swal({title: '('+ response.respuesta_codex + ') '+response.respuesta_mensaje,		    											
											type: "error",
											html: false,
											showCancelButton: false,
											confirmButtonColor: "#DD6B55",
											showConfirmButton: true,
											});
									}//end if
									//console.log('termina add order');
									cargador_visibility('hide');
							}							
		                 }
		response = ajax_call(parameters, data);
		//cargador_visibility('hide');
	}//end function 
</script>


                      


                <table id="tbl_dispo" class="clear table-head table-dispo tablesorter tableinit" width="100%">
                	<thead>
                        <tr>
                            <th class="th-inner"  width="300">Description</th>
                            <th class="th-inner"  width="70">Color</th>
                            <th class="th-inner"  width="70">40</th>
                            <th class="th-inner"  width="70">50</th>
                            <th class="th-inner"  width="70">60</th>
                            <th class="th-inner"  width="70">70</th>
                            <th class="th-inner"  width="70">80</th>
                            <th class="th-inner"  width="70">90</th>
                            <th class="th-inner"  width="70">100</th>
                            <th class="th-inner"  width="70">110</th>
                            <th class="th-inner"  width="90"><a href="#" style="color:white; text-decoration:underline" id="popup_tipo_caja" name="popup_tipo_caja">Boxes Type <i class="glyphicon glyphicon-question-sign" style="color:white; font-size:16px"></i></a></th>
                            <th class="th-inner"  width="70">Stock</th>
                            <th class="th-inner" style="min-width:120px; max-width:120px" width="120">Order</th>
                        </tr>
                      </thead>


	            	<tbody class="searchable" style="border: 1px solid #cdcdcd;">
               		
<?php 

	if ($this->result)
	{
		$ind = 0;
		foreach($this->result as $reg)
		{
			$ind ++;
			
			//Se establecen los precios de acuerdo al GRADO del tallo
			$grado_id	= null;
			$precio		= null;
			$precio_40 	= null;
			$precio_50 	= null;
			$precio_60 	= null;
			$precio_70 	= null;
			$precio_80	= null;
			$precio_90 	= null;
			$precio_100 = null;
			$precio_110 = null;
			 switch (trim($reg['grado_id']))
			 {
			 	case '40':
			 		$precio_40 	= $reg['precio'];
			 		$precio		= $reg['precio'];
			 		$grado_id	= 40;
			 		break;
			 	case '50':
			 		$precio_50 	= $reg['precio'];
			 		$precio		= $reg['precio'];
			 		$grado_id	= 50;
			 		break;
			 	case '60':
			 		$precio_60 	= $reg['precio'];
			 		$precio		= $reg['precio'];
			 		$grado_id	= 60;
			 		break;
 				case '70':
			 		$precio_70 	= $reg['precio'];
			 		$precio		= $reg['precio'];
			 		$grado_id	= 70;
 					break;
 				case '80':
			 		$precio_80 	= $reg['precio'];
			 		$precio		= $reg['precio'];
			 		$grado_id	= 80;
 					break;
 				case '90':
			 		$precio_90 	= $reg['precio'];
			 		$precio		= $reg['precio'];
			 		$grado_id	= 90;
 					break;
 				case '100':
			 		$precio_100 = $reg['precio'];
			 		$precio		= $reg['precio'];
			 		$grado_id	= 100;
 					break;
 				case '110':
			 		$precio_110 = $reg['precio'];
			 		$precio		= $reg['precio'];
			 		$grado_id	= 110;
 					break;
			}//end switch
			
			$html_tallos_x_bunch = '';
			if ($reg['tallos_x_bunch']!=25)
			{
				//$html_tallos_x_bunch = '&nbsp;<span class="tallos_buches_no_standar">('.$reg['tallos_x_bunch'].')</span>';
				$html_tallos_x_bunch = '&nbsp;('.$reg['tallos_x_bunch'].')';				
			}//end if
			
			//Se configura el combo de caja
			$options_cbo_caja = '';
			foreach($reg['cajas'] as $caja)
			{
				$seleccionado = '';
				if ($reg['tipo_caja_default_id']==$caja){
					$seleccionado = "selected";
				}//end if
				$options_cbo_caja .='<option value="'.$caja.'" '.$seleccionado.' >'.$this->result_cajas[$caja]['nombre'].'</option>';
			}//end foreach
			
			
			//Se configura del combo de ORDEN
			$options_cbo_order = '';
			$class_row = '';
			for($i=1; $i <= $reg['nro_cajas']; $i++)
			{
				$options_cbo_order .='<option value="'.$i.'">'.$i.'</option>';
			}//end foreach
?>
	                    <tr id="<?php echo($ind); ?>"  producto_id="<?php echo($reg['producto_id']); ?>"  variedad_id="<?php echo($reg['variedad_id']); ?>" grado_id="<?php echo($grado_id); ?>"  tallos_x_bunch="<?php echo($reg['tallos_x_bunch']); ?>"  class="<?php echo($class_row); ?>">
	                        <td>
	                            <span class="variedad_nombre"><?php echo($reg['variedad_nombre']); ?></span><?php echo($html_tallos_x_bunch); ?>

								<?php if (!empty($reg['url_ficha'])){ ?>
		                            <div class="pull-right btn_ficha" style="margin-right: 10%; color: green; cursor:pointer">
                                    	<a onclick="window.open(this.href,this.target,'scrollbars=yes,resizable=yes,height=600,width=1000,left=100,top=100'); return false;" href="<?php echo($reg['url_ficha']); ?>"><span class="glyphicon glyphicon-camera pointer"></span></a>
		                            </div>
	                            <?php }//end if ?>                                

								<?php if (!empty($reg['precio_oferta'])&&($reg['precio_oferta']>0)){ ?>
		                            <div class="pull-right btn_oferta" style="margin-right: 10%; color: orange; cursor:pointer">
		                                <span class="glyphicon glyphicon-star pointer"
		                                aria-hidden="true" data-toggle="modal" data-target="#dialog_oferta"></span>
		                            </div>
	                            <?php }//end if ?>                                
	                        </td>
	                        <td><h5><small><?php echo($reg['color_nombre']); ?><small></h5></td>
	                        <td>
	                            <?php echo($precio_40); ?>                                    
	                        </td>
	                        <td>
	                            <?php echo($precio_50); ?>
	                        </td>
	                        <td>
	                            <?php echo($precio_60); ?>
	                        </td>
	                        <td>
	                            <?php echo($precio_70); ?>
	                        </td>
	                        <td>
	                            <?php echo($precio_80); ?>
	                        </td>
	                        <td>
	                            <?php echo($precio_90); ?>
	                        </td>
	                        <td>
	                            <?php echo($precio_100); ?>
	                        </td>                                
	                        <td>
	                            <?php echo($precio_110); ?>
	                        </td>
	                        <td align="center">
	                            <select class="form-control cbo_tipo_caja_detalle" id="<?php echo($ind); ?>_tipo_caja_id"><?php echo($options_cbo_caja); ?></select>                            
	                        </td>
	                        <td>
	                        	<span id="<?php echo($ind); ?>_stock"><?php echo($reg['nro_cajas']); ?></span>
	                        </td>
	                        <td nowrap >
                            	<div class="pull-right" style="display:block">
                               		<select class="form-control input-sm pull-left cantidad_order" id="<?php echo($ind); ?>_cantidad_order"><?php echo($options_cbo_order); ?></select>
                            
                                    <div id="<?php echo($ind); ?>_add" class="btn_add_order btn-sm btn-success pull-left" indice="<?php echo($ind); ?>">
                                        <span class="glyphicon glyphicon-plus-sign"></span> Add
                                    </div>                            		
                                </div>
 	                        </td>
	                    </tr>
<?php 
		}//end foreach
	}//end if
?>                  	
						</tbody>    
                	</table>
            
            
            <!--  DIALOG DE OFERTA -->
			<div class="modal fade" id="dialog_oferta" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			  <div class="modal-dialog">
			    <div class="modal-content">
			      <div class="modal-header">
			        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
			        <h4 class="modal-title" id="myModalLabel">AGRINAG Offer For:  <span id="dialog_oferta_variedad_nombre"></span></h4>
			      </div>
			      <div class="modal-body clearfix">
			        <div class="clearfix">
						<div id="dialog_oferta_formulario"></div>			
			        </div>
			      </div>
			    </div>
			  </div>
			</div>
            
                        
            
            
<?php 	if ($this->respuesta_dispo_code != 'OK')
	  	{
?>            
			<script>
					swal({title: "<?php echo ('('.$this->respuesta_dispo_code . ') '.$this->respuesta_dispo_msg); ?>",		    											
						type: "error",
						html: false,
						showCancelButton: false,
						confirmButtonColor: "#DD6B55",
						showConfirmButton: true,
						});
			</script>            
<?php 	}//end if ?>