<?php
	//Se configura el combo de caja
	$options_cbo_caja = '';
	//echo('<pre>');var_dump($this->reg_dispo_precio_oferta);
	foreach($this->reg_dispo_precio_oferta['cajas'] as $caja)
	{
		$seleccionado = '';
		if ($this->reg_dispo_precio_oferta['tipo_caja_default_id']==$caja){
			$seleccionado = "selected";
		}//end if		
		$options_cbo_caja .='<option value="'.$caja.'" '.$seleccionado.' >'.$caja.'</option>';
	}//end foreach
	
	
	//Se configura del combo de ORDEN
	$options_cbo_order = '';
	for($i=1; $i <= $reg_dispo_precio_oferta['nro_cajas']; $i++)
	{
		$options_cbo_order .='<option value="'.$i.'">'.$i.'</option>';
	}//end foreach
				
?> 


<script>
	//var ajax_process_dispo_det_cajas = null;

	$(document).ready(function () {
		 $("#oferta_cbo_tipo_caja_id").on('change', function(event){		
        //$("body").on('change', '#oferta_cbo_tipo_caja_id', function(event){
        	oferta_consultar_nro_cajas();
			return true;
         });        


		 $("#oferta_cbo_order").on('change', function(event){
			var producto_id			= $("#oferta_producto_id").val();
			var variedad_id 		= $('#oferta_variedad_id').val();
			var grado_id			= $('#oferta_grado_id').val();
			var tallos_x_bunch		= $("#oferta_tallos_x_bunch").val();
			var tipo_caja_id		= $('#oferta_cbo_tipo_caja_id').val(); 	
			var nro_cajas_oferta 	= $('#oferta_cbo_order').val();

        	consultar_oferta_detalle(producto_id, variedad_id, grado_id, tallos_x_bunch, tipo_caja_id, nro_cajas_oferta);
			return true;
        });        

		
		$("#btn_aplicar_oferta").on('click', function(event){	
			oferta_add_order();
			return false;	
        });        
		
		
		
		//Se carga inicialmente el detalle		
		var producto_id			= $("#oferta_producto_id").val();
		var variedad_id 		= $('#oferta_variedad_id').val();
		var grado_id			= $('#oferta_grado_id').val();
		var tallos_x_bunch		= $("#oferta_tallos_x_bunch").val();
		var tipo_caja_id		= $('#oferta_cbo_tipo_caja_id').val(); 	
		var nro_cajas_oferta 	= $('#oferta_cbo_order').val();
		consultar_oferta_detalle(producto_id, variedad_id, grado_id, tallos_x_bunch, tipo_caja_id, nro_cajas_oferta);
	});//$(document).ready
	
	

	function oferta_consultar_nro_cajas()
	{	
		var producto_id		= $('#oferta_producto_id').val();	
		var variedad_id 	= $('#oferta_variedad_id').val();
		var grado_id		= $('#oferta_grado_id').val();
		var tallos_x_bunch	= $('#oferta_tallos_x_bunch').val();		
		var tipo_caja_id	= $('#oferta_cbo_tipo_caja_id').val(); 	
	
		//Se inicializa la cantidad de cajas y el combo de seleccion de cajas
		 $('#oferta_cbo_order').html('');
		 $('#oferta_stock').html('loading..');
		 		
		//MORONITOR		
		var data = 	{	producto_id: producto_id,
						variedad_id: variedad_id,
						grado_id: grado_id,
						tallos_x_bunch: tallos_x_bunch,
						tipo_caja_id: tipo_caja_id,
					}
	
		data = JSON.stringify(data);
		var parameters = {	'type': 'POST',//'POST',
							'contentType': 'application/json',
							'url':'<?php echo($this->basePath()); ?>/dispo/disponibilidad/getcajas',
							'control_process':true,
							'show_cargando':false,
							'finish':function(response){
									if (response.respuesta_codex=='OK'){
										//Se muestra el cuadro de informacion que se cargo una orden
										//Se inicializa la cantidad de cajas y el combo de seleccion de cajas
										 $('#oferta_cbo_order').html(response.cbo_nro_caja);
										 $('#oferta_stock').html(response.nro_cajas);				
										 if (response.nro_cajas==0)
										 {
											 $('#oferta_cbo_order').hide();
											 //$('#'+id_tr+'_add').hide();
										 }else{
											 $('#oferta_stock').show();
											 //$('#'+id_tr+'_add').show();
										 }
										 var nro_cajas_oferta = $('#oferta_cbo_order').val();
										 consultar_oferta_detalle(producto_id, variedad_id, grado_id, tallos_x_bunch, tipo_caja_id, nro_cajas_oferta);
									}else{
										swal({title: '('+ response.respuesta_codex + ') '+response.respuesta_mensaje,		    											
											type: "error",
											html: false,
											showCancelButton: false,
											confirmButtonColor: "#DD6B55",
											showConfirmButton: true,
											});
									}//end if
									//console.log('termina add order');
									cargador_visibility('hide');
							}							
		                 }
		response = ajax_call(parameters, data);		
		return false;		
	}//end function consultarDispoPorCaja
	
	
	function consultar_oferta_detalle(producto_id, variedad_id, grado_id, tallos_x_bunch, tipo_caja_id, nro_caja)
	{
		var data = 	{	oferta_tipo_caja_id: tipo_caja_id,
						oferta_producto_id: producto_id,
						oferta_variedad_id: variedad_id,
						oferta_grado_id: grado_id,
						oferta_tallos_x_bunch: tallos_x_bunch,
						oferta_nro_caja: nro_caja
					};

		$("#oferta_tbl_hueso").find("tr:gt(0)").remove(); //Borrar todas las filas de la table excepto la primera fila	
		data = JSON.stringify(data);
		var parameters = {	'type': 'POST',//'POST',
							'contentType': 'application/json',
							'url':'<?php echo($this->basePath()); ?>/dispo/disponibilidad/getcajasofertas',
							'control_process':true,
							'show_cargando':false,
							'finish':function(response){
									if (response.respuesta_codex=='OK'){
										///$.each(response.result, function(i, item) {
										if (response.result)
										{
											for (var i = 0; i < response.result.length; i++) {											
												row = response.result[i];
												ind = i + 1;
												row_html		= '<tr id="row_hueso_'+ind+'">'
																  +'<td>'+row.variedad_nombre+'</td>'
																  +'<td>'+row.grado_id+'</td>'
																  +'<td>'+row.precio+'</td>'
																  +'<td>'+row.tipo_caja_id+'</td>'
																  +'<td>'+row.nro_cajas_requeridas+'</td>'
																  +'<td><input type="radio" class="form-control" name="oferta_hueso_seleccion"  value="'+ind+'" data-producto-id="'+row.producto_id+'" data-variedad-id="'+row.variedad_id+'" data-grado-id = "'+row.grado_id+'" data-tallos-x-bunch="'+row.tallos_x_bunch+'" data-tipo-caja-id="'+row.tipo_caja_id+'" data-nro-cajas-requeridas="'+row.nro_cajas_requeridas+'" /></td>'
																  +'</tr>';
												$('#oferta_tbl_hueso tr:last').after(row_html);
											}//end for
										}
									}else{
										swal({title: '('+ response.respuesta_codex + ') '+response.respuesta_mensaje,		    											
											type: "error",
											html: false,
											showCancelButton: false,
											confirmButtonColor: "#DD6B55",
											showConfirmButton: true,
											});
									}//end if
									//console.log('termina add order');
									cargador_visibility('hide');
							}							
		                 }
		response = ajax_call(parameters, data);		
		return false;				
	}//end function
	
	
	function oferta_add_order(obj)
	{
		var radioValue 	=  $("input[name='oferta_hueso_seleccion']:checked").val();
		if (!radioValue){
			alert('Select an Offer');
			return false;
		}//end if

//		cargador_visibility('show');		
		
		var radioHueso 	=  $("input[name='oferta_hueso_seleccion']:checked");
		var hueso_producto_id			= radioHueso.data('producto-id');
		var hueso_variedad_id 			= radioHueso.data('variedad-id');
		var hueso_grado_id 				= radioHueso.data('grado-id');
		var hueso_tallos_x_bunch		= radioHueso.data('tallos-x-bunch');
		var hueso_tipo_caja_id 			= radioHueso.data('tipo-caja-id');
		var hueso_nro_cajas_requeridas	= radioHueso.data('nro-cajas-requeridas');
		
		
		//console.log('hueso_variedad_id:',hueso_variedad_id, '*hueso_grado_id:',hueso_grado_id,'*hueso_tipo_caja_id:',hueso_tipo_caja_id,'*hueso_nro_cajas_requeridas:',hueso_nro_cajas_requeridas);
		
		var oferta_producto_id			= $("#oferta_producto_id").val();
		var oferta_variedad_id			= $("#oferta_variedad_id").val();
		var oferta_grado_id				= $("#oferta_grado_id").val();
		var oferta_tallos_x_bunch		= $("#oferta_tallos_x_bunch").val();
		var oferta_tipo_caja_id			= $("#oferta_cbo_tipo_caja_id").val();
		var oferta_nro_cajas			= $("#oferta_cbo_order").val();
		//console.log('oferta_variedad_id:',oferta_variedad_id,'*oferta_grado_id:',oferta_grado_id,'*oferta_tipo_caja_id:',oferta_tipo_caja_id,'*oferta_nro_cajas:',oferta_nro_cajas);
		
		//Se llama mediante AJAX para adicionar al carrito de compras
		var data = 	{	producto_id:			oferta_producto_id,
						variedad_id: 			oferta_variedad_id,
						grado_id: 				oferta_grado_id,
						tallos_x_bunch:			oferta_tallos_x_bunch,
						tipo_caja_id: 			oferta_tipo_caja_id,
						cantidad_order: 		oferta_nro_cajas,
						hueso_producto_id:		hueso_producto_id,
						hueso_variedad_id: 		hueso_variedad_id,
						hueso_grado_id: 		hueso_grado_id,
						hueso_tallos_x_bunch:	hueso_tallos_x_bunch,
						hueso_tipo_caja_id: 	hueso_tipo_caja_id,
						hueso_cantidad_order: 	hueso_nro_cajas_requeridas,
					}
		data = JSON.stringify(data);
		
		//var data = '';
		var parameters = {	'type': 'POST',//'POST',
							'contentType': 'application/json',
							'url':'<?php echo($this->basePath()); ?>/dispo/pedido/additem',
							'control_process':true,
							'show_cargando':true,
							'finish':function(response){
									if (response.respuesta_codex=='OK'){
										//Se muestra el cuadro de informacion que se cargo una orden
										$('#dialog_oferta').modal('hide')
										
										$("#msg_order").show();
										$("#msg_order").html(response.respuesta_mensaje);
										setTimeout(function(){ $("#msg_order").hide(); }, 4000);

										//Consulta el detalle de la dispo
										consultarNroItemsPedidoComprando()
										consultar_detalle_dispo()
										//cargador_visibility('hide');							
									}else{
										swal({title: '('+ response.respuesta_codex + ') '+response.respuesta_mensaje,		    											
											type: "error",
											html: false,
											showCancelButton: false,
											confirmButtonColor: "#DD6B55",
											showConfirmButton: true,
											});
									}//end if
									//console.log('termina add order');
									cargador_visibility('hide');
							}							
		                 }
		response = ajax_call(parameters, data);		
		return false;		
	}//end function oferta_add_order	
</script>

	<div class="table-container">  
    	 <input type="hidden" id="oferta_producto_id" value="<?php echo($this->reg_dispo_precio_oferta['producto_id']); ?>" />
  		 <input type="hidden" id="oferta_variedad_id" value="<?php echo($this->reg_dispo_precio_oferta['variedad_id']); ?>" />
  		 <input type="hidden" id="oferta_grado_id" value="<?php echo($this->reg_dispo_precio_oferta['grado_id']); ?>" />  
         <input type="hidden" id="oferta_tallos_x_bunch" value="<?php echo($this->reg_dispo_precio_oferta['tallos_x_bunch']); ?>" />       
          <table class="table-dispo border" width="100%">
              <tr>
                  <td class="th-inner"  width="90">Standart Price</td>
                  <td class="th-inner"  width="90">Special Price</td>
                  <td class="th-inner"  width="70">Length</td>
                  <td class="th-inner"  width="80">Type Box</td>
                  <td class="th-inner"  width="60">Stock</td>
                  <td class="th-inner"  width="90">Order</td>                               
              </tr>
         
              <tr>
                  <td width="90">
                     <?php echo($this->reg_dispo_precio_oferta['precio']); ?>                           
                  </td>                                
                  <td width="90">
                      <b><?php echo($this->reg_dispo_precio_oferta['precio_oferta']); ?></b>                               
                  </td>
                  <td width="70">                  	
                      <?php echo($this->reg_dispo_precio_oferta['grado_id']); ?>                           
                  </td>                            
                  <td width="80">
                      <select id="oferta_cbo_tipo_caja_id" class="form-control">
                        	<?php echo($options_cbo_caja); ?>
                      </select>
                  </td>
                  <td width="60">
                       <span id="oferta_stock"><?php echo($this->reg_dispo_precio_oferta['nro_cajas']); ?></span> 
                  </td>
                  <td width="90">
                       <select id="oferta_cbo_order" class="form-control">
                       		<?php echo($options_cbo_order); ?>
                       </select>
                  </td>
              </tr>
          </table>
  	</div>  

  	<div class="space-around pull-left" style="margin-top:10px">
      	Varieties Availability
  	</div>
    
    <div class="clearfix"></div>

  	<div id="oferta_tbl_hueso" class="table-container">  
          <table class="table-dispo border">
              <tr>
                  <td class="th-inner"  width="200">Variety</td>
                  <td class="th-inner"  width="70">Lenght</td>
                  <td class="th-inner"  width="70">Price</td>
                  <td class="th-inner"  width="90">Type Box</td>
                  <td class="th-inner"  width="90">Quantity</td>                               
                  <td class="th-inner" width="150">Order</th>
              </tr>

              <tr>                                
                  <td width="200">
                      variedad_combo_nombre
                  </td>
                  <td width="70">
                      <?php echo($reg['grado_combo_id']); ?>
                  </td>
                   <td width="70">
                      <?php echo($reg['precio_combo']); ?>                                      
                  </td>                            
                  <td width="90">
                      <?php echo($this->reg_dispo_precio_oferta['grado_id']); ?> 
                  </td>
                  <td width="90">
                      
                  </td>
                  <td width="150">
                      <input type="radio" class="form-control" id="hueso_escogido" name="hueso_escogido" />
                  </td>
              </tr>
          </table>
  	</div>

	<div style="margin-top:10px">
        <button type="button" class="btn btn-md btn-success pull-right space-around" id="btn_aplicar_oferta">
          <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> Accept Offer
        </button>    
	</div>