<?php
	//Se configura el combo de caja
	$options_cbo_caja = '';
	foreach($this->reg_dispo_precio_oferta['cajas'] as $caja)
	{
		$options_cbo_caja .='<option value="'.$caja.'">'.$caja.'</option>';
	}//end foreach
	
	
	//Se configura del combo de ORDEN
	$options_cbo_order = '';
	for($i=1; $i <= $reg_dispo_precio_oferta['nro_cajas']; $i++)
	{
		$options_cbo_order .='<option value="'.$i.'">'.$i.'</option>';
	}//end foreach
				
?> 


<script>
	//var ajax_process_dispo_det_cajas = null;

	$(document).ready(function () {
		 $("#oferta_cbo_tipo_caja_id").on('change', function(event){		
        //$("body").on('change', '#oferta_cbo_tipo_caja_id', function(event){
        	oferta_consultar_nro_cajas();
			return true;
        });        

		 $("#oferta_cbo_order").on('change', function(event){
			var variedad_id 		= $('#oferta_variedad_id').val();
			var grado_id			= $('#oferta_grado_id').val();
			var tipo_caja_id		= $('#oferta_cbo_tipo_caja_id').val(); 	
			var nro_cajas_oferta 	= $('#oferta_cbo_order').val();
						 		
        	consultar_oferta_detalle(variedad_id, grado_id, tipo_caja_id, nro_cajas_oferta);
			return true;
        });        

		
		$("#btn_aplicar_oferta").on('click', function(event){	
			oferta_add_order();
			return false;	
        });        
		
		
		
		//Se carga inicialmente el detalle		
		var variedad_id 		= $('#oferta_variedad_id').val();
		var grado_id			= $('#oferta_grado_id').val();
		var tipo_caja_id		= $('#oferta_cbo_tipo_caja_id').val(); 	
		var nro_cajas_oferta 	= $('#oferta_cbo_order').val();
		consultar_oferta_detalle(variedad_id, grado_id, tipo_caja_id, nro_cajas_oferta);
	});//$(document).ready
	
	
	
	
	function oferta_consultar_nro_cajas()
	{		
		var variedad_id 	= $('#oferta_variedad_id').val();
		var grado_id		= $('#oferta_grado_id').val();
		var tipo_caja_id	= $('#oferta_cbo_tipo_caja_id').val(); 	
	
		//Se inicializa la cantidad de cajas y el combo de seleccion de cajas
		 $('#oferta_cbo_order').html('');
		 $('#oferta_stock').html('loading..');
		 		
		var data = 	{	variedad_id: variedad_id,
						grado_id: grado_id,
						tipo_caja_id: tipo_caja_id,
					}
	
		data = JSON.stringify(data);
		var parameters = {	'type': 'POST',//'POST',
							'contentType': 'application/json',
							'url':'<?php echo($this->basePath()); ?>/dispo/disponibilidad/getcajas',
							'control_process':true,
							'show_cargando':false,
							'finish':function(response){
									if (response.respuesta_codex=='OK'){
										//Se muestra el cuadro de informacion que se cargo una orden
										//Se inicializa la cantidad de cajas y el combo de seleccion de cajas
										 $('#oferta_cbo_order').html(response.cbo_nro_caja);
										 $('#oferta_stock').html(response.nro_cajas);				
										 if (response.nro_cajas==0)
										 {
											 $('#oferta_cbo_order').hide();
											 //$('#'+id_tr+'_add').hide();
										 }else{
											 $('#oferta_stock').show();
											 //$('#'+id_tr+'_add').show();
										 }
										 var nro_cajas_oferta = $('#oferta_cbo_order').val();
										 consultar_oferta_detalle(variedad_id, grado_id, tipo_caja_id, nro_cajas_oferta);
									}else{
										swal({title: '('+ response.respuesta_codex + ') '+response.respuesta_mensaje,		    											
											type: "error",
											html: false,
											showCancelButton: false,
											confirmButtonColor: "#DD6B55",
											showConfirmButton: true,
											});
									}//end if
									//console.log('termina add order');
									cargador_visibility('hide');
							}							
		                 }
		response = ajax_call(parameters, data);		
		return false;		
	}//end function consultarDispoPorCaja
	
	
	function consultar_oferta_detalle(variedad_id, grado_id, tipo_caja_id, nro_caja)
	{
		var data = 	{	oferta_tipo_caja_id: tipo_caja_id,
						oferta_variedad_id: variedad_id,
						oferta_grado_id: grado_id,
						oferta_nro_caja: nro_caja
					};

		$("#oferta_tbl_hueso").find("tr:gt(0)").remove(); //Borrar todas las filas de la table excepto la primera fila	
		data = JSON.stringify(data);
		var parameters = {	'type': 'POST',//'POST',
							'contentType': 'application/json',
							'url':'<?php echo($this->basePath()); ?>/dispo/disponibilidad/getcajasofertas',
							'control_process':true,
							'show_cargando':false,
							'finish':function(response){
									if (response.respuesta_codex=='OK'){
										///$.each(response.result, function(i, item) {
										if (response.result)
										{
											for (var i = 0; i < response.result.length; i++) {											
												row = response.result[i];
												ind = i + 1;
												row_html		= '<tr id="row_hueso_'+ind+'" variedad_id="'+row.variedad_id+'" grado_id="'+row.grado_id+'" tipo_caja_id="'+row.tipo_caja_id+'" nro_cajas_requeridas="'+row.nro_cajas_requeridas+'" >'
																  +'<td>'+row.variedad_nombre+'</td>'
																  +'<td>'+row.grado_id+'</td>'
																  +'<td>'+row.precio+'</td>'
																  +'<td>'+row.tipo_caja_id+'</td>'
																  +'<td>'+row.nro_cajas_requeridas+'</td>'
																  +'<td><input type="radio" class="form-control" name="oferta_hueso_seleccion"  value="'+ind+'" /></td>'
																  +'</tr>';
												$('#oferta_tbl_hueso tr:last').after(row_html);
											}//end for
										}
									}else{
										swal({title: '('+ response.respuesta_codex + ') '+response.respuesta_mensaje,		    											
											type: "error",
											html: false,
											showCancelButton: false,
											confirmButtonColor: "#DD6B55",
											showConfirmButton: true,
											});
									}//end if
									//console.log('termina add order');
									cargador_visibility('hide');
							}							
		                 }
		response = ajax_call(parameters, data);		
		return false;				
	}//end function
	
	
	function oferta_add_order(obj)
	{
		var radioValue 	=  $("input[name='oferta_hueso_seleccion']:checked").val();
		if (!radioValue){
			alert('seleccione una oferta');
			return false;
		}//end if

//		cargador_visibility('show');		

		console.log('valor:',radioValue);
		
		var tr 						= $('#row_hueso_'+radioValue);
		var hueso_variedad_id 			= tr.attr('variedad_id');
		var hueso_grado_id 				= tr.attr('grado_id');
		var hueso_tipo_caja_id 			= tr.attr('tipo_caja_id');		
		var hueso_nro_cajas_requeridas	= tr.attr('nro_cajas_requeridas');
		
		console.log('hueso_variedad_id:',hueso_variedad_id, '*hueso_grado_id:',hueso_grado_id,'*hueso_tipo_caja_id:',hueso_tipo_caja_id,'*hueso_nro_cajas_requeridas:',hueso_nro_cajas_requeridas);
		
		var oferta_variedad_id			= $("#oferta_variedad_id").val();
		var oferta_grado_id				= $("#oferta_grado_id").val();
		var oferta_tipo_caja_id			= $("#oferta_cbo_tipo_caja_id").val();
		var oferta_nro_cajas			= $("#oferta_cbo_order").val();
		console.log('oferta_variedad_id:',oferta_variedad_id,'*oferta_grado_id:',oferta_grado_id,'*oferta_tipo_caja_id:',oferta_tipo_caja_id,'*oferta_nro_cajas:',oferta_nro_cajas);
		
		//Se llama mediante AJAX para adicionar al carrito de compras
		var data = 	{	variedad_id: 			oferta_variedad_id,
						grado_id: 				oferta_grado_id,
						tipo_caja_id: 			oferta_tipo_caja_id,
						cantidad_order: 		oferta_nro_cajas,
						hueso_variedad_id: 		hueso_variedad_id,
						hueso_grado_id: 		hueso_grado_id,
						hueso_tipo_caja_id: 	hueso_tipo_caja_id,
						hueso_cantidad_order: 	hueso_nro_cajas_requeridas,						
					}
		data = JSON.stringify(data);
		
		//var data = '';
		var parameters = {	'type': 'POST',//'POST',
							'contentType': 'application/json',
							'url':'<?php echo($this->basePath()); ?>/dispo/pedido/additem',
							'control_process':true,
							'show_cargando':true,
							'finish':function(response){
									if (response.respuesta_codex=='OK'){
										//Se muestra el cuadro de informacion que se cargo una orden
										$('#dialog_oferta').modal('hide')
										
										$("#msg_order").show();
										$("#msg_order").html(response.respuesta_mensaje);
										setTimeout(function(){ $("#msg_order").hide(); }, 4000);

										//Consulta el detalle de la dispo
										consultarNroItemsPedidoComprando()
										consultar_detalle_dispo()
										//cargador_visibility('hide');							
									}else{
										swal({title: '('+ response.respuesta_codex + ') '+response.respuesta_mensaje,		    											
											type: "error",
											html: false,
											showCancelButton: false,
											confirmButtonColor: "#DD6B55",
											showConfirmButton: true,
											});
									}//end if
									//console.log('termina add order');
									cargador_visibility('hide');
							}							
		                 }
		response = ajax_call(parameters, data);		
		return false;		
	}//end function oferta_add_order	
</script>

	<div class="table-container">  
  		 <input type="hidden" id="oferta_variedad_id" value="<?php echo($this->reg_dispo_precio_oferta['variedad_id']); ?> " />
  		 <input type="hidden" id="oferta_grado_id" value="<?php echo($this->reg_dispo_precio_oferta['grado_id']); ?> " />         
          <table class="table-dispo border">
              <tr>
                  <td class="th-inner"  width="90">Precio Normal</td>
                  <td class="th-inner"  width="90">Precio Oferta</td>
                  <td class="th-inner"  width="70">Grado</td>
                  <td class="th-inner"  width="80">type box</td>
                  <td class="th-inner"  width="60">Cantidad</td>
                  <td class="th-inner"  width="90">Order</td>                               
              </tr>
         
              <tr>
                  <td width="90">
                     <?php echo($this->reg_dispo_precio_oferta['precio']); ?>                           
                  </td>                                
                  <td width="90">
                      <b><?php echo($this->reg_dispo_precio_oferta['precio_oferta']); ?></b>                               
                  </td>
                  <td width="70">                  	
                      <?php echo($this->reg_dispo_precio_oferta['grado_id']); ?>                           
                  </td>                            
                  <td width="80">
                      <select id="oferta_cbo_tipo_caja_id" class="form-control select-class">
                        	<?php echo($options_cbo_caja); ?>
                      </select>
                  </td>
                  <td width="60">
                       <span id="oferta_stock"><?php echo($this->reg_dispo_precio_oferta['nro_cajas']); ?></span> 
                  </td>
                  <td width="90">
                       <select id="oferta_cbo_order" class="form-control select-class">
                       		<?php echo($options_cbo_order); ?>
                       </select>
                  </td>
              </tr>
          </table>
  	</div>  

  	<div class="space-around">
      	Variedades para Seleccionar
  	</div>

  	<div id="oferta_tbl_hueso" class="table-container">  
          <table class="table-dispo border">
              <tr>
                  <td class="th-inner"  width="200">Variedad</td>
                  <td class="th-inner"  width="70">Grado</td>
                  <td class="th-inner"  width="70">Precio</td>
                  <td class="th-inner"  width="90">type box</td>
                  <td class="th-inner"  width="90">Cantidad</td>                               
                  <td class="th-inner" width="150">order</th>
              </tr>

              <tr>                                
                  <td width="200">
                      variedad_combo_nombre
                  </td>
                  <td width="70">
                      <?php echo($reg['grado_combo_id']); ?>
                  </td>
                   <td width="70">
                      <?php echo($reg['precio_combo']); ?>                                      
                  </td>                            
                  <td width="90">
                      <?php echo($this->reg_dispo_precio_oferta['grado_id']); ?> 
                  </td>
                  <td width="90">
                      {{ctrl.get_cantidad_x_factor(oferta.factor_combo,ctrl.item_oferta.listindex)}}
                  </td>
                  <td width="150">
                      <input type="radio" class="form-control" id="hueso_escogido" name="hueso_escogido" />
                  </td>
              </tr>
          </table>
  	</div>

    <button type="button" class="btn btn-xs btn-success pull-right space-around" id="btn_aplicar_oferta">
      <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> Aplicar OFERTA
    </button>    
