<meta charset="UTF-8">
	<style type="text/css">
		/*#frm_dispo_grupo_stockgrado .form-group {
			text-align: right;
		}	*/
	</style>

	<script type="text/javascript" src="<?php echo($this->basePath('js/module/dispo/disponibilidad/disponibilidad.js')); ?>"></script>
   	<script type="text/javascript" src="<?php echo($this->basePath('js/module/dispo/disponibilidad/dispo_x_grupo.js')); ?>"></script>
   	<script type="text/javascript" src="<?php echo($this->basePath('js/module/dispo/disponibilidad/grupo_usuario.js')); ?>"></script>    

	<script>
		$(document).ready(function () {
			InputData_TrimAll();
			InputData_initNumberNoDecimal();
			InputData_initNumberAndDecimal();

			//$("#tbl_proveedor").stickyTableHeaders();
			$('#tbl_proveedor').tablesorter(); //Columna de Sueldo
			$("#tbl_proveedor").stickyTableHeaders();

			$(".btn_refrescar").on('click', function(event){ 
				var proveedor 		= $(this).data('proveedor');
				consultarDispoRemote(proveedor);
				return false;
			});			

			$(".btn_sincronizar_general, .btn_sincronizar").on('click', function(event){ 
				var proveedor 		= $(this).data('proveedor');
				sincronizarDispoRemote(proveedor);
				return false;
			});			

			$('#tabs_disponibilidad a').click(function (e) {
				e.preventDefault()
				$(this).tab('show')
			})
			
			$("#frm_dispo_grupo #btn_excel").on('click', function(event){ 
	        	DispoGrupo_ExportarExcel();
	    		return false;
	    	});	
		});//$(document).ready
		
		
		function consultarDispoRemote(proveedor)		
		{
			limpiarSincronizar(proveedor, false);
			if (proveedor=='ALL')
			{
				var data = 	{agr_connect: 1, htc_connect: 1, lma_connect:1}
			}else{
				switch (proveedor)
				{
					case 'AGR':
						var data = 	{agr_connect: 1}
						break;
					case 'HTC':
						var data = 	{htc_connect: 1}
						break;
					case 'LMA':
						var data = 	{lma_connect: 1}
						break;
				}//end switch
			}//end if
			data = JSON.stringify(data);
			var parameters = {	'type': 'POST',//'POST',
								'contentType': 'application/json',
								'url':'<?php echo($this->basePath()); ?>/dispo/disponibilidad/remotesincronizarpreview',
								'control_process':true,
								'show_cargando':true,
								'async':true,
								'finish':function(response){
									if (response.respuesta_codex=="OK")
									{
									  // $(".btn_sincronizar").removeClass("disabled");
									   $.each(response.result, function(key, reg) {
											var tr 			= $("#"+reg.Proveedor.toUpperCase());
											var fec_finca 	= tr.find('.fec_finca');
											var nro_reg		= tr.find('.nro_reg');
											fec_finca.html(reg.fecha);
											nro_reg.html(reg.nro_reg);
										});	
										 $.each(response.connect, function(key, reg) {
											var tr 				= $("#"+key.toUpperCase());
											var observacion 	= tr.find('.observacion');
											var btn_refrescar	= tr.find('.btn_refrescar');
											var btn_sincronizar	= tr.find('.btn_sincronizar');
											observacion.html(reg.message);
											
											if (reg.message!='')
											{
												btn_refrescar.removeClass('disabled');
												btn_sincronizar.addClass('disabled');
											}else{
												btn_sincronizar.removeClass('disabled');
											}//end if
											
										 });
										 
										$(".btn_sincronizar_general").removeClass('disabled');
									}else{
										console.log('response:',response);
										swal({title: '('+ response.code + ') '+response.message,		    											
											type: "error",
											html: false,
											showCancelButton: false,
											confirmButtonColor: "#DD6B55",
											showConfirmButton: true,
											});
									}//end if
								}//end finish				
							 }
			response = ajax_call(parameters, data);		
			return false;				
		}//end function consultarPreviewDispoRemote
		
		
		function limpiarSincronizar(proveedor, CleanNroRegProcesados)
		{
			var tr 					= $("#AGR");
			var agr_fecha			= tr.find('.fec_finca');
			var agr_nro_reg			= tr.find('.nro_reg');
			var agr_nro_procesados	= tr.find('.nro_procesados');
			var agr_observacion		 = tr.find('.observacion');
			
			var tr 					= $("#LMA");
			var lma_fecha			= tr.find('.fec_finca');
			var lma_nro_reg 		= tr.find('.nro_reg');
			var lma_nro_procesados	= tr.find('.nro_procesados');
			var lma_observacion 	= tr.find('.observacion');

			var tr 					= $("#HTC");
			var htc_fecha			= tr.find('.fec_finca');		
			var htc_nro_reg			= tr.find('.nro_reg');
			var htc_nro_procesados	= tr.find('.nro_procesados');
			var htc_observacion 	= tr.find('.observacion');
			
			if (proveedor=='ALL')
			{
				agr_nro_procesados.html('');
				lma_nro_procesados.html('');
				htc_nro_procesados.html('');
				agr_observacion.html('');
				lma_observacion.html('');
				htc_observacion.html('');								
								
				if (CleanNroRegProcesados==false)
				{
					agr_fecha.html('');
					lma_fecha.html('');
					htc_fecha.html('');	
					agr_nro_reg.html('');									
					lma_nro_reg.html('');
					htc_nro_reg.html('');
				}//end if			
			}else{
				switch (proveedor)
				{
					case 'AGR':
						agr_nro_procesados.html('');
						agr_observacion.html('');
						if (CleanNroRegProcesados==false){
							agr_fecha.html('');
							agr_nro_reg.html('');
						}//end if
						break;
					case 'LMA':
						lma_nro_procesados.html('');
						lma_observacion.html('');
						if (CleanNroRegProcesados==false){
							lma_fecha.html('');
							lma_nro_reg.html('');
						}//end if
						break;
					case 'HTC':
						htc_nro_procesados.html('');
						htc_observacion.html('');						
						if (CleanNroRegProcesados==false){
							  htc_fecha.html('');
							  htc_nro_reg.html('');
						}//end if
						break;
				}//end switch				
			}//end if
		}//end function limpiarSincronizar
		
		
		
		function sincronizarDispoRemote(proveedor)
		{
			limpiarSincronizar(proveedor, true);
			var tr 					= $("#AGR");
			var agr_fecha 			= tr.find('.fec_finca').html();
			var tr 					= $("#LMA");
			var lma_fecha 			= tr.find('.fec_finca').html();
			var tr 					= $("#HTC");
			var htc_fecha 			= tr.find('.fec_finca').html();

			if (proveedor=='ALL')
			{
				var data = 	{agr_connect: 1, htc_connect: 1, lma_connect:1,  agr_fecha: agr_fecha, lma_fecha: lma_fecha, htc_fecha: htc_fecha}
			}else{				
				switch (proveedor)
				{
					case 'AGR':
						var data = 	{agr_connect: 1, agr_fecha: agr_fecha}
						break;
					case 'LMA':
						var data = 	{lma_connect: 1, lma_fecha: lma_fecha}
						break;
					case 'HTC':
						var data = 	{htc_connect: 1, htc_fecha: htc_fecha}
						break;
				}//end switch
			}//end if
			data = JSON.stringify(data);
			var parameters = {	'type': 'POST',//'POST',
								'contentType': 'application/json',
								'url':'<?php echo($this->basePath()); ?>/dispo/disponibilidad/remotesincronizar',
								'control_process':true,
								'show_cargando':true,
								'async':true,
								'finish':function(response){
									//console.log('response:',response);									
									
									if (response.respuesta_codex=="OK")
									{
									   $.each(response.result, function(key, reg) {
											var tr 				= $("#"+reg.proveedor_id.toUpperCase());
											var nro_procesados	= tr.find('.nro_procesados');
											nro_procesados.html(reg.nro_reg);
										});	
										 $.each(response.connect, function(key, reg) {
											var tr 			= $("#"+key.toUpperCase());
											var observacion = tr.find('.observacion');											 
											observacion.html(reg.message);
										 });																
									}else{
										message_error(response.response.code, response.response.message, true);
										/*swal({title: '('+ response.response.code + ') '+response.response.message,		    											
											type: "error",
											html: false,
											showCancelButton: false,
											confirmButtonColor: "#DD6B55",
											showConfirmButton: true,
											});
										*/
									}//end if
								}//end finish				
							 }
			response = ajax_call(parameters, data);		
			return false;				
		}//end function sincronizarDispoRemote


		function DispoGrupo_ExportarExcel()
		{
			cargador_visibility('show');

			var url = '../../dispo/grupodispo/exportarExcelDispoGrupo';
			var params = '?grupo_dispo_cab_id='+$("#frm_dispo_grupo #grupo_dispo_cab_id").val()+
						 '&color_ventas_id='+$("#frm_dispo_grupo #color_ventas_id").val()+
					 	 '&calidad_variedad_id='+$("#frm_dispo_grupo #calidad_variedad_id").val();
			url = url + params;
			var win = window.open(url);
			
			cargador_visibility('hide');
		}//end function DispoGeneral_ExportarExcel
		
	</script>





    <div class="title-admin-section">
        <h1>PANEL DE CONTROL DE DISPONIBILIDAD</h1>
    </div>            
    
    <div class="row">   
        <section class="body-admin-section">                
            
            <div id="tabs_disponibilidad" class="table-container col-md-16 col-sm-16">	      
                  <!-- Nav tabs -->
                  <ul class="nav nav-tabs" role="tablist">
                    <li role="presentation" class="active"><a href="#tab_dispo_sincronizacion" aria-controls="tab_dispo_sincronizacion" role="tab" data-toggle="tab">SINCRONIZADOR</a></li>
                    <li role="presentation"><a href="#tab_dispo" aria-controls="tab_dis" role="tab" data-toggle="tab">DISPONIBILIDAD</a></li>
                    <li role="presentation"><a href="#tab_dispo_x_grupo" aria-controls="tab_dispo_x_grupo" role="tab" data-toggle="tab">DISPO X GRUPO</a></li>
                    <li role="presentation"><a href="#tab_usuarios" aria-controls="tab_usuarios" role="tab" data-toggle="tab">USUARIOS</a></li>
                  </ul>
        
            
                  <!-- Tab panes -->
                  <div class="tab-content" style="margin-top:10px">
                    <div role="tabpanel" class="tab-pane active" id="tab_dispo_sincronizacion">
                        <div class="panel panel-default">
                            <table id='tbl_proveedor'  class="clear table-head table-dispo tablesorter tableinit" style="width:100%">
                                <thead>
                                    <tr>
                                      <th rowspan="2" class="th-inner">&nbsp;FINCA&nbsp;</th>
                                      <th colspan="2" class="th-inner">SERVER FINCAS</th>
                                      <th class="th-inner">INTERNET</th>
                                      <th rowspan="2" class="th-inner">&nbsp;ACCION&nbsp;</th>
                                      <th width="100%" rowspan="2" class="th-inner">&nbsp;OBSERVACION&nbsp;</th>
                                    </tr>
                                    <tr>
                                        <th class="th-inner">&nbsp;FECHA&nbsp;</th>
                                        <th class="th-inner" nowrap>&nbsp;NRO. REG.&nbsp;</th>
                                        <th class="th-inner">PROCESADOS</th> 
                                    </tr>
                                 </thead>
                                 <tbody style="border: 1px solid #cdcdcd;">
                                    <tr id="AGR">
                                        <td>AGR</td>
                                        <td class="fec_finca"></td>
                                        <td class="nro_reg" ></td>
                                        <td class="nro_procesados"></td>
                                        <td nowrap>
	                                       	<a data-proveedor="AGR" href="#" class="btn_refrescar btn btn-primary btn-xs disabled"><i class="glyphicon glyphicon-refresh"></i> REFRESCAR</a>
                                        	<a data-proveedor="AGR" href="#" class="btn_sincronizar btn btn-primary btn-xs disabled"><i class="glyphicon glyphicon-cog"></i> PROCESAR</a>
                                        </td>
                                        <td width="100%" class="observacion" align="left">..</td>                        
                                    </tr>
                                    <tr id="HTC">
                                        <td>HTC</td>
                                        <td class="fec_finca"></td>
                                        <td class="nro_reg"></td>
                                        <td class="nro_procesados"></td>
                                        <td nowrap>
	                                       	<a data-proveedor="HTC" href="#" class="btn_refrescar btn btn-primary btn-xs disabled"><i class="glyphicon glyphicon-refresh"></i> REFRESCAR</a>
                                        	<a data-proveedor="HTC" href="#" class="btn_sincronizar btn btn-primary btn-xs disabled"><i class="glyphicon glyphicon-cog"></i> PROCESAR</a>
                                        </td>
                                        <td class="observacion" align="left">..</td>                    
                                  </tr>
                                    <tr id="LMA">
                                        <td>RLM</td>
                                        <td class="fec_finca"></td>
                                        <td class="nro_reg"></td>
                                        <td class="nro_procesados"></td>
                                        <td nowrap>
                                        	<a data-proveedor="LMA" href="#" class="btn_refrescar btn btn-primary btn-xs disabled"><i class="glyphicon glyphicon-refresh"></i> REFRESCAR</a>
                                        	<a data-proveedor="LMA" href="#" class="btn_sincronizar btn btn-primary btn-xs disabled"><i class="glyphicon glyphicon-cog"></i> PROCESAR</a>
                                        </td>
                                        <td class="observacion" align="left">..</td>                      
                                  </tr>
                                 </tbody>
                            </table>
                            <div class="clear" style="padding: 5px"></div>
                            <a  href="#" class="btn_refrescar btn btn-primary btn-xs" data-proveedor="ALL"><i class="glyphicon glyphicon-refresh"></i> REFRESCAR</a>
                            <a href="#" class="btn_sincronizar_general btn btn-primary btn-xs disabled" data-proveedor="ALL"><i class="glyphicon glyphicon-cog"></i> PROCESAR</a>
                    	</div>
                    </div>
                    <div role="tabpanel" class="tab-pane" id="tab_dispo">
                        <div class="panel panel-default">
                        
                        	<!--- Grilla principal de la DISPO GENERAL --->
                        	<form id="frm_dispo" name="frm_dispo" action="#" method="post" class="form-inline">
                                <div class="form-group">
                                	 <section class="body-admin-section">
                                     	<div class="accion-admin-section">
                                        	<div class="botonera-admin-section pull-left separator">
                                        		<button id="btn_nuevo" type="button" class="btn btn-primary btn-xs"><i class="glyphicon glyphicon-plus"></i> NUEVO</button>
                                                <button id="btn_mover" type="button" class="btn btn-primary btn-xs"><i class="glyphicon glyphicon-plus"></i> MOVER</button>
                                        	</div>
                                            <div class="busqueda-admin-section pull-left">
                                            	 <select  id="inventario_id" class="form-control input-sm"></select>
                                                 <select  id="calidad_id" class="form-control input-sm"></select>
                                                 <select  id="proveedor_id" class="form-control input-sm"></select>
                                          	     <select  id="color_ventas_id" class="form-control input-sm"></select>
                                                 <select name="calidad_variedad_id" class="form-control input-sm"  id="calidad_variedad_id">
                                                 </select>
                                                 
												<button id="btn_consultar" type="button" class="btn btn-primary btn-xs"><i class="glyphicon glyphicon-search"></i> BUSCAR</button>
												<button id="btn_excel" type="button" class="btn btn-primary btn-xs"><i class="glyphicon glyphicon-download-alt"></i></button>
                                            </div>
                                        </div>
                                     </section>
                                	 
                                     
                                </div>
                                <div class="row-fluid">                                	
                                    <table id="grid_dispo_general" class="grid grid-autoheight"></table>
                                    <div id="pager_dispo_general"></div>
                                </div>
                            </form>
                            
                            <!-- Modal Dispo General por Proveedor -->
                            <form id="frm_dispo_proveedor" name="frm_dispo_proveedor" action="#" method="post" class="form-group" />
                            	<input type="hidden" id="inventario_id" value="" />
                            	<input type="hidden" id="calidad_id" value="" />
                            	<input type="hidden" id="proveedor_id" value="" />
                            	<input type="hidden" id="variedad_id" value="" />
                                <input type="hidden" id="grado_id" value="" />
                                <input type="hidden" id="tallos_x_bunch" value="" />
                                <div class="modal fade" id="dialog_dispo_proveedores" tabindex="-1" role="dialog" aria-labelledby="Dialogo para Configurar el Stock de los Proveedores">
                                    <div class="modal-dialog modal-sm" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                                <h4 class="modal-title" id="myModalLabel"><span id="dialog_dispo_proveedores_titulo"></span></h4>
                                            </div>
                                            <div class="modal-body">
                                                <div class="row">
                                                    <div class="col-md-4">
                                                        <div class="row">
                                                            <div class="col-md-12 text-center">
                                                                AGR
                                                            </div>
                                                            <div class="col-md-12 text-center">
                                                                <input id="stock_agr" max-lenght="3" class="form-control" type="text" style="text-align:center" value="">
                                                            </div>
                                                         </div>
                                                    </div>
                                                    
                                                    <div class="col-md-4">
                                                        <div class="row">
                                                            <div class="col-md-12 text-center">
                                                                HTC
                                                            </div>
                                                            <div class="col-md-12 text-center">
                                                                <input id="stock_htc" max-lenght="3" class="form-control" type="text" style="text-align:center" value="">
                                                            </div>
                                                         </div>
                                                    </div>
    
                                                    <div class="col-md-4">
                                                        <div class="row">
                                                            <div class="col-md-12 text-center">
                                                                LMA
                                                            </div>
                                                            <div class="col-md-12 text-center">
                                                                <input id="stock_lma" max-lenght="3" class="form-control" type="text" style="text-align:center" value="">
                                                            </div>
                                                         </div>
                                                    </div>                                               	
                                                    
                                                </div>
                                                
                                                <p>
                                                <div class="row">
                                                    <div class="col-md-12 text-right">
                                                        <button id="btn_grabar" type="button" class="btn btn-primary btn-sm"><i class="glyphicon glyphicon-ok"></i> GRABAR</button>
                                                    </div>
                                                </div>
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                       		</form>
                              
                              
							<!-- Modal Dispo General para crear Variedades que no existen en la dispo -->
                            <form id="frm_variedad" name="frm_dispo_general_variedad" action="#" method="post" class="form-group" />
                            	<input type="hidden" id="inventario_id" value="" />
                            	<input type="hidden" id="calidad_id" value="" />
                            	<input type="hidden" id="proveedor_id" value="" />                              
                               
                                <div class="modal fade" id="dialog_dispo_variedad" tabindex="-1" role="dialog" aria-labelledby="Dialogo para crear una Variedad en la Dispo seleccionada">
                                    <div class="modal-dialog modal-md" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                                <h4 class="modal-title" id="myModalLabel"><span id="dialog_dispo_variedad_titulo"></span></h4>
                                            </div>
                                            <div class="modal-body">
                                            	
                                            	<div class="row">
                                                	<div class="col-md-12">
                                                    	<select  id="variedad_id" class="form-control input-sm"></select>
                                                        <input type="hidden" id="grado_seleccionado_id" value="" />
                                                    </div>
                                                    <div class="col-md-12">
                                                    	
                                                    	<table id="grid_dispo_variedad" class="grid"></table>
                               							<div id="pager_dispo_variedad"></div>
                                                        
                                                    </div>
                                                </div>
                                            	
                                                <fieldset id="fincas_stock">
                                                <div class="row">
                                                    <div class="col-md-4">
                                                        <div class="row">
                                                            <div class="col-md-12 text-center">
                                                                AGR
                                                            </div>
                                                            <div class="col-md-12 text-center">
                                                                <input id="agr_cantidad_bunch" max-lenght="3" class="form-control" type="text" style="text-align:center" value="">
                                                            </div>
                                                         </div>
                                                    </div>
                                                    
                                                    <div class="col-md-4">
                                                        <div class="row">
                                                            <div class="col-md-12 text-center">
                                                                HTC
                                                            </div>
                                                            <div class="col-md-12 text-center">
                                                                <input id="htc_cantidad_bunch" max-lenght="3" class="form-control" type="text" style="text-align:center" value="">
                                                            </div>
                                                         </div>
                                                    </div>
    
                                                    <div class="col-md-4">
                                                        <div class="row">
                                                            <div class="col-md-12 text-center">
                                                                LMA
                                                            </div>
                                                            <div class="col-md-12 text-center">
                                                                <input id="lma_cantidad_bunch" max-lenght="3" class="form-control" type="text" style="text-align:center" value="">
                                                            </div>
                                                         </div>
                                                    </div>                                               	
                                                </div>
                                                
                                                <p>
                                                <div class="row">
                                                    <div class="col-md-12 text-right">
                                                        <button id="btn_grabar" type="button" class="btn btn-primary btn-sm"><i class="glyphicon glyphicon-ok"></i> GRABAR</button>
                                                    </div>
                                                </div>
                                                </fieldset>
                                                
                                                </p>
                                               
                                            </div>
                                        </div>
                                    </div>
                                </div>                              
                       		</form>
                            
                            
    						<!-- Modal para cambiar masivamente el STOCK POR GRADO del la DISPO GENERAL ------------------------------->
                            <div class="modal fade" id="dialog_dispo_general_gradostock" tabindex="-1" role="dialog" aria-labelledby="Dialogo para cambiar masivamente el stock por grado de la DISPO GENERAL">
                                <div class="modal-dialog modal-lg" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                            <h4 class="modal-title" id="myModalLabel"><span id="dialog_dispo_general_stockgrado_titulo"></span></h4>
                                        </div>
                                        <div class="modal-body">

											<label class="sr-only" for="grid_dispogrupo_color">POPUP DISPO-GENERAL PARA CONFIGURAR EL STOCK MASIVO</label>
                                            <form id="frm_dispo_general_stockgrado" name="frm_dispo_general_stockgrado" action="#" method="post" />
                                            <input type="hidden" id="inventario_id" value="" />
                                                <input type="hidden" id="calidad_id" value="" />
                                                <input type="hidden" id="proveedor_id" value="" />
                                                <input type="hidden" id="grado_id" value="" />
                                            
                                            	<div class="row">
                                                	<div class="col-sm-4">
                                                   	  <div class="form-horizontal">
                                                        	<div class="form-group">                                                
                                                                <label for="porcentaje" class="col-sm-5 control-label">PORCENTAJE:</label>
                                                                <div class="col-sm-7">
                                                                	<div class="input-group">
                                                                   		<input type="text" class="form-control inputdata-number-and-decimal" id="porcentaje" style="text-align:right">
                                                                        <div class="input-group-addon">%</div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                            
                                                            <div class="form-group">                                                
                                                                <label for="valor" class="col-sm-5 control-label">VALOR:</label>
                                                                <div class="col-sm-7">
                                                                    <input type="text" class="form-control inputdata-number-no-decimal" id="valor" style="text-align:right">
                                                                </div>
                                                            </div>
                                                            
                                                            <div class="form-group">
                                                                <div class="col-sm-12">
                                                                    <button id="btn_grabar" type="button" class="btn btn-primary btn-sm" data-loading-text="Procesando..."><i class="glyphicon glyphicon-ok"></i> GRABAR</button>
                                                                </div>
															</div>
                                                            
                                                        </div>
                                                        
                                                    </div>
                                                	<div class="col-sm-4">      
                                                        <label class="sr-only" for="grid_dispogeneral_color">GRID DE COLORES</label>
                                                        <table id="grid_dispogeneral_color" class="grid"></table>   <!-- grid-autowidthcontainer -->
                                                        <div id="pager_dispogeneral_color"></div>
                                                    </div>
                                                    
                                                    <div class="col-sm-4">
                                                        <label class="sr-only" for="grid_dispogeneral_categoria">GRID DE CATEGORIAS</label>
                                                        <table id="grid_dispogeneral_categoria" class="grid"></table>   <!-- grid-autowidthcontainer -->
                                                        <div id="pager_dispogeneral_categoria"></div>

                                                    </div>
                                                </div>
                                            
                                            </form>

                                        </div>
                                    </div>
                                </div>
                            </div>                              
                             <!-- END para cambiar masivamente el STOCK POR GRADO del la DISPO GENERAL-------------------->           


    						<!-- Modal para MOVER STOCK en la DISPO GENERAL ------------------------------->
                            <div class="modal fade" id="dialog_dispo_general_moverstock" tabindex="-1" role="dialog" aria-labelledby="Dialogo para mover en la DISPO GENERAL">
                                <div class="modal-dialog modal-lg" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                            <h4 class="modal-title" id="myModalLabel"><span id="dialog_dispo_general_moverstock_titulo"></span></h4>
                                        </div>
                                        <div class="modal-body">

											<label class="sr-only" for="grid_dispogrupo_color">POPUP DISPO-GENERAL PARA MOVER EL STOCK</label>
                                            <form id="frm_dispo_general_moverstock" name="frm_dispo_general_moverstock" action="#" method="post" />
                                            	<input type="hidden" id="inventario_id" value="" />
                                                <input type="hidden" id="calidad_id" value="" />
                                                <input type="hidden" id="proveedor_id" value="" />
                                                <input type="hidden" id="color_ventas_id" value="" />
                                                <input type="hidden" id="calidad_variedad_id" value="" />

                         
                                                <div class="form-inline">
                                                        <div class="form-group">                                                
                                                            <label for="calidad_id">Destino Calidad:</label>
                                                            <select  id="calidad_id" class="form-control input-sm"></select>
                                                        </div>
    
                                                        <button id="btn_mover" type="button" class="btn btn-primary btn-sm" data-loading-text="Procesando..."><i class="glyphicon glyphicon-ok"></i> MOVER</button>
                                                </div>

                                            	<div class="row">
                                                	<div class="col-sm-12">      
                                                        <label class="sr-only" for="grid_dispogeneral_color">GRID DE DISPO - MOVER</label>
                                                        <table id="grid_dispogeneral_moverstock" class="grid grid-autoheight"></table>   <!-- grid-autowidthcontainer -->
                                                        <div id="pager_dispogeneral_moverstock"></div>
                                                    </div>
                                                </div>
                                            
                                            </form>

                                        </div>
                                    </div>
                                </div>
                            </div>                              
                             <!-- END Modal para MOVER STOCK en la DISPO GENERAL-------------------->           
                                                         
                            
                         </div>
                    </div>
                    

                    <!-- ...TAB DISPO X GRUPO -->
                    <div role="tabpanel" class="tab-pane" id="tab_dispo_x_grupo">
                        <div class="panel panel-default">
                        	<!--- Grilla principal de la DISPO X GRUPO --->
                        	<form id="frm_dispo_grupo" name="frm_dispo_grupo" action="#" method="post" class="form-inline">
                                <div class="form-group">
                                	 <section class="body-admin-section">
                                     	<div class="accion-admin-section">
                                        	<div class="botonera-admin-section pull-left separator">
                                        		<button id="btn_nuevo" type="button" class="btn btn-primary btn-xs"><i class="glyphicon glyphicon-plus"></i> NUEVO</button>
                                                <button id="btn_modificar" type="button" class="btn btn-primary btn-xs"><i class="glyphicon glyphicon-pencil"></i>  MODIFICAR</button>
                                        	</div>
                                            <div class="busqueda-admin-section pull-left">
                                            	 <select  id="grupo_dispo_cab_id" class="form-control input-sm"></select>
                                                 &nbsp;&nbsp;<a id="editar_dispo_grupo"><span id="info_grupo_dispo_cab" class="bg-info"></span></a>
                                                 <select  id="color_ventas_id" class="form-control input-sm"></select>
                                                 <select  id="calidad_variedad_id" class="form-control input-sm"></select>
                                            </div>
                                            <span>&nbsp;&nbsp;&nbsp;</span>
                                            <span class="botonera-admin-section">
                                            <button id="btn_consultar" type="button" class="btn btn-primary btn-xs"><i class="glyphicon glyphicon-search"></i> BUSCAR</button>
                    						<button id="btn_excel" type="button" class="btn btn-primary btn-xs"> <i class="glyphicon glyphicon-download-alt"></i></button>
                    						</span>  
                                        </div>
                                     </section>
                                	 
                                     
                                </div>
                                <table id="grid_dispo_grupo" class="grid grid-autoheight"></table>
                                <div id="pager_dispo_grupo"></div>
                            </form> 


							<!-- Modal para crear GRUPOS X DISPO ------------------------------->
                            <div class="modal fade" id="dialog_dispo_grupo_mantenimiento" tabindex="-1" role="dialog" aria-labelledby="Dialogo para el mantenimiento del Grupo Mantenimiento">
                                <div class="modal-dialog modal-md" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                            <h4 class="modal-title" id="myModalLabel"><span id="dialog_dispo_grupo_mantenimiento_titulo"></span></h4>
                                        </div>
                                        <div class="modal-body">
                                        
                                            <form id="frm_dispo_grupo_mantenimiento" name="frm_dispo_grupo_mantenimiento" action="#" method="post" class="form-horizontal" />
                                            	<input type="hidden" id="accion" name="accion" value="">
                                                <div class="form-group">                                                
                                                    <label for="id" class="col-md-3 control-label">Id:</label>
                                                    <div class="col-md-2">
                                                        <input type="text" class="form-control" id="id" disabled>
                                                    </div>
                                                </div>

                                                <div class="form-group">
                                                    <label for="nombre" class="col-md-3 control-label">Nombre:</label>
                                                    <div class="col-md-9">
                                                        <input type="text" class="form-control" id="nombre" placeholder="Nombre" validate="required" validateMessage="Ingrese un nombre">
                                                    </div>
                                                </div>

                                                <div class="form-group">
                                                    <label for="inventario_id" class="col-md-3 control-label">Inventario:</label>
                                                    <div class="col-md-9">
                                                        <select  id="inventario_id" class="form-control" validate="required" validateMessage="Seleccione un inventario"></select>
                                                    </div>
                                                </div>

                                                <div class="form-group">                                                
                                                    <label for="calidad_id" class="col-md-3 control-label">Calidad:</label>
                                                    <div class="col-md-9">
                                                    	<select  id="calidad_id" class="form-control" validate="required" validateMessage="Seleccione la calidad"></select>                                                    
                                                    </div>
                                                </div>

                                                <div class="form-group">                                                                                                   
                                                    <div class="col-md-offset-2 col-md-10 text-right">
                                                    	<button id="btn_grabar" type="button" class="btn btn-primary btn-sm"><i class="glyphicon glyphicon-ok"></i> GRABAR</button>
                                                    </div>
                                                </div>
                                            </form>

                                        </div>
                                    </div>
                                </div>
                            </div>                              
                             <!-- END Modal GRUPOS X DISPO ----------------------------------------------------------------------------------------->  
                             
                             
    						<!-- Modal para cambiar masivamente el STOCK POR GRADO del la DISPO X GRUPO ------------------------------->
                            <div class="modal fade" id="dialog_dispo_grupo_gradostock" tabindex="-1" role="dialog" aria-labelledby="Dialogo para cambiar masivamente el stock por grado">
                                <div class="modal-dialog modal-lg" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                            <h4 class="modal-title" id="myModalLabel"><span id="dialog_dispo_grupo_stockgrado_titulo"></span></h4>
                                        </div>
                                        <div class="modal-body">
                                        	<label class="sr-only" for="grid_dispogrupo_color">POPUP DISPO-POR-GRUPO PARA CONFIGURAR EL STOCK MASIVO</label>
                                            <form id="frm_dispo_grupo_stockgrado" name="frm_dispo_grupo_stockgrado" action="#" method="post" />
                                                <input type="hidden" id="grupo_dispo_cab_id" value="" />
                                                <input type="hidden" id="grado_id" value="" />
                                            
                                            	<div class="row">
                                                	<div class="col-sm-4">
                                                    
                                                    	<div class="form-horizontal">
                                                        	<div class="form-group">                                                
                                                                <label for="porcentaje" class="col-sm-5 control-label">PORCENTAJE:</label>
                                                                <div class="col-sm-7">
                                                                	<div class="input-group">
                                                                   		<input type="text" class="form-control inputdata-number-and-decimal" id="porcentaje" style="text-align:right">
                                                                        <div class="input-group-addon">%</div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                            
                                                            <div class="form-group">                                                
                                                                <label for="valor" class="col-sm-5 control-label">VALOR:</label>
                                                                <div class="col-sm-7">
                                                                    <input type="text" class="form-control inputdata-number-no-decimal" id="valor" style="text-align:right">
                                                                </div>
                                                            </div>
                                                            
                                                            <div class="form-group">
                                                                <div class="col-sm-12">
                                                                    <button id="btn_grabar" type="button" class="btn btn-primary btn-sm" data-loading-text="Procesando..."><i class="glyphicon glyphicon-ok"></i> GRABAR</button>
                                                                </div>
															</div>
                                                            
                                                        </div>
                                                        
                                                    </div>
                                                	<div class="col-sm-4">      
                                                        <label class="sr-only" for="grid_dispogrupo_color">GRID DE COLORES</label>
                                                        <table id="grid_dispogrupo_color" class="grid"></table>   <!-- grid-autowidthcontainer -->
                                                        <div id="pager_dispogrupo_color"></div>
                                                    </div>
                                                    
                                                    <div class="col-sm-4">
                                                        <label class="sr-only" for="grid_dispogrupo_categoria">GRID DE CATEGORIAS</label>
                                                        <table id="grid_dispogrupo_categoria" class="grid"></table>   <!-- grid-autowidthcontainer -->
                                                        <div id="pager_dispogrupo_categoria"></div>

                                                    </div>
                                                </div>
                                            
                                            </form>

                                        </div>
                                    </div>
                                </div>
                            </div>                              
                             <!-- END Modal GRUPOS X DISPO ----------------------------------------------------------------------------------------->                           
                             
                             
                        </div>
                    </div>
 
 					<!---  TABS PARA EL GRUPO DE USUARIOS ASIGNADO A LA DISPO ---------------------------------------------------------------------->
                    <div role="tabpanel" class="tab-pane" id="tab_usuarios">
                    	<div class="panel panel-default">
                        
                        	<form id="frm_grupo_usuario" name="frm_grupo_usuario" action="#" method="post" class="form-inline">
                                <div class="form-group">
                                	 <section class="body-admin-section">
                                     	<div class="accion-admin-section">                                        	
                                            <div class="busqueda-admin-section pull-left">
                                            	 <select  id="grupo_dispo_cab_id" class="form-control input-sm"></select>
                                                 <button id="btn_consultar" type="button" class="btn btn-primary btn-xs" style="display: none;"></button>&nbsp;&nbsp;<span id="info_grupo_dispo_cab" class="bg-info"></span>
                                                 <button id="btn_enviar_dispo" type="button" class="btn btn-success btn-xs"><span class="glyphicon glyphicon-envelope"></span>&nbsp;&nbsp;ENVIAR DISPO POR EMAIL</button>
                                            </div>
                                        </div>
                                     </section>
                                </div>
                                
                             	<div class="clearfix">
                             		<table cellpadding="0" cellspacing="0" border="0">
                                    	<tr>
                                        	<td>
                                                <table id="grid_grupodispo_noasignados" class="grid grid-autoheight" ></table>
                                                <div id="pager_grupodispo_noasignados"></div>
                                            </td>
                                            <td>
                                                <p><a id="btn_asignar_grupo"   role="button"   class="btn btn-primary btn-sm">ASIGNAR <i class="glyphicon glyphicon-forward"> </i></a>
                                                </p><br>
                                                <p><a id="btn_eliminar_grupo"   role="button"   class="btn btn-primary btn-sm"><i class="glyphicon glyphicon-backward"></i> QUITAR&nbsp;&nbsp;&nbsp;</a>
                                                </p>

                                            </td>
                                            <td>
                                                <table id="grid_grupodispo_asignados" class="grid grid-autoheight" ></table>
                                                <div id="pager_grupodispo_asignados"></div>                                            
                                            </td>
                                        <tr>
                                    </table>
		                     	</div>                             
                           	</form> 
                            
                            
						</div>
 					</div>
 					<!--- END TAB USUARIOS ASIGNADOS A LA DISPO ----------------------------------------------------------------------------------->
 
          		</div>     
            </div>            
        </section>
    </div>	            




	       	 	<!-- DIALOGS -->	
		<?php echo $this->partial('dispo/dialog/seleccioncliente', array(
				'identidad_usuario' 		=> $this->identidad_usuario,
				'opcion_consulta'			=> 'view_seleccionar_marcacion'
		));
		?>	