<meta charset="UTF-8">


<script>

	$(document).ready(function () {
		$(".loading-state").hide();

		$("#btn_save").on('click', function(event){
			consultar_disponibilidad();
			return false;
		});		 

		 consultar_marcacion();	
		 consultar_agencia_carga();	 
	});//$(document).ready


	
	function consultar_marcacion(){
		var data = {texto_primer_elemento: "Marcación"}
		data = JSON.stringify(data);
		
		//var data = '';
		var parameters = {	'type': 'POST',//'POST',
							'contentType': 'application/json',
							'url':'<?php echo($this->basePath()); ?>/dispo/marcacion/getcombo',
							'cancel_process_previous':false,
							'show_cargando':true,
							'finish':function(response){
									if (response.respuesta_code=='OK'){
										$("#marcacion_sec").html(response.opciones);									
									}else{
										message_error('ERROR', response);
									}//end if								
							}							
		                 }
		response = ajax_call(parameters, data);		
		return false;
	}//end function consultar_registro	


	function consultar_agencia_carga(){
		var data = {texto_primer_elemento: "Ag. de Carga"}
		data = JSON.stringify(data);
		
		//var data = '';
		var parameters = {	'type': 'POST',//'POST',
							'contentType': 'application/json',
							'url':'<?php echo($this->basePath()); ?>/dispo/agenciacarga/getcombo',
							'cancel_process_previous':false,
							'show_cargando':true,
							'finish':function(response){
									if (response.respuesta_code=='OK'){
										$("#agencia_carga_id").html(response.opciones);									
									}else{
										message_error('ERROR', response);
									}//end if								
							}							
		                 }
		response = ajax_call(parameters, data);		
		return false;
	}//end function consultar_registro	


	function consultar_disponibilidad()
	{
		if ($('#marcacion_sec').val()=='')
		{
			alert('Debde de seleccionar una marcacion');
			return false;
		}

		if ($('#agencia_carga_id').val()=='')
		{
			alert('Debde de seleccionar una agencia de carga');
			return false;
		}

		$('#frm').submit();
	}//end function consultar_disponibilidad
	

</script>
	
	<form id="frm" name="frm" action="<?php echo($this->basePath()); ?>/dispo/disponibilidad/asignarMarcacionAgencia" method="post">	
	<section class="col-md-15 col-sm-15">
	    <div class="title-section clearfix">
	        <h1>
	            Disponibilidad
	        </h1>
	
	        <div class="marca-container pull-right">
	            <div class="marca-info separator flo-left clearfix">
	                <img class="flo-left" src="<?php echo($this->basePath()); ?>/images/marca-icon.png" alt="">
	                <select class="form-control flo-left" name="marcacion_sec" id="marcacion_sec">
	                </select>	                
	            </div>
	
	            <div class="carga-info flo-left separator clearfix">
	                <img class="flo-left" src="<?php echo($this->basePath()); ?>/images/carga-icon.png" alt="">
	                <select class="form-control flo-left" name="agencia_carga_id" id="agencia_carga_id">
	                </select>
	            </div>
	
	            <div class="add-label flo-left pointer" id="btn_save">
	                    Save This
	            </div>
	        </div>
	    </div>
	</section>
	 </form>	


