<meta charset="UTF-8">


<script>

	$(document).ready(function () {
		$(".loading-state").hide();

		$("#btn_save").on('click', function(event){
			consultar_disponibilidad();
			return false;
		});		 

		 //consultar_marcacion();	
		 //consultar_agencia_carga();
		consultar_marcacion_y_agenciacarga();	 
	});//$(document).ready


	function consultar_marcacion_y_agenciacarga()
	{
		var data = {
						marcacion_texto_primer_elemento: "LABEL / MARK",
						agenciacarga_texto_primer_elemento: "CARGO AGENCY"
				  }
		data = JSON.stringify(data);
		
		//var data = '';
		var parameters = {	'type': 'POST',//'POST',
							'contentType': 'application/json',
							'url':'<?php echo($this->basePath()); ?>/dispo/disponibilidad/getcomboMarcacionAgenciacarga',
							'cancel_process_previous':false,
							'show_cargando':true,
							'finish':function(response){
									if (response.respuesta_code=='OK'){
										$("#marcacion_sec").html(response.marcacion_opciones);
										$("#agencia_carga_id").html(response.agenciacarga_opciones);							
									}else{
										message_error('ERROR', response);
									}//end if								
							}							
		                 }
		response = ajax_call(parameters, data);		
		return false;
	}//end function 
	

/*	function consultar_agencia_carga(){
		var data = {texto_primer_elemento: "Ag. de Carga"}
		data = JSON.stringify(data);
		
		//var data = '';
		var parameters = {	'type': 'POST',//'POST',
							'contentType': 'application/json',
							'url':'<?php echo($this->basePath()); ?>/dispo/agenciacarga/getcombo',
							'cancel_process_previous':false,
							'show_cargando':true,
							'finish':function(response){
									if (response.respuesta_code=='OK'){
										$("#agencia_carga_id").html(response.opciones);									
									}else{
										message_error('ERROR', response);
									}//end if								
							}							
		                 }
		response = ajax_call(parameters, data);		
		return false;
	}//end function consultar_agencia_carga	
*/

	function consultar_disponibilidad()
	{
		if ($('#marcacion_sec').val()=='')
		{
			alert('Select Label / Mark');;
			return false;
		}

		if ($('#agencia_carga_id').val()=='')
		{
			alert('Select Cargo Agency');
			return false;
		}

		$('#frm').submit();
	}//end function consultar_disponibilidad
	

</script>
		<form id="frm" name="frm" action="<?php echo($this->basePath()); ?>/dispo/disponibilidad/asignarMarcacionAgencia" method="post">	
		    <div class="title-section">
		        <h1>Availability</h1>
		    </div>
		    	
	        <div class="container-fluid pull-right">
            	<div class="row marca-container">
            		<div class="pull-left">
	                	<div class="pull-left">
	                    	<img src="<?php echo($this->basePath()); ?>/images/marca-icon.png" alt="">
	                     </div>
	                     <div class="pull-left separator" >
		                	<select class="form-control" name="marcacion_sec" id="marcacion_sec"></select>
	                    </div>
	                </div>
                    <div class="pull-left">
	                    <div class="pull-left">
	                    	<img src="<?php echo($this->basePath()); ?>/images/carga-icon.png" alt="">
	                    </div>
	                    <div class="pull-left separator">
		                    <select class="form-control" name="agencia_carga_id" id="agencia_carga_id"></select>
	                    </div>
	                </div>
                    <div class="pull-left">
                    	<input  class="btn btn-default" type="button" id="btn_save" value="Save"  />
                    </div>
				</div>
                
			</div>
		</form>	



	       	 	<!-- DIALOGS -->	
		<?php echo $this->partial('dispo/dialog/seleccioncliente', array(
				'identidad_usuario' 		=> $this->identidad_usuario,
				'opcion_consulta'			=> 'view_seleccionar_marcacion'
		));
		?>	