<meta charset="UTF-8">
<script type="text/javascript" src="<?php echo($this->basePath('js/module/dispo/tipocajamatriz/mantenimiento.js')); ?>"></script>
<script>
	$(document).ready(function () {
		InputData_TrimAll();
	});//$(document).ready
</script>


<div class="title-admin-section">
	<h1>CAJA MATRIZ</h1>
</div>            

<div class="row">   
	<section class="body-admin-section">                
					
		<form id="frm_tipo_caja_busqueda" name="frm_tipo_caja_busqueda" action="#" method="post" class="form-inline">
			<div class="form-group">
				 <section class="body-admin-section">
					<div class="accion-admin-section">
                        <div class="botonera-admin-section pull-left separator">
                            <button id="btn_actualizacion_masiva" type="button" class="btn btn-primary btn-xs"><i class="glyphicon glyphicon-plus"></i> ACTUALIZACION MASIVA</button>
                        </div>                    
						<div class="busqueda-admin-section pull-left">
							 <select  id="tipo_caja_id" class="form-control input-sm"></select>                        
							 <select  id="inventario_id" class="form-control input-sm"></select>
							 <button id="btn_consultar" type="button" class="btn btn-primary btn-xs"><i class="glyphicon glyphicon-search"></i> BUSCAR</button>
						</div>
					</div>
				 </section>
				 
				 
			</div>
			<div class="row-fluid">                                	
				<table id="grid_tipo_caja" class="grid grid-autoheight"></table>
				<div id="pager_tipo_caja"></div>
			</div>
		</form>            
        
        
        <!-- Modal para crear GRUPOS X DISPO ------------------------------->
        <div class="modal fade" id="dialog_tipo_caja_actualizacion" tabindex="-1" role="dialog" aria-labelledby="Dialogo para el la actualizacion masiva de Unidades de Bunchs para las cajas">
            <div class="modal-dialog modal-md" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">ACTUALIZACION MASIVA</h4>
                    </div>
                    <div class="modal-body">
                        <form id="frm_tipo_caja_matenimiento" name="frm_tipo_caja_matenimiento" action="#" method="post" class="form-horizontal" />
                          	<input type="hidden" id="inventario_id" value="" />
                            <input type="hidden" id="tipo_caja_id" value="" />
                            <div class="form-group">                                                
                                <label for="id" class="col-md-4 control-label">Tipo Caja:</label>
                                <div class="col-md-8">
                                     <p class="form-control-static" id="tipo_caja_nombre">X</p>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="nombre" class="col-md-4 control-label">Inventario:</label>
                                <div class="col-md-8">
									<p class="form-control-static" id="inventario_nombre">X</p>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="inventario_id" class="col-md-4 control-label">Variedad:</label>
                                <div class="col-md-8">
                                    <select  id="variedad_id" class="form-control"></select>
                                </div>
                            </div>

                            <div class="form-group">                                                
                                <label for="calidad_id" class="col-md-4 control-label">Grado:</label>
                                <div class="col-md-8">
                                    <select  id="grado_id" class="form-control"></select>                                                    
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="nombre" class="col-md-4 control-label">Bunches Por Caja:</label>
                                <div class="col-md-8">
                                    <input type="text" class="form-control" id="unds_bunch" placeholder="Cantidad de Bunchs" validate="required" validateMessage="Ingrese cantidad de Bunches">
                                </div>
                            </div>

                            <div class="form-group">                                                                                                   
                                <div class="col-md-offset-2 col-md-10 text-right">
                                    <button id="btn_grabar" type="button" class="btn btn-primary btn-sm"><i class="glyphicon glyphicon-ok"></i> GRABAR</button>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>                              
        
         <!-- END Modal GRUPOS X DISPO ----------------------------------------------------------------------------------------->  	 
	</section>
</div>	            
