<meta charset="UTF-8">
<script type="text/javascript" src="<?php echo($this->basePath('js/module/dispo/tipocajamatriz/mantenimiento.js')); ?>"></script>
<script>
	$(document).ready(function () {
		InputData_TrimAll();
	});//$(document).ready
</script>


<div class="title-admin-section">
	<h1>CAJA MATRIZ</h1>
</div>            

<div class="row">   
	<section class="body-admin-section">                
					
	</section>
</div>	            
