
<script type="text/javascript" src="<?php echo($this->basePath('js/module/dispo/variedad/variedad.js')); ?>"></script>



<div class="title-admin-section">
	<h1>VARIEDADES</h1>
</div>


<div class="row">   
	<section class="body-admin-section">    	
    	<div class="accion-admin-section"> 	
        	<div class="botonera-admin-section pull-left separator">
        		<form id="frm_nuevo" name="frm_nuevo">
            		<a id="btn_nuevo" class="btn btn-small btn-primary btn-sm" href="#" role="button"><i class="glyphicon glyphicon-plus icon-white"></i> Nuevo</a>
            	</form>
            </div>
        	<div class="busqueda-admin-section pull-left">	
            	<div class="form-inline">
	                <form id="frm_busqueda" action="<?php echo($this->basePath()); ?>/dispo/variedad/mantenimiento" method="post" >
		                <div class="input-group" style="display:inline-flex">    
		                	<input name="criterio_busqueda" id="criterio_busqueda" type="text" class="form-control input-sm" placeholder="Search" size="20" value="<?php echo($this->criterio_busqueda); ?>" />
		                     <div class="input-group">
								<select  name="busqueda_estado" id="busqueda_estado" class="form-control input-sm" style="width:130px">
			    	                <?php echo($this->busqueda_estado); ?>
		    	                </select>                                       
		                    </div>
		                    <div class="input-group">
								<select  name="busqueda_color" id="busqueda_color" class="form-control input-sm" style="width:130px">
			    	                <?php echo($this->busqueda_color); ?>
		    	                </select>                                       
		                    </div>
		 					<span class="input-group-btn">
		                    	<button id="btn_consultar" class="btn  btn-primary btn-sm" type="button"><i class="glyphicon glyphicon-search icon-white"></i> Buscar</button>
		                    	
		                    </span>    
		                    <span>&nbsp;&nbsp;</span>
		                    <span class="input-group">
		                    <button id="btn_excel" type="button" class="btn btn-primary btn-sm"> <i class="glyphicon glyphicon-download-alt"></i> Generar Reporte</button>
		                    </span>                    
		                </div>                
	                </form>                  
				</div>
            </div>
		</div>
		<div class="clearfix"></div>
        <div>
			<table id="grid_variedad_listado" class="grid grid-autoheight"></table>
            <div id="pager_variedad_listado"></div>        	
        </div>
	</section>
</div>				
    

        <!--  DIALOG DE MANTENIMIENTO -->
            <form id="frm_mantenimiento_variedad">
			<div class="modal fade" id="dialog_mantenimiento" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			  <div class="modal-dialog">
			    <div class="modal-content">
			      <div class="modal-header">
			        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
			        <h4 class="modal-title" id="myModalLabel">VARIEDAD (<span id="dialog_mantenimiento_variedad_nombre"></span>)</h4>
			      </div>
			      <div class="modal-body clearfix">
			        <div class="clearfix">
                        
			        	  <table border="0" align="center" cellpadding="0" cellspacing="0" class="tbl_formulario_mantenimiento">
			        	      <tr>
			        	        <td><label class="control-label">ID:</label></td>
			        	        <td>
                                <input id="variedad_id" name="variedad_id" type="text" class="form-control input-sm" style="width:50px" value="" maxlength="3" max-lenght="3" validate="required" validateMessage="Ingrese un codigo">
                                <input type="hidden" name="accion" id="accion" value="" /></td>
		        	          </tr>
			        	      <tr>
			        	        <td><label class="control-label">NOMBRE:</label></td>
			        	        <td><input name="nombre" type="text" class="form-control input-sm" id="nombre" style="width:350px" value="" maxlength="30" max-lenght="30" validate="required" validateMessage="Ingrese un nombre"></td>
		        	          </tr>
		        	          <tr>
			        	        <td><label class="control-label">NOMBRE TECNICO:</label></td>
			        	        <td><input name="nombre_tecnico" type="text" class="form-control input-sm" id="nombre_tecnico" style="width:350px" value="" maxlength="30" max-lenght="30" ></td>
		        	          </tr>
		        	             <tr>
			        	        <td><label class="control-label">CALIDAD:</label></td>
			        		    <td><select  name="calidad_variedad_id" class="select-class2" id="calidad_variedad_id" validate="required" validateMessage="Seleccione Calidad"></select></td>
		        	          </tr>	
		        	           <tr>
			        	        <td><label class="control-label">COLOR :</label></td>
			        		    <td><select  name="color" class="select-class2" id="color" ></select></td>
		        	          </tr>	
		        	           <tr>
			        	        <td><label class="control-label">COLOR 2:</label></td>
			        		    <td><select  name="color2" class="select-class2" id="color2" ></select></td>
		        	          </tr>	
		        	          <tr>
			        	        <td><label class="control-label">GRUPO:</label></td>
			        		    <td><select  name="grupo_color_id" class="select-class2" id="grupo_color_id" validate="required" validateMessage="Seleccione Grupo"></select></td>
		        	          </tr>	
			        	      <tr>
			        	        <td><label class="control-label">COLOR BASE:</label></td>
			        		    <td><select  name="colorbase" class="select-class2" id="colorbase" validate="required" validateMessage="Seleccione Color Base"></select></td>
		        	          </tr>	
		        	            <tr>
			        	        <td><label class="control-label">SOLIDO:</label></td>
			        		    <td><select  name="solido" class="select-class2" id="solido" validate="required"></select></td>
		        	          </tr>
		        	            <tr>
			        	        <td><label class="control-label">REAL:</label></td>
			        		    <td><select  name="es_real" class="select-class2" id="es_real" validate="required"></select></td>
		        	          </tr>
		        	           <tr>
			        	        <td><label class="control-label">CULTIVADA:</label></td>
			        	        <td><select  name="cultivada" class="select-class2" id="cultivada" ></select></td>
		        	          </tr>
		        	          <tr>
			        	        <td><label class="control-label">OBTENTOR:</label></td>
			        		    <td><select  name="obtentor_id" class="select-class2" id="obtentor_id" ></select></td>
		        	          </tr>	
		        	          <tr>
			        	        <td><label class="control-label">TAMAÑO BUNCH:</label></td>
			        		    <td><select  name="tamano_bunch_id" class="select-class2" id="tamano_bunch_id" validate="required" validateMessage="Seleccione un Tamaño"></select></td>
		        	          </tr>	
		        	          <tr>
			        	         <td><label class="control-label">COLOR VENTAS:</label></td>
			        	         <td><select id="color_ventas_id" name="color_ventas_id"  class="select-class2" validate="required" validateMessage="Seleccione Color Ventas"></select></td>
			        	       </tr>
			        	      <tr>
			        	        <td><label class="control-label">URL FICHA:</label></td>
			        	        <td><input name="url_ficha" type="text" class="form-control input-sm" id="url_ficha" style="width:350px" value="" ></td>
		        	          </tr>
		        	           <tr>
			        	        <td><label class="control-label">CICLO:</label></td>
			        	        <td><input name="ciclo_prod" type="text" class="inputdata-number-no-decimal" id="ciclo_prod" style="width:350px" value="" maxlength="6"  validate="required" validateMessage="Ingrese ciclo"></td>
		        	          </tr>
		        	           <tr>
			        	        <td><label class="control-label">MENSAJE:</label></td>
			        	        <td><input name="mensaje" type="text" class="form-control input-sm" id="mensaje" style="width:350px" value="" maxlength="70" ></td>
		        	          </tr>
		        	           <tr>
			        	        <td><label class="control-label">ESTADO PROD. ESPECIAL:</label></td>
			        	        <td><input type="checkbox" name="est_producto_especial" id="est_producto_especial" value=""></td>
		        	          </tr>	
		        	           <tr>
			        	        <td><label class="control-label">ESTADO:</label></td>
			        	        <td><select  name="estado" class="select-class2" id="estado"></select></td>
		        	          </tr>		
		        	            <tr>
			        	        <td><label class="control-label">SINCRONIZADO:</label></td>
			        	        <td>
 
									<span id="sincronizado_pendiente" class="glyphicon glyphicon-time icon-white" style="color:red; display:none" ></span>
									<span id="sincronizado_ok" class="glyphicon glyphicon-ok icon-white" style="color:green; display:none"></span>
                                    <span id="lbl_fec_sincronizado"></span>
 
                                </td>
		        	          </tr>        	   
			        	      <tr>
			        	        <td>&nbsp;</td>
			        	        <td>&nbsp;</td>
		        	        </tr>

			        	      <tr>
			        	        <td><label class="control-label">Ingreso:</label></td>
			        	        <td><b><span id="lbl_usuario_ing"></span></b> - <span id="lbl_fec_ingreso"></span></td>
		        	          </tr>
			        	      <tr>
			        	        <td><label class="control-label">Modificación:</label></td>
			        	        <td><b><span id="lbl_usuario_mod"></span></b> - <span id="lbl_fec_modifica"></span></td>
		        	          </tr>
	        	      </table>
                      <br>
						<center><a id="btn_grabar" class="btn btn-small btn-success" href="#"><i class="glyphicon glyphicon-plus icon-save"></i> Grabar</a></center>
     
		        	  <!--   div id="dialog_oferta_formulario"></div -->			
			        </div>
			      </div>
			    </div>
			  </div>
			</div>
			</form>
	