
<script>

$(document).ready(function () {


	
	});//$(document).ready
    </script>



<div class="title-admin-section">
	<h1>BUSCADOR</h1>
</div>

<head>
    <title>buscador typeahead</title>
    <meta http-equiv="content-type" content="text/html;charset=utf-8" />
    <meta name="generator" content="Geany 1.23.1" />
</head>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<script src="http://cdn.jsdelivr.net/typeahead.js/0.9.3/typeahead.min.js"></script>
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css">

<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
<style>
.tt-query,
.tt-hint {
    width: 150%;
    height: 34px;
    padding: 6px 12px;
    font-size: 14px;
    line-height: 30px;
    border: 2px solid #ccc;
    -webkit-border-radius: 8px;
    -moz-border-radius: 8px;
    border-radius: 8px;
    outline: none;
}

.tt-query {
    -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
    -moz-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
    box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
}

.tt-hint {
    color: #999
}

.tt-dropdown-menu {
    width: 250px;
    margin-top: 12px;
    padding: 8px 0;
    background-color: #fff;
    border: 1px solid #ccc;
    border: 1px solid rgba(0, 0, 0, 0.2);
    -webkit-border-radius: 8px;
    -moz-border-radius: 8px;
    border-radius: 8px;
  -webkit-box-shadow: 0 5px 10px rgba(0,0,0,.2);
    -moz-box-shadow: 0 5px 10px rgba(0,0,0,.2);
    box-shadow: 0 5px 10px rgba(0,0,0,.2);
}

.tt-suggestion {
    padding: 3px 20px;
    font-size: 18px;
    line-height: 24px;
}

.tt-suggestion.tt-is-under-cursor {
    color: #fff;
    background-color: #0097cf;

}
</style>
<script>

$(document).ready(function(){
		    $("#buscador").typeahead({
		    	minLength: 3,
		        name : 'buscador',
		        remote: {
		            url : '../../dispo/buscador/consultarclientefactura?q=%QUERY'
		        }
		    });
	
		   
		    $("#buscador").on("typeahead:selected", function(e,datum) { 
			   // $codigo=datum.id;
			    $("#codigo").val(datum.id); 
			})
	    

});
</script>
<body>
<br>
   
<!-- Small modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-sm">Small modal</button>

<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
    <div><br>
      <center><input type="text" name="buscador" id="buscador" class="" ></center>
      <br>
      <br>
      <center><input type="text" name="codigo" id="codigo" class="form-control" value=""></center>
      <br>
      <br>
      
     </div>
    </div>
  </div>
</div>


    
    </body>
</html>