
<script>

$(document).ready(function () {


	
	});//$(document).ready
    </script>



<div class="title-admin-section">
	<h1>BUSCADOR</h1>
</div>

<head>
    <title>buscador typeahead</title>
    <meta http-equiv="content-type" content="text/html;charset=utf-8" />
    <meta name="generator" content="Geany 1.23.1" />
</head>


<script>

$(document).ready(function(){
   $("#buscador").typeahead({
		    	minLength: 3,
		        name : 'buscador',
		        remote: {
		            url : '../../dispo/buscador/consultarclientefactura?q=%QUERY'
		        }
		    });



   var bestPictures = new Bloodhound({
	   datumTokenizer: Bloodhound.tokenizers.obj.whitespace('value'),
	   queryTokenizer: Bloodhound.tokenizers.whitespace,
	   prefetch: '../data/films/post_1960.json',
	   remote: {
	     url: '../../dispo/buscador/consultarclientefactura?q=%QUERY',
	     wildcard: '%QUERY'
	   }
	 });

	 $('#remote .typeahead').typeahead(null, {
	   name: 'best-pictures',
	   display: 'value',
	   source: bestPictures
	 });
	

		   
		    $("#buscador").on("typeahead:selected", function(e,datum) { 
			   // $codigo=datum.id;
			    $("#codigo").val(datum.id); 
			})







});
</script>
<body>
<br>
   
<!-- Small modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-sm">Small modal</button>

<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
    <div><br>
      <center> 
  

  <input  type="text" placeholder="Oscar winners for Best Picture" name="buscador" id="buscador">

      
</center>
      <br>
      <br>
      <center><input type="text" name="codigo" id="codigo" class="form-control" value=""></center>
      <br>
      <br>
      
     </div>
    </div>
  </div>
</div>


    
    </body>
</html>