

<script>

$(document).ready(function(){
	
			var dataClientes = new Bloodhound({
			  datumTokenizer: Bloodhound.tokenizers.obj.whitespace('value'),
			  queryTokenizer: Bloodhound.tokenizers.whitespace,
			  /*prefetch: '../../dispo/buscador/consultarclientefactura',*/
			  remote: {
			 	url : '../../dispo/buscador/consultarclientefactura?term=%QUERY',
				wildcard: '%QUERY'
			  }
			});	
	
			$('#buscador').typeahead(
				{
					highlight: true,
					minLength: 3	
				}, 
				{
				  name: 'data-clientes',
				  display: 'value',
				  source: dataClientes,
				  limit: 100
				}
			);
			
			/*  $('#buscador').typeahead({
				highlight: true
			  },
			  {
				source: dataClientes
			  });*/			
	
		   
		    $("#buscador").on("typeahead:selected", function(e,datum) { 
			   // $codigo=datum.id;
			    $("#codigo").val(datum.id); 
			})
	    

});
</script>
<body>
<br>
   
<!-- Small modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-sm">Small modal</button>

<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
    <div><br>
      <center>
      		<div class="scrollable-dropdown-menu">
	      		<input type="text" name="buscador" id="buscador" class="form-control" >
            </div>
      </center>
      <br>
      <br>
      <center><input type="text" name="codigo" id="codigo" class="form-control" value=""></center>
      <br>
      <br>
      
     </div>
    </div>
  </div>
</div>


    
    </body>
</html>