<?php echo $this->doctype(); ?>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <?php echo $this->headTitle($this->translate('AGRINAG - Dispo')) ?>

    <!-- Styles -->
	<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))								
					->appendStylesheet('http://fonts.googleapis.com/css?family=Muli')						
					->appendStylesheet($this->basePath() . '/css/bootstrap.css') 									
					->appendStylesheet($this->basePath() . '/css/main.css') 									
	?>		
    
    <!-- Scripts -->
	<?php echo $this->headScript()->appendFile($this->basePath() . '/js/scripts/jquery-1.11.1.min.js')
								  ->appendFile($this->basePath() . '/js/scripts/angular.min.js')
								  ->appendFile($this->basePath() . '/js/scripts/angular-route.js')
								  ->appendFile($this->basePath() . '/js/scripts/bootstrap.js')
								  ->appendFile($this->basePath() . '/js/scripts/behaviors.js')
	?>	
	
    
</head>
<body class="body-login">
    <form method="post" name="frm" action="<?php echo($this->basePath()); ?>/seguridad/login/autenticar">" >
        <div class="login-container">
            <div class="login-cont-header clearfix">
                <img class="flo-left" src="images/login-agr-logo.png" alt="Logo Agrinag">
                <h2 class="pull-right">
                    DISPONIBILIDAD - <b>AGRINAG</b>
                </h2>
            </div>
            <div class="login-cont-body">
                <div class="login-form-cont clearfix">
                   <div class="input-group flo-left">
                        <span class="input-group-addon">
                            <img src="images/user-login.png" alt="">
                        </span>
                        <input class="form-control" type="text" name="username" placeholder="USERNAME">
                   </div>
                   <div class="input-group flo-left">
                        <span class="input-group-addon">
                            <img src="images/key-login.png" alt="">
                        </span>
                        <input class="form-control pass-input" type="password" name="password" placeholder="PASSWORD">
                   </div>
                   <input type="submit" class="btn-login flo-left" value="Login" name="btnlogin" />
                   <p style="color:#FFFFFF">
						<?php		
						$mensaje = '';
						if ($this->flashMessages){
						    foreach($this->flashMessages as $message)
						    {
								$mensaje = $mensaje.$message;
						    }
							//echo '<script>message_alert("Mensaje del Sistema","'.$mensaje.'");</script>';	

							echo $mensaje;
						}//end if
						?>                   
                    </p>
                </div>
                                      
            </div>
            <div class="pull-right">
                <div class="img-circle social-icon flo-left">
                    <a href="http://www.facebook.com/agrinagrose" target="_blank"><img src="images/facebook-icon.png" alt=""></a>
                </div>
                <div class="img-circle social-icon flo-left">
                    <a href="http://instagram.com/agrinagrose" target="_blank"><img src="images/instag-icon.png" alt=""></a>
                </div>
                <div class="img-circle social-icon flo-left">
                    <a href="http://www.pinterest.com/agrinagroses/" target="_blank"><img src="images/pint-icon.png" alt=""></a>
                </div>
            </div>
        </div>
    </form>

</body>
</html>