
<script type="text/javascript" src="<?php echo($this->basePath('js/module/dispo/usuario/usuario.js')); ?>"></script>


<div class="title-admin-section">
	<h1>USUARIOS</h1>
</div>

 <div class="row">
	<section class="body-admin-section">    	
    	<div class="accion-admin-section"> 
    		<form id="frm_nuevo_usuario" class="form-horizontal" role="form" name="frm_nueva_agencia">
        	<div class="botonera-admin-section pull-left separator">
            	<a id="btn_nuevo" name="btn_nuevo" class="btn btn-primary btn-xs" href="#" role="button"><i class="glyphicon glyphicon-plus icon-white"></i> Nuevo</a>
            </div>
       	  </form>	
        	<div class="busqueda-admin-section pull-left">	
            	<!--- div class="form-inline" -->
                	
                <form id="frm_busqueda_usuario" action="<?php echo($this->basePath()); ?>/seguridad/usuario/mantenimiento" method="post">
	                <div class="input-group" style="display:inline-flex">    
	                	<input name="criterio_busqueda" id="criterio_busqueda" type="text" class="form-control input-sm" placeholder="Search" size="20" value="<?php echo($this->criterio_busqueda); ?>" />
	                     <div class="input-group">
							<select  name="busqueda_estado" id="busqueda_estado" class="form-control input-sm" style="width:130px">
		    	                <?php echo($this->cbo_busqueda_estado); ?>
	    	                </select>  
	                    </div>
	 					<span class="input-group-btn">
	 					  <select name="busqueda_perfil_id" id="busqueda_perfil_id"class="form-control input-sm">
	                    		<?php  echo($this->cbo_busqueda_perfil); ?>
	                    	</select> 
	                    	<button id="btn_consultar"  name="btn_consultar" class="btn btn-sm btn-primary" type="button"><i class="glyphicon glyphicon-search icon-white"></i> Buscar</button>
	                    </span> 
	                    <span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
	                    <span class="input-group">
	                    <button id="btn_excel" type="button" class="btn btn-sm btn-primary"> <i class="glyphicon glyphicon-download-alt"></i> Generar Reporte</button>
	                    </span>                           
	                </div>                
                </form>    
			
            </div>
      </div>
        <div class="clearfix"></div>
        <div>
			<table id="grid_usuario_listado" class="grid grid-autoheight"></table>
            <div id="pager_usuario_listado"></div>        	
        </div>
  </section>
</div>
 
    

            <!--  DIALOG DE MANTENIMIENTO -->
            <form id="frm_mantenimiento_usuario" name="frm">
			<div class="modal fade" id="dialog_mantenimiento" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			  <div class="modal-dialog">
			    <div class="modal-content">
			      <div class="modal-header">
			        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
			        <h4 class="modal-title" id="myModalLabel">USUARIO(<span id="dialog_mantenimiento_usuario_nombre"></span>)</h4>
			      </div>
			      <div class="modal-body clearfix">
			        <div class="clearfix">
                        
			        	  <table border="0" align="center" cellpadding="0" cellspacing="0" class="tbl_formulario_mantenimiento">
			        	      <tr>
			        	        <td><label class="control-label">ID:</label></td>
			        	        <td>
                                <input id="id" name="id" type="text" class="form-control input-sm" style="width:50px" value="" maxlength="3" max-lenght="3" disabled="disabled">
                                <input type="hidden" name="accion" id="accion" value="" /></td>
		        	          </tr>
			        	      <tr>
			        	        <td><label class="control-label">NOMBRE:</label></td>
			        	        <td><input name="nombre" type="text" class="form-control input-sm" id="nombre" style="width:350px" value="" maxlength="50" max-lenght="3" validate="required" validateMessage="Ingrese un nombre" onkeyup="this.value=this.value.toUpperCase()" ></td>
		        	          </tr>
			        	      <tr>
			        	        <td><label class="control-label">USUARIO:</label></td>
			        	        <td><input name="username" type="text" class="form-control input-sm" id="username" style="width:350px" value="" maxlength="20" validate="required" max-lenght="3"></td>
		        	          </tr>
			        	      <tr>
			        	        <td><label class="control-label">CLAVE:</label></td>
			        	        <td><input type="password" name="password"  class="form-control input-sm" id="password" style="width:350px" value="" maxlength="15"></td>
		        	          </tr>
		        	           <tr>
			        	        <td><label class="control-label">CONFIRMAR CLAVE:</label></td>
			        	        <td><input type="password" name="password2"  class="form-control input-sm" id="password2" style="width:350px" value="" maxlength="15"></td>
		        	          </tr>
		        	          <tr>
			        	        <td><label class="control-label">CORREO:</label></td>
			        	        <td><input type="email" name="email"  class="form-control input-sm" id="email" style="width:350px" value="" maxlength="50"  max-lenght="3" ></td>
		        	          </tr>
		        	          <tr>
			        	        <td><label class="control-label">LOGIN FOX:</label></td>
			        	        <td><input type="text" name="login_fox"  class="form-control input-sm" id="login_fox" style="width:350px" value="" maxlength="12" validate="required" max-lenght="12" ></td>
		        	          </tr>
			        	      <tr>
			        	        <td><label class="control-label">TIPO:</label></td>
			        	        <td><select  name="perfil_id" class="select-class2" id="perfil_id" validate="required"></select></td>
		        	          </tr>
			        	      <tr>
			        	        <td><label class="control-label">ESTADO:</label></td>
			        	        <td><select  name="estado" class="select-class2" id="estado"></select></td>
		        	          </tr>
			        	      <tr>
			        	        <td>&nbsp;</td>
			        	        <td>&nbsp;</td>
		        	        </tr>
			        	  
			        	      <tr>
			        	        <td><label class="control-label">Ingreso:</label></td>
			        	        <td><b><span id="lbl_usuario_ing"></span></b> - <span id="lbl_fec_ingreso"></span></td>
		        	          </tr>
			        	      <tr>
			        	        <td><label class="control-label">Modificación:</label></td>
			        	        <td><b><span id="lbl_usuario_mod"></span></b> - <span id="lbl_fec_modifica"></span></td>
		        	          </tr>
	        	      </table>
                      <br>
						<center><a id="btn_grabar" class="btn btn-small btn-success" href="#"><i class="glyphicon glyphicon-plus icon-save"></i> Grabar</a></center>
     
                      
		        	  <!--   div id="dialog_oferta_formulario"></div -->			
			        </div>
			      </div>
			    </div>
			  </div>
			</div>
			</form>
	