
<script>
	$(document).ready(function () {	
		InputData_TrimAll();
/*		InputData_KeyEnterDisabled();*/
//		InputData_initNumberAndDecimal();
		
		
		$('table').tablesorter(); //Columna de Sueldo
		$("table").stickyTableHeaders();


        $("#btn_consultar").on('click', function(event){ 
            $("#frm").submit();
			return false;
        });

        $("#btn_nuevo").on('click', function(event){
			nuevo(); 
			return false;
        });       

        $(".btn_edit").on('click', function(event){ 
			var tr 						= $(this).closest('tr');
			var usuario_id 		= tr.attr('usuario_id');

			consultar_usuario(usuario_id);
			//$("#dialog_mantenimiento").modal('show') 
        });
		
		
        $("#tbl_registros tbody tr").on('dblclick', function(event){ 
			var tr 						= $(this).closest('tr');
			var usuario_id 		= tr.attr('usuario_id');

			consultar_usuario(usuario_id);
			//$("#dialog_mantenimiento").modal('show') 
        });		

        $("#btn_grabar").on('click', function(event){ 
        	grabar();
			return false;
        });       

	});//$(document).ready
	
	
	function nuevo()
	{
		//Se llama mediante AJAX para adicionar al carrito de compras
		var data = 	{}
		data = JSON.stringify(data);
		
		var parameters = {	'type': 'POST',//'POST',
							'contentType': 'application/json',
							'url':'<?php echo($this->basePath()); ?>/seguridad/usuario/nuevodata',
							'control_process':true,
							'show_cargando':true,
							'finish':function(response){
									ValidateControlsInit();
									$("#accion").val("I");
									$("#dialog_mantenimiento_usuario_nombre").html("NUEVO REGISTRO");

									$("#usuario_id").val('');
									$("#usuario_id").prop('readonly',false);
									$("#nombre").val('');
									$("#username").val('');
									$("#password").val('');
									$("#email").val('');
									$("#perfil_id").html(response.cbo_perfil_id);
									$("#estado").html(response.cbo_estado);
									$("#lbl_usuario_ing").html('');
									$("#lbl_fec_ingreso").html('');
									$("#lbl_usuario_mod").html('');
									$("#lbl_fec_modifica").html('');									
									$("#dialog_mantenimiento").modal('show')
							}							
		                 }
		response = ajax_call(parameters, data);		
		return false;				
	}//end function nuevo
	
	function consultar_usuario(id)
	{
		//Se llama mediante AJAX para adicionar al carrito de compras
		var data = 	{usuario_id: id}
		data = JSON.stringify(data);
		
		var parameters = {	'type': 'POST',//'POST',
							'contentType': 'application/json',
							'url':'<?php echo($this->basePath()); ?>/seguridad/usuario/consultardata',
							'control_process':true,
							'show_cargando':true,
							'finish':function(response){
									mostrar_registro(response)
									cargador_visibility('hide');

									$("#dialog_mantenimiento").modal('show')
							}							
		                 }
		response = ajax_call(parameters, data);		
		return false;		
	}//end function consultar_usuario


	
	function ValidateControlAdicional()
	{
		//Validacion Customizada
		var valor1 = $("#password").val();
		var valor2 = $("#password2").val();
		var accion = $("#accion").val(); 

		if (accion == 'I'){
			if ($("#password").val()==''){
				mensaje = 'Debe ingresar una clave';
				return mensaje;
			}
			if ($("#password2").val()==''){
				mensaje = 'Debe ingresar la confirmacion de la clave';
				return mensaje;
			}//end if
		}//end if

		if ($("#password").val()!=''){
			if ($("#password").val() != $("#password2").val()){
				mensaje = 'La contraseña no coincide';
				return mensaje;
			}//end if
		}//end if
		if ($("#password2").val()!=''){
			if ($("#password").val() != $("#password2").val()){
				mensaje = 'La contraseña no coincide';
				return mensaje;
			}//end if
		}//end if

		return 'OK';
	}//end function ValidateControlAdicional

	

	function grabar(){

		if (!ValidateControls('frm')) {
			return false;
		}//end FuncionGrabar

		var mensaje = ValidateControlAdicional();

		if (mensaje!='OK')
		{
			swal({  title: mensaje,   
				//text: "Desea continuar utilizando la misma marcacion? Para seguir realizando mas pedidos",  
				//html:true,
				type: "warning",
				showCancelButton: false,
				confirmButtonColor: "#DD6B55",
				confirmButtonText: "OK",
				cancelButtonText: "",
				closeOnConfirm: false,
				closeOnCancel: false,
				/*timer: 2000*/
			});			
			return false;
		}//end if
		
		//Se llama mediante AJAX para adicionar al carrito de compras
		var data = 	{	accion: $("#accion").val(),
					 	id: $("#usuario_id").val(),
					 	nombre: $("#nombre").val(),
					 	username: $("#username").val(),					 	
					 	password: $("#password").val(),
					 	password2: $("#password2").val(),
					 	email: $("#email").val(),
					 	perfil_id: $("#perfil_id").val(),
					 	estado: $("#estado").val(),
					}
		data = JSON.stringify(data);
		
		var parameters = {	'type': 'POST',//'POST',
							'contentType': 'application/json',
							'url':'<?php echo($this->basePath()); ?>/seguridad/usuario/grabardata',
							'control_process':true,
							'show_cargando':true,
							'finish':function(response){
									if (response.validacion_code == 'OK')
									{
										mostrar_registro(response)
										cargador_visibility('hide');
										swal({  title: "Informacion grabada con exito!!",   
											//text: "Desea continuar utilizando la misma marcacion? Para seguir realizando mas pedidos",  
											//html:true,
											type: "success",
											showCancelButton: false,
											confirmButtonColor: "#DD6B55",
											confirmButtonText: "OK",
											cancelButtonText: "",
											closeOnConfirm: false,
											closeOnCancel: false,
											/*timer: 2000*/
										});
									}else{
										swal({title: response.respuesta_mensaje,   
											//text: "Desea continuar utilizando la misma marcacion? Para seguir realizando mas pedidos",  
											//html:true,
											type: "error",
											showCancelButton: false,
											confirmButtonColor: "#DD6B55",
											confirmButtonText: "OK",
											cancelButtonText: "",
											closeOnConfirm: false,
											closeOnCancel: false,
											/*timer: 2000*/
										});
									
									}									
							}							
		                 }
		response = ajax_call(parameters, data);		
			
		return false;		
	}//end function grabar


	function mostrar_registro(response)
	{
		var row = response.row;
		if (row!==null)
		{
			ValidateControlsInit();
			$("#accion").val("M");			
			$("#dialog_mantenimiento_usuario_nombre").html(row.nombre);
			$("#usuario_id").val(row.id);
			$("#usuario_id").prop('readonly',true);
			$("#nombre").val(row.nombre);
			$("#username").val(row.username);
			$("#password").val('');
			$("#email").val(row.email);
			$("#perfil_id").html(response.cbo_perfil_id);
			$("#estado").html(response.cbo_estado);
			$("#lbl_usuario_ing").html(row.usuario_ing_user_name);
			$("#lbl_fec_ingreso").html(row.fec_ingreso);
			$("#lbl_usuario_mod").html(row.usuario_mod_user_name);
			$("#lbl_fec_modifica").html(row.fec_modifica);
			
	/*		if (row.sincronizado==1)
			{
				$("#sincronizado_pendiente").hide();
				$("#sincronizado_ok").show();
			}else{
				$("#sincronizado_pendiente").show();
				$("#sincronizado_ok").hide();
			}//end if

	*/
			
		}//end if
	}//end function mostrar_registro
	
</script>

<div class="title-admin-section">
	<h1>USUARIOS</h1>
</div>

<div class="table-container col-md-16 col-sm-16">
  <div class="clearfix">
        	<div class="pull-left">
            	<a id="btn_nuevo" class="btn btn-small btn-success" href="#"><i class="glyphicon glyphicon-plus icon-white"></i> Nuevo</a>
            </div>
        	<div class="pull-right">
            	<div class="form-inline">
                	<form id="frm" action="<?php echo($this->basePath()); ?>/seguridad/usuario/mantenimiento" method="post" >
                    <input name="criterio_busqueda" type="text" class="select-class2" placeholder="Search" size="20" value="<?php echo($this->criterio_busqueda); ?>" />
                    <select  name="busqueda_estado" class="select-class2">
                        <?php echo($this->cbo_busqueda_estado); ?>
                    </select>
                    <select name="busqueda_perfil_id" class="select-class2">
                    	<?php  echo($this->cbo_busqueda_perfil); ?>
                    </select>
                    <a id="btn_consultar" class="btn btn-small btn-success" href="#"><i class="glyphicon glyphicon-search icon-white"></i></a>
                    </form>
				</div>
            </div>
       </div>
		<table id="tbl_registros" class="clear table-head table-dispo tablesorter tableinit tablesorter_numberrow">
			<thead>
				<tr>
				  <th  width="50" rowspan="2" class="th-inner">&nbsp;</th>
					<th  width="100" rowspan="2" class="th-inner">ID</th>				
					<th  width="0" rowspan="2" class="th-inner">NOMBRE</th>
					<th  width="0" rowspan="2" class="th-inner">USUARIO</th>
					<th  width="150" rowspan="2" class="th-inner">EMAIL</th>
					<th  width="50" rowspan="2" class="th-inner">PERFIL</th>
					<th  width="70" rowspan="2" class="th-inner">ESTADO</th>
					<th  width="70" rowspan="2" class="th-inner">&nbsp;</th>
				</tr>
			</thead>
			<tbody class="searchable" style="border: 1px solid #cdcdcd;">
<?php  
		$i=0;
		foreach($this->result as $reg)
		{
			$i++;
			$class_row = '';
			if ($reg['estado']=='I'){
				$class_row = 'row_estado_inactivo';
			}
?>            
				<tr usuario_id="<?php echo($reg['id']); ?>" class="<?php echo($class_row); ?>" >
				  <td><?php echo($i); ?></td>
					<td><?php echo($reg['id']); ?></td>
					<td align="left"><?php echo($reg['nombre']); ?></td>
					<td><?php echo($reg['username']); ?></td>
					<td><?php echo($reg['email']); ?></td>
					<td><?php echo($reg['perfil_nombre']); ?></td>
					<td><?php echo($reg['estado']); ?></td>
					<td><a href="#" class="btn_edit"><i class="glyphicon glyphicon-pencil icon-white" style="color:orange"></i></a></td>
				</tr>
<?php	}//end foreach ?>		
			</tbody>
		</table>    
				
    </div>
    

            <!--  DIALOG DE MANTENIMIENTO -->
            <form id="frm">
			<div class="modal fade" id="dialog_mantenimiento" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			  <div class="modal-dialog">
			    <div class="modal-content">
			      <div class="modal-header">
			        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
			        <h4 class="modal-title" id="myModalLabel">USUARIO(<span id="dialog_mantenimiento_usuario_nombre"></span>)</h4>
			      </div>
			      <div class="modal-body clearfix">
			        <div class="clearfix">
                        
			        	  <table border="0" align="center" cellpadding="0" cellspacing="0" class="tbl_formulario_mantenimiento">
			        	      <tr>
			        	        <td><label class="control-label">ID:</label></td>
			        	        <td>
                                <input id="usuario_id" name="usuario_id" type="text" class="form-control input-sm" style="width:50px" value="" maxlength="3" max-lenght="3" disabled="disabled">
                                <input type="hidden" name="accion" id="accion" value="" /></td>
		        	          </tr>
			        	      <tr>
			        	        <td><label class="control-label">NOMBRE:</label></td>
			        	        <td><input name="nombre" type="text" class="form-control input-sm" id="nombre" style="width:350px" value="" maxlength="50" max-lenght="3" validate="required" validateMessage="Ingrese un nombre" onkeyup="this.value=this.value.toUpperCase()" ></td>
		        	          </tr>
			        	      <tr>
			        	        <td><label class="control-label">USUARIO:</label></td>
			        	        <td><input name="username" type="text" class="form-control input-sm" id="username" style="width:350px" value="" maxlength="20" validate="required" max-lenght="3"></td>
		        	          </tr>
			        	      <tr>
			        	        <td><label class="control-label">CLAVE:</label></td>
			        	        <td><input type="password" name="password"  class="form-control input-sm" id="password" style="width:350px" value="" maxlength="15"></td>
		        	          </tr>
		        	           <tr>
			        	        <td><label class="control-label">CONFIRMAR CLAVE:</label></td>
			        	        <td><input type="password" name="password2"  class="form-control input-sm" id="password2" style="width:350px" value="" maxlength="15"></td>
		        	          </tr>
		        	           <tr>
			        	        <td><label class="control-label">CORREO:</label></td>
			        	        <td><input type="email" name="email"  class="form-control input-sm" id="email" style="width:350px" value="" maxlength="50" validate="required" max-lenght="3" ></td>
		        	          </tr>
			        	      <tr>
			        	        <td><label class="control-label">TIPO:</label></td>
			        	        <td><select  name="perfil_id" class="select-class2" id="perfil_id" validate="required"></select></td>
		        	          </tr>
			        	      <tr>
			        	        <td><label class="control-label">ESTADO:</label></td>
			        	        <td><select  name="estado" class="select-class2" id="estado"></select></td>
		        	          </tr>
			        	      <tr>
			        	        <td>&nbsp;</td>
			        	        <td>&nbsp;</td>
		        	        </tr>
			        	  
			        	      <tr>
			        	        <td><label class="control-label">Ingreso:</label></td>
			        	        <td><b><span id="lbl_usuario_ing"></span></b> - <span id="lbl_fec_ingreso"></span></td>
		        	          </tr>
			        	      <tr>
			        	        <td><label class="control-label">Modificación:</label></td>
			        	        <td><b><span id="lbl_usuario_mod"></span></b> - <span id="lbl_fec_modifica"></span></td>
		        	          </tr>
	        	      </table>
                      <br>
						<center><a id="btn_grabar" class="btn btn-small btn-success" href="#"><i class="glyphicon glyphicon-plus icon-save"></i> Grabar</a></center>
     
                      
		        	  <!--   div id="dialog_oferta_formulario"></div -->			
			        </div>
			      </div>
			    </div>
			  </div>
			</div>
			</form>
	